import { Anime } from "../modeles/anime";


export const BERSERK : Anime[] =[
  {
    episode: 1,
    season: 1,
    title : 'Le guerrier noir',
    summary: 'Guts, se rend a Midland pour se battre contre le seigneur du fief afin d\'y acquérir le Béhélit. La série commence réellement au 2ème épisode.',
    type: 'Seinen',
    picture: '../assets/berserk/001.jpeg',
    created: new Date('08 octobre 1997'),
    link1: '//ok.ru/videoembed/1131157719686',
    link2: '',
    link3: '',
  },
  {
    episode: 2,
    season: 1,
    title : 'L\'unité du Faucon',
    summary: 'A la suite de sa victoire contre le puissant Bazooso, Guts se fait attaquer par un groupe de mercenaires : l\'unité du faucon menée par Griffith..',
    type: 'Seinen',
    picture: '../assets/berserk/002.jpeg',
    created: new Date('15 octobre 1997'),
    link1: '//ok.ru/videoembed/1131158047366',
    link2: '',
    link3: '',
  },
  {
    episode: 3,
    season: 1,
    title : 'Baptême du feu',
    summary: 'C\'est à l\'issue de son combat contre Griffith que Guts intègre l\'unité du faucon, mais une partie de ceux ci ne tolère pas son intégration. Durant l\'attaque d\'un groupe ennemi, Guts se voit confier le poste d\'arrière garde, rôle qu\'il remplira avec succès le conduisant, petit à petit, à trouver sa place au sein du groupe...',
    type: 'Seinen',
    picture: '../assets/berserk/003.jpeg',
    created: new Date('22 octobre 1997'),
    link1: '//ok.ru/videoembed/1131158178438',
    link2: '',
    link3: '',
  },
  {
    episode: 4,
    season: 1,
    title : 'La Main de Dieu',
    summary: 'En combattant les troupes de l\'empire de Tudor, le royaume de l\'est, Guts se remémore son enfance, comment il en est venu à être mercenaire, formé par l\'homme qu\'il considérait comme son père : Gambino...',
    type: 'Seinen',
    picture: '../assets/berserk/004.jpeg',
    created: new Date('29 octobre 1997'),
    link1: '//ok.ru/videoembed/1131158309510',
    link2: '',
    link3: '',
  },
  {
    episode: 5,
    season: 1,
    title : 'L\'Epée du Vent',
    summary: '3 ans ont passé, l\'unité du faucon a remportée victoire sur victoire. Guts est désormais commandant et Griffith, leader des faucons, est fait chevalier par le roi du Midland. Maintenant l\'unité des faucons n\'a plus le statut de mercenaire mais de soldat...',
    type: 'Seinen',
    picture: '../assets/berserk/005.jpeg',
    created: new Date('05 novembre 1997'),
    link1: '//ok.ru/videoembed/1131158440582',
    link2: '',
    link3: '',
  },
  {
    episode: 6,
    season: 1,
    title : 'Zodd l\'Immortel',
    summary: 'Lors de la prise d\'un château de Tudor, l\'unité du faucon se retrouve confronté à un problème de taille: Nosferatu Zodd surnommé Zodd l\'immortel. Guts et Griffith devront se mettre à deux pour affronter ce démon...',
    type: 'Seinen',
    picture: '../assets/berserk/006.jpeg',
    created: new Date('12 novembre 1997'),
    link1: '//ok.ru/videoembed/1131158571654',
    link2: '',
    link3: '',
  },
  {
    episode: 7,
    season: 1,
    title : 'Maître d\'arme',
    summary: 'Tout au long de cet épisode on peut ressentir les émotions et sentiments que ressentent Griffith, Guts et Casca. On assistera à la 1ère rencontre entre Griffith et la fille du roi du Midland : Charlotte...',
    type: 'Seinen',
    picture: '../assets/berserk/007.jpeg',
    created: new Date('19 novembre 1997'),
    link1: '//ok.ru/videoembed/1131158702726',
    link2: '',
    link3: '',
  },
  {
    episode: 8,
    season: 1,
    title : 'Conspiration',
    summary: 'Bataille stratégique pour la prise d\'un pont que détient Sir Adon, sujet de Tudor. Ce sera avec ruse que se déroulera l\'affrontement. A la suite de cela, Griffith sera promu au rang de comte...',
    type: 'Seinen',
    picture: '../assets/berserk/008.jpeg',
    created: new Date('26 novembre 1997'),
    link1: '//ok.ru/videoembed/1131158833798',
    link2: '',
    link3: '',
  },
  {
    episode: 9,
    season: 1,
    title : 'Tentative d\'assassinat',
    summary: 'Lors de la chasse d’automnes organisée pour le plaisir du Midland, dont la protection est confiée à l’unité du faucon, un complot, mené par le frère du Julius le général des dragons blancs, vise à assassiner Griffith...',
    type: 'Seinen',
    picture: '../assets/berserk/009.jpeg',
    created: new Date('03 décembre 1997'),
    link1: '//ok.ru/videoembed/1131159292550',
    link2: '',
    link3: '',
  },
  {
    episode: 10,
    season: 1,
    title : 'Aristocrate',
    summary: 'Guts se charge des représailles envers celui qui a tenté d’assassiner Griffith : Lord Julius. De son côté Griffith est invité au bal par la princesse Charlotte...',
    type: 'Seinen',
    picture: '../assets/berserk/010.jpeg',
    created: new Date('10 décembre 1997'),
    link1: '//ok.ru/videoembed/1131158964870',
    link2: '',
    link3: '',
  },
  {
    episode: 11,
    season: 1,
    title : 'Un combat',
    summary: 'Les sentiments de la princesse Charlotte pour Griffith sont mis à nu, mais la reine ne semble l’approuver. Une grande bataille va faire rage entre l’armée de Tudor menée par Sir Adon et l’armée du faucon de Midland...',
    type: 'Seinen',
    picture: '../assets/berserk/011.jpeg',
    created: new Date('17 décembre 1997'),
    link1: '//ok.ru/videoembed/1131159095942',
    link2: '',
    link3: '',
  },
  {
    episode: 12,
    season: 1,
    title : 'Deux personnes',
    summary: 'Suite au combat, Guts et Casca se retrouvent seuls. Celle-ci explique à Guts pourquoi elle a rejoint l’unité du faucon. La jalousie de Casca, cachée jusqu’ici, apparaît au grand jour...',
    type: 'Seinen',
    picture: '../assets/berserk/012.jpeg',
    created: new Date('24 décembre 1997'),
    link1: '//ok.ru/videoembed/1131159227014',
    link2: '',
    link3: '',
  },
  {
    episode: 13,
    season: 1,
    title : 'Combattre jusqu\'à la mort',
    summary: 'Guts et Casca affrontent le restant des troupes de l\'empire de Tudor et font en particulier face à Samson, le petit frère de Sir Adon, le meilleur guerrier de l’armée. Casca se rend compte de l\'importance de l’amitié que lui témoigne Guts...',
    type: 'Seinen',
    picture: '../assets/berserk/013.jpeg',
    created: new Date('07 janvier 1998'),
    link1: '//ok.ru/videoembed/1131159161478',
    link2: '',
    link3: '',
  },
  {
    episode: 14,
    season: 1,
    title : 'Rêve en feu de joie',
    summary: 'Guts met en pièces une centaine de soldats afin que Casca puisse s’enfuir. De retour au camp, Guts s\'interroge sur ses raisons de se battre tandis que ses liens avec Casca se renforcent...',
    type: 'Seinen',
    picture: '../assets/berserk/014.jpeg',
    created: new Date('14 janvier 1998'),
    link1: '//ok.ru/videoembed/1131159030406',
    link2: '',
    link3: '',
  },
  {
    episode: 15,
    season: 1,
    title : 'Combat décisif',
    summary: 'Du fait de la défaite des Tigres Blancs du Midland face aux Rhinocéros Pourpres menés par le général Boscogne, le roi décide d’envoyer l’unité du faucon sur le front afin de reprendre le château de Dordrey détenu depuis un siècle par l\'empire de Tudor. Il s’en suit une grande bataille entre l’unité du faucon et les rhinocéros pourpres...',
    type: 'Seinen',
    picture: '../assets/berserk/015.jpeg',
    created: new Date('21 janvier 1998'),
    link1: '//ok.ru/videoembed/1131158899334',
    link2: '',
    link3: '',
  },
  {
    episode: 16,
    season: 1,
    title : 'Le conquérant',
    summary: 'L’unité du faucon n’a pas eu de mal à pénétrer dans l’enceinte du château de Dordrey. Cependant Guts et la troupe ne se doutent pas du piège que leur a tendu Sir Adon... Une confrontation s’opère entre Guts et le général Boscogne...',
    type: 'Seinen',
    picture: '../assets/berserk/016.jpeg',
    created: new Date('28 janvier 1998'),
    link1: '//ok.ru/videoembed/1131158768262',
    link2: '',
    link3: '',
  },
  {
    episode: 17,
    season: 1,
    title : 'Moment de gloire',
    summary: 'Victorieux et acclamés par la foule en liesse, Griffith, Guts, Casca et le reste de l’unité du faucon font leur entrée dans la cour de Midland. En revanche, la reine et certains aristocrates ne partagent pas ce point de vue...',
    type: 'Seinen',
    picture: '../assets/berserk/017.jpeg',
    created: new Date('4 février 1998'),
    link1: '//ok.ru/videoembed/1131158637190',
    link2: '',
    link3: '',
  },
  {
    episode: 18,
    season: 1,
    title : 'Pierre tombale de flammes',
    summary: 'Au cours de la fête organisée en l’honneur de la victoire et la prise du château de Dordrey par L’unité du faucon, les aristocrates au service de la reine font portés un verre empoisonné à Griffith...',
    type: 'Seinen',
    picture: '../assets/berserk/018.jpeg',
    created: new Date('11 février 1998'),
    link1: '//ok.ru/videoembed/1131158506118',
    link2: '',
    link3: '',
  },
  {
    episode: 19,
    season: 1,
    title : 'Au revoir',
    summary: 'Après avoir longuement réfléchi, Guts décide de quitter l’unité du faucon afin de poursuivre ses propres rêves et non pas ceux de Griffith bien qu\'il ait conclu auparavant un marché avec celui-ci...',
    type: 'Seinen',
    picture: '../assets/berserk/019.jpeg',
    created: new Date('18 février 1998'),
    link1: '//ok.ru/videoembed/1131158375046',
    link2: '',
    link3: '',
  },
  {
    episode: 20,
    season: 1,
    title : 'Etincelle enflammée',
    summary: 'A la suite de son aventure avec la princesse Charlotte, Griffith se fait emprisonner. Ayant quitté les faucons, Guts se retrouve chez un forgeron du nom de Godou. Là, il décide de brandir son épée non plus pour les autres, mais pour lui-même...',
    type: 'Seinen',
    picture: '../assets/berserk/020.jpeg',
    created: new Date('25 février 1998'),
    link1: '//ok.ru/videoembed/1131158243974',
    link2: '',
    link3: '',
  },
  {
    episode: 21,
    season: 1,
    title : 'Une confession',
    summary: 'La foi renaît au cœur du clan du faucon grâce au retour de Guts qui comment à nouer une liaison amoureuse avec Casca. Le clan du faucon réunifié décide d’aller libérer Griffith...',
    type: 'Seinen',
    picture: '../assets/berserk/021.jpeg',
    created: new Date('04 mars 1998'),
    link1: '//ok.ru/videoembed/1131157981830',
    link2: '',
    link3: '',
  },
  {
    episode: 22,
    season: 1,
    title : 'L\'infiltration',
    summary: 'Pour délivrer Griffith, Guts, Casca et les autres infiltrent le château du Midland. En voyant Griffith si mal en point, Guts déchaîne sa colère...',
    type: 'Seinen',
    picture: '../assets/berserk/022.jpeg',
    created: new Date('11 mars 1998'),
    link1: '//ok.ru/videoembed/1131157916294',
    link2: '',
    link3: '',
  },
  {
    episode: 23,
    season: 1,
    title : 'La veille du Festival',
    summary: 'Guts et les autres ont réussi à sauver Griffith et à échapper à l’armée du Midland. Par la suite, Griffith retrouve le Béhélit rouge qu’il avait perdu dans sa cellule. Il a alors rendez vous avec les Diables...',
    type: 'Seinen',
    picture: '../assets/berserk/023.jpeg',
    created: new Date('18 mars 1998'),
    link1: '//ok.ru/videoembed/1131157785222',
    link2: '',
    link3: '',
  },
  {
    episode: 24,
    season: 1,
    title : 'L\'Eclipse',
    summary: 'Le Béhélit de Griffith prend soudainement la forme d’une tête et alors apparaît une éclipse. De plus, le sol se transforme en une multitude de têtes tandis que des monstres apparaissent. Le festival vient de commencer...',
    type: 'Seinen',
    picture: '../assets/berserk/024.jpeg',
    created: new Date('25 mars 1998'),
    link1: '//ok.ru/videoembed/1131158112902',
    link2: '',
    link3: '',
  },
  {
    episode: 25,
    season: 1,
    title : 'Le Moment Eternel',
    summary: 'Le festival est le lieu d\'une véritable hécatombe. Pratiquement tout le monde se fait dévorer bien que Guts fasse un vrai carnage sur les monstres. Griffith, quant à lui, devient le cinquième Roi Béni : le nouveau Roi Démon...',
    type: 'Seinen',
    picture: '../assets/berserk/025.jpeg',
    created: new Date('01 avril 1998'),
    link1: '//ok.ru/videoembed/1131157850758',
    link2: '',
    link3: '',
  },
]
