import { Anime } from "../modeles/anime";


export const COWBOYBEBOP: Anime[] = [
  {
    episode: 1,
    season: 1,
    title: 'Asteroid Blues',
    summary: 'Spike et Jet sont à court d\'argent en ce moment. Pas question donc de rater leur prochaine cible: Asimov Solensan. Ce dernier se cache actuellement sur l\'astéroïde Tikuana, et aurait volé le stock d\'une drogue qu\'on s\'injecte sur la prunelle...',
    type: 'Shonen',
    picture: '../assets/cowboyBebop/001.jpeg',
    created: new Date('23 octobre 1998'),
    link1: 'https://www.youtube.com/embed/TILb92S1THU',
    link2: '',
    link3: '',
  },
  {
    episode: 2,
    season: 1,
    title: 'Stray Dog Strut',
    summary: 'Ein, le chien surdoué, a été capturé dans un laboratoire par Abdul Hakim, un voleur animalier. Spike et Jet se lancent à sa poursuite, puis décident bientôt d\'adopter la petite bête...',
    type: 'Shonen',
    picture: '../assets/cowboyBebop/002.jpeg',
    created: new Date('30 octobre 1998'),
    link1: 'https://www.youtube.com/embed/DR07I6M0KQ4',
    link2: '',
    link3: '',
  },
  {
    episode: 3,
    season: 1,
    title: 'Honky Tonk Woman',
    summary: 'Miss Faye Valentine est kidnappée par le patron d\'un casino, qui veut se servir d\'elle pour récupérer une micropuce, caché dans un jeton ,en échange de quoi il effacera ses dettes. Spike et de Jet sont de passage dans ce même casino...',
    type: 'Shonen',
    picture: '../assets/cowboyBebop/003.jpeg',
    created: new Date('6 novembre 1998'),
    link1: "https://www.youtube.com/embed/otzvUEpbY0I",
    link2: '',
    link3: '',
  },
  {
    episode: 4,
    season: 1,
    title: 'Gateway Shuffle',
    summary: 'Spike et Jet retrouvent Faye, en panne d\'essence. Elle devient membre de l\'équipage du Bebop. Spike et Jet ont cette fois arrêté la chef des Space Warriors, une associations de "terroristes écologiques", qui lutte pour défendre les lois de la nature...',
    type: 'Shonen',
    picture: '../assets/cowboyBebop/004.jpeg',
    created: new Date('13 novembre 1998'),
    link1: 'https://www.youtube.com/embed/U0O96VrisDg',
    link2: '',
    link3: '',
  },
  {
    episode: 5,
    season: 1,
    title: 'Ballad of fallen angels',
    summary: 'Vicious tue Mao Yenraï, qui était son chef à l\'époque où lui et Spike étaientt dans la mafia chinoise, les dragons rouges. Cette manoeuvre a pour but de faire venir Spike à lui. Voyant le montant de la prime reposant sur la tête de Mao Yenraï, Faye décide de s\'en occuper...',
    type: 'Shonen',
    picture: '../assets/cowboyBebop/005.jpeg',
    created: new Date('20 novembre 1998'),
    link1: 'https://www.youtube.com/embed/TVLhFArjNxw',
    link2: '',
    link3: '',
  },
  {
    episode: 6,
    season: 1,
    title: 'Sympathy for the devil',
    summary: 'Sur le point de mourir, Giraffe (que Spike poursuivait) lui demande d\'aider un enfant prodige du Jazz avec une pierre provenant de l\'explosion de la Gate. Et surtout de ne pas se laisser duper par son apparence d\'enfant de 10 ans...',
    type: 'Shonen',
    picture: '../assets/cowboyBebop/006.jpeg',
    created: new Date('27 novembre 1998'),
    link1: 'https://www.youtube.com/embed/dTXXpxq3wgo',
    link2: '',
    link3: '',
  },
  {
    episode: 7,
    season: 1,
    title: 'Heavy metal queen',
    summary: "Faye et Spike sont à la poursuite d'un spécialiste des explosions. Ils rencontrent au passage VT, une 'camionneuse' de l'espace, fan de Heavy Metal, dont le nom est inconnu de tous...",
    type: 'Shonen',
    picture: '../assets/cowboyBebop/007.jpeg',
    created: new Date('4 décembre 1998'),
    link1: 'https://www.youtube.com/embed/FB1HPdrCEOU',
    link2: '',
    link3: '',
  },
  {
    episode: 8,
    season: 1,
    title: 'Waltz for Venus',
    summary: "Spike et Faye procèdent à l'arrestation de malfrats qui tentaient d'effectuer un cambriolage sur un vol en partance pour Vénus. Faye va déposer son argent au casino. Spike rencontre Rocco, un petit truand qui s'est mis toute sa bande à dos, après avoir volé une plante...",
    type: 'Shonen',
    picture: '../assets/cowboyBebop/008.jpeg',
    created: new Date('11 décembre 1998'),
    link1: 'https://www.youtube.com/embed/PN1Qdog2ZWA',
    link2: '',
    link3: '',
  },
  {
    episode: 9,
    season: 1,
    title: 'Jamming with Edward',
    summary: "Jet et Fay sont à la recherche d'un célèbre hacker, qui aurait utilisé des satellites pour des graffitis. Mais personne ne la jamais vu et ne sait à quoi il ressemble...",
    type: 'Shonen',
    picture: '../assets/cowboyBebop/009.jpeg',
    created: new Date('18 décembre 1998'),
    link1: 'https://www.youtube.com/embed/WoYOfGlqozQ',
    link2: '',
    link3: '',
  },
  {
    episode: 10,
    season: 1,
    title: 'Ganymede elegy',
    summary: "Jet est de retour sur Ganymede, la planète ou il été policier, et où il avait autrefois une petit amie, Alissa. Cette dernière l'a quitté un jour sans la moindre explication. Elle à un nouveau petit ami, mais il s'avère que celui-ci est recherché par la police...",
    type: 'Shonen',
    picture: '../assets/cowboyBebop/010.jpeg',
    created: new Date('1 janvier 1999'),
    link1: 'https://www.youtube.com/embed/-RQ38w6h3z8',
    link2: '',
    link3: '',
  },
  {
    episode: 11,
    season: 1,
    title: 'Toys in the Attic',
    summary: "Tous les membres du Bebop sont victimes d'une attaque, dans leur propre vaisseau, par une créature biologique inconnue. Seul Spike parvient à lui échapper, et finit par découvrir que la créature est un homard, laissé plus d'un an au frigo...",
    type: 'Shonen',
    picture: '../assets/cowboyBebop/011.jpeg',
    created: new Date('8 janvier 1999'),
    link1: 'https://www.youtube.com/embed/ONWhV080SmA',
    link2: '',
    link3: '',
  },
  {
    episode: 12,
    season: 1,
    title: 'Jupiter jazz 1/2',
    summary: "Vicious se retrouve mêlé à un trafic de Red Eye, dont le code est 'Julia'. Spike, Ed et Jet tombent bientôt sur ce code en cherchant Faye, qui s'est enfuie du Bebop en emportant l'argent avec elle...",
    type: 'Shonen',
    picture: '../assets/cowboyBebop/012.jpeg',
    created: new Date('15 janvier 1999'),
    link1: 'https://www.youtube.com/embed/Gs6IBkPBA1E',
    link2: '',
    link3: '',
  },
  {
    episode: 13,
    season: 1,
    title: 'Jupiter jazz 2/2',
    summary: "Spike a survécu grâce à des anesthésiants. Glen et Vicious furent amis alors qu'ils étaient mercenaires sur Titan, mais à leur retour, Vicious n'hésita pas à le balancer comme espion...",
    type: 'Shonen',
    picture: '../assets/cowboyBebop/013.jpeg',
    created: new Date('22 janvier 1999'),
    link1: 'https://www.youtube.com/embed/SqwYJgwFg7Q',
    link2: '',
    link3: '',
  },
  {
    episode: 14,
    season: 1,
    title: 'Bohemian rhapsody',
    summary: "Toute l'équipe se lance à la recherche d'un homme suspecté d'avoirtrafiqué la Gate. Il se trouve en outre être un champion d'échec à demi fou...",
    type: 'Shonen',
    picture: '../assets/cowboyBebop/014.jpeg',
    created: new Date('29 janvier 1999'),
    link1: 'https://www.youtube.com/embed/woumGVNTfF0',
    link2: '',
    link3: '',
  },
  {
    episode: 15,
    season: 1,
    title: 'My funny Valentine',
    summary: "Tandis que Jet est parti chasser la prime, Faye révèle des bribes de son passé à Ein. Elle aurait été congelée durant 514 ans, er l'origine de ses dettes est en fait la somme d'argent, dûe au docteur qui l'a sorti du frigo...",
    type: 'Shonen',
    picture: '../assets/cowboyBebop/015.jpeg',
    created: new Date('5 février 1999'),
    link1: 'https://www.youtube.com/embed/NnPggsy09mg',
    link2: '',
    link3: '',
  },
  {
    episode: 16,
    season: 1,
    title: 'Black dog serenade',
    summary: "Une mutinerie de prisonniers réunit Jet et son ancien partenaire, car l' un des prisonnier est responsable de la perte de son bras...",
    type: 'Shonen',
    picture: '../assets/cowboyBebop/016.jpeg',
    created: new Date('12 février 1999'),
    link1: 'https://www.youtube.com/embed/cJX-Vk-1nng',
    link2: '',
    link3: '',
  },
  {
    episode: 17,
    season: 1,
    title: 'Mushroom samba',
    summary: "Rien ne va plus à bord du Bebop, privé de carburant et de nourriture. Comme si cela ne suffisait pas, une collision avec un autre vaisseau a dévié la trajectoire de l'engin...",
    type: 'Shonen',
    picture: '../assets/cowboyBebop/017.jpeg',
    created: new Date('19 février 1999'),
    link1: 'https://www.youtube.com/embed/B2VteDmlqD4',
    link2: '',
    link3: '',
  },
  {
    episode: 18,
    season: 1,
    title: 'Speak like a child',
    summary: "Ouvrant le colis que Faye Valentine vient de recevoir, Spike découvre une cassette vidéo - une véritable relique ! Reste à trouver un lecteur, qui lui permettrait de la visionner...",
    type: 'Shonen',
    picture: '../assets/cowboyBebop/018.jpeg',
    created: new Date('26 février 1999'),
    link1: 'https://www.youtube.com/embed/fnLYFSJcR3U',
    link2: '',
    link3: '',
  },
  {
    episode: 19,
    season: 1,
    title: 'Wild horses',
    summary: "Spike confie son vaisseau au vieux Duhan, un passionné d'aviation, afin que celui-ci procède à quelques révisions. Le reste de l'équipe se lance à la poursuite des Starship pirates...",
    type: 'Shonen',
    picture: '../assets/cowboyBebop/019.jpeg',
    created: new Date('5 mars 1999'),
    link1: 'https://www.youtube.com/embed/ybbkki2jK9k',
    link2: '',
    link3: '',
  },
  {
    episode: 20,
    season: 1,
    title: 'Pierrot le fou',
    summary: "Spike se retrouve nez à nez avec un homme qui tue les haut rang de l' I.S.S.P. Ce fou l'invite a une grande fête, que Spike ne peut refuser...",
    type: 'Shonen',
    picture: '../assets/cowboyBebop/020.jpeg',
    created: new Date('12 mars 1999'),
    link1: 'https://www.youtube.com/embed/duGKB5fFfuw',
    link2: '',
    link3: '',
  },
  {
    episode: 21,
    season: 1,
    title: ' Boogie woogie feng-shui',
    summary: "Jet reçoit un mystérieux e-mail, d'une vieille connaissance, Pao, maître de Feng-Shui. Ce message le met sur la piste d'un gang et d'une certaine Meifa, qui n'est autre que la fille de Pao...",
    type: 'Shonen',
    picture: '../assets/cowboyBebop/021.jpeg',
    created: new Date('19 mars 1999'),
    link1: 'https://www.youtube.com/embed/nY6qggEhVLQ',
    link2: '',
    link3: '',
  },
  {
    episode: 22,
    season: 1,
    title: 'Cow boy funk',
    summary: "Alors qu'il traque un poseur de bombes, Spike tombe sur Andy, un authentique cow-boy, et surtout, son principal concurrent...",
    type: 'Shonen',
    picture: '../assets/cowboyBebop/022.jpeg',
    created: new Date('26 mars 1999'),
    link1: 'https://www.youtube.com/embed/wHjXUgY0PDE',
    link2: '',
    link3: '',
  },
  {
    episode: 23,
    season: 1,
    title: 'Brain scratch',
    summary: "Faye est chargée d'infiltrer une secte dont les adeptes se suicident un peu trop souvent, et dont le gourou, le docteur Londes, est recherché pour meurtre...",
    type: 'Shonen',
    picture: '../assets/cowboyBebop/023.jpeg',
    created: new Date('2 avril 1999'),
    link1: 'https://www.youtube.com/embed/GePJ2tZjxOQ',
    link2: '',
    link3: '',
  },
  {
    episode: 24,
    season: 1,
    title: 'Hard luck woman',
    summary: "Faye débarque sur Terre afin de retrouver quelques souvenirs de son passé. Ed en profite pour rendre visite à sa soeur Clara, responsable de l'orphelinat dans lequel elle a autrefois grandi..",
    type: 'Shonen',
    picture: '../assets/cowboyBebop/024.jpeg',
    created: new Date('9 avril 1999'),
    link1: 'https://www.youtube.com/embed/iquXkxxuSEU',
    link2: '',
    link3: '',
  },
  {
    episode: 25,
    season: 1,
    title: ' The real folk blues 1/2',
    summary: "Vicious tente d'abattre Van, le leader de l'organisation criminelle des Dragons Rouges, mais il échoue. Van décide alors d'éliminer tous ceux qui ont un lien avec Vicious...",
    type: 'Shonen',
    picture: '../assets/cowboyBebop/025.jpeg',
    created: new Date('16 avril 1999'),
    link1: 'https://www.youtube.com/embed/4e57uni1ng8',
    link2: '',
    link3: '',
  },
  {
    episode: 26,
    season: 1,
    title: 'The real folk blues 2/2',
    summary: "Spike et Julia se retrouvent face à face au cimetière. En pointant son arme sur lui, Julia lui explique qie Vicious l'avait obligé à le tuer ou a mourir...",
    type: 'Shonen',
    picture: '../assets/cowboyBebop/026.jpeg',
    created: new Date('23 novembre 1998'),
    link1: 'https://www.youtube.com/embed/iC_W4TkOzp8',
    link2: '',
    link3: '',
  },
]
