import { Anime } from "../modeles/anime";


export const DEATHNOTE: Anime[] = [
  {
    episode: 1,
    season: 1,
    title: 'Renaissance',
    summary: " Light Yagami, un brillant lycéen de 17 ans, découvre un livre : le Death Note. Il appartient en fait à Ryuk, un dieu de la mort qui s'ennuie dans le monde des shinigamis. Il l'a laissé tomber sur Terre. Le Death Note est un cahier qui tue tous ceux dont on écrit le nom à l'intérieur.",
    type: 'Seinen',
    picture: '../assets/deathNote/001.jpeg',
    created: new Date('3 octobre 2006'),
    link1: '//ok.ru/videoembed/943933622829',
    link2: '',
    link3: '',
  },
  {
    episode: 2,
    season: 1,
    title: 'Confrontation',
    summary: "Interpol commence à s'inquiéter du nombre de morts qui surviennent dans le milieu criminel. L'organisation décide donc de faire appel à L, un célèbre mais anonyme détective privé, à la condition posée par ce dernier qu'ils lui donnent une totale collaboration. En quelques heures, il peut déjà affirmer que Kira (pseudonyme donné par les internautes à Light) se trouve dans la région du Kanto, au Japon.",
    type: 'Seinen',
    picture: '../assets/deathNote/002.jpeg',
    created: new Date('10 octobre 2006'),
    link1: '//ok.ru/videoembed/749342689959',
    link2: '',
    link3: '',
  },
  {
    episode: 3,
    season: 1,
    title: 'Pacte',
    summary: "Le père de Light travaille dans la police, ce qui permet à Kira d'obtenir toutes les avancées de l'enquête et ainsi contourner toutes les théories de L. Ryuk avertit alors Light que quelqu'un le surveille, il lui précise également que, s'il le souhaite, il peut obtenir des yeux de Shinigami, ce qui lui permettrait de connaître aussitôt le nom de chaque personne qu'il verra. En échange, son espérance de vie diminuerait de moitié.",
    type: 'Seinen',
    picture: '../assets/deathNote/003.jpeg',
    created: new Date('17 octobre 2006'),
    link1: '//ok.ru/videoembed/749342952103',
    link2: '',
    link3: '',
  },
  {
    episode: 4,
    season: 1,
    title: 'Poursuite',
    summary: "Light refuse l'échange des yeux et fait des expériences sur des criminels au moyen du Death Note. Plus tard, il parvient à provoquer une prise d'otage dans un bus par le biais d'une nouvelle victime, le tout sous les yeux de Ray Penber, un agent du FBI.",
    type: 'Seinen',
    picture: '../assets/deathNote/004.jpeg',
    created: new Date('24 octobre 2006'),
    link1: '//ok.ru/videoembed/749343279783',
    link2: '',
    link3: '',
  },
  {
    episode: 5,
    season: 1,
    title: 'Tactique',
    summary: "Ray Penber est devenu un témoin gênant pour Light. Ce dernier décide alors de l'éliminer en l'obligeant à lui donner les noms des agents du FBI en étant caché par une capuche, mais il lui montre son visage juste avant sa mort.",
    type: 'Seinen',
    picture: '../assets/deathNote/005.jpeg',
    created: new Date('31 octobre 2006'),
    link1: '//ok.ru/videoembed/749343476391',
    link2: '',
    link3: '',
  },
  {
    episode: 6,
    season: 1,
    title: 'Déchirure',
    summary: "L'équipe de police chargée de l'enquête « Kira » découvre enfin le vrai visage du célèbre détective L. De son côté, Light fait la rencontre de la fiancée de Ray Penber ; elle semble en savoir un peu trop sur Kira.",
    type: 'Seinen',
    picture: '../assets/deathNote/006.jpeg',
    created: new Date('7 novembre 2006'),
    link1: '//ok.ru/videoembed/749343804071',
    link2: '',
    link3: '',
  },
  {
    episode: 7,
    season: 1,
    title: 'Temps couvert',
    summary: "La fiancée de Ray Penber est éliminée à son tour après avoir été dupée par Light.",
    type: 'Seinen',
    picture: '../assets/deathNote/007.jpeg',
    created: new Date('14 novembre 2006'),
    link1: '//ok.ru/videoembed/749344131751',
    link2: '',
    link3: '',
  },
  {
    episode: 8,
    season: 1,
    title: 'Regard',
    summary: "L décide de s'intéresser aux personnes surveillées par Ray Penber avant son assassinat. Il fait donc placer des caméras chez les familles Kitamura et Yagami.",
    type: 'Seinen',
    picture: '../assets/deathNote/008.jpeg',
    created: new Date('21 novembre 2006'),
    link1: '//ok.ru/videoembed/749344328359',
    link2: '',
    link3: '',
  },
  {
    episode: 9,
    season: 1,
    title: 'Contact',
    summary: "Light devient étudiant à Todai. Là-bas, il rencontre un certain Hideki Ryuuga qui n'est autre que L. Ce dernier avoue à Light qu'il est L et souhaite qu'il fasse partie de l'enquête « Kira ».",
    type: 'Seinen',
    picture: '../assets/deathNote/009.jpeg',
    created: new Date('28 novembre 2006'),
    link1: '//ok.ru/videoembed/749344656039',
    link2: '',
    link3: '',
  },
  {
    episode: 10,
    season: 1,
    title: 'Doute',
    summary: "Light soupçonne Hideki d'utiliser un pseudonyme pour éviter que Kira puisse le tuer, ce qui le rend fou de rage d'être pris de vitesse. De son côté, L pense qu'il y a 5 % de chances que Light soit Kira et tente de le percer à jour.",
    type: 'Seinen',
    picture: '../assets/deathNote/010.jpeg',
    created: new Date('5 décembre 2006'),
    link1: '//ok.ru/videoembed/749344852647',
    link2: '',
    link3: '',
  },
  {
    episode: 11,
    season: 1,
    title: 'Assaut',
    summary: "Des messages sont envoyés par Kira sur Sakura TV où il annonce la mort en direct de deux présentateurs. Les procédés étant différents de d'habitude, L en déduit qu'il s'agit d'un faux Kira.",
    type: 'Seinen',
    picture: '../assets/deathNote/011.jpeg',
    created: new Date('12 décembre 2006'),
    link1: '//ok.ru/videoembed/749345245863',
    link2: '',
    link3: '',
  },
  {
    episode: 12,
    season: 1,
    title: 'Amour',
    summary: "L demande à Light de se faire passer pour Kira afin d'adresser un message au faux Kira qui est en fait Misa, une célèbre mannequin. Accompagnée de Rem, son shinigami, elle tente d'entrer en contact avec Kira.",
    type: 'Seinen',
    picture: '../assets/deathNote/012.jpeg',
    created: new Date('26 décembre 2006'),
    link1: '//ok.ru/videoembed/749345442471',
    link2: '',
    link3: '',
  },
  {
    episode: 13,
    season: 1,
    title: 'Confession',
    summary: "Grâce à ses yeux de shinigami, Misa identifie Light. Elle décide d'aller à sa rencontre et lui promet de faire tout ce qu'il lui ordonnera en remerciement pour avoir tué l'assassin de ses parents.",
    type: 'Seinen',
    picture: '../assets/deathNote/013.jpeg',
    created: new Date('9 janvier 2007'),
    link1: '//ok.ru/videoembed/749345704615',
    link2: '',
    link3: '',
  },
  {
    episode: 14,
    season: 1,
    title: 'Ami',
    summary: "Light aimerait que Rem tue L pour lui et il se rend compte à quel point le fait d'être vu avec Misa pourrait être dangereux.",
    type: 'Seinen',
    picture: '../assets/deathNote/014.jpeg',
    created: new Date('16 janvier 2007'),
    link1: '//ok.ru/videoembed/749346097831',
    link2: '',
    link3: '',
  },
  {
    episode: 15,
    season: 1,
    title: 'Pari',
    summary: "L est persuadé que Misa est le 2e Kira ; il s'arrange alors pour la faire capturer. Rem qui ne supporte pas de la voir souffrir, lui propose de renoncer à son Death Note afin qu'elle oublie les meurtres qu'elle a commis, et donc qu'elle ne puisse rien avouer.",
    type: 'Seinen',
    picture: '../assets/deathNote/015.jpeg',
    created: new Date('23 janvier 2007'),
    link1: '//ok.ru/videoembed/847016626738',
    link2: '',
    link3: '',
  },
  {
    episode: 16,
    season: 1,
    title: 'Décision',
    summary: "Light décide de dire à L qu'il a peut-être été Kira et il se retrouve ainsi enfermé. Cette manœuvre prouvera si oui ou non Light est effectivement Kira. Cependant, Light renonce à son tour à son Death Note et jure qu'il n'a jamais pu être Kira. De plus, les crimes qui s'étaient arrêtés reprennent de plus belle.",
    type: 'Seinen',
    picture: '../assets/deathNote/016.jpeg',
    created: new Date('30 janvier 2007'),
    link1: '//ok.ru/videoembed/749347277479',
    link2: '',
    link3: '',
  },
  {
    episode: 17,
    season: 1,
    title: 'Exécution',
    summary: "Le père de Light veut absolument faire libérer son fils. L lui demande alors de le tuer. Ayant passé le test, Light et Misa sont autorisés à sortir mais seront surveillés en permanence. D'ailleurs, L va jusqu'à s'attacher avec Light par des menottes car il continue à croire en sa double personnalité.",
    type: 'Seinen',
    picture: '../assets/deathNote/017.jpeg',
    created: new Date('6 février 2007'),
    link1: '//ok.ru/videoembed/749347474087',
    link2: '',
    link3: '',
  },
  {
    episode: 18,
    season: 1,
    title: 'Allié',
    summary: "L'équipe s'installe dans un nouveau quartier général et grâce aux crimes commis par Kira, ils s'intéressent aux activités de la société Yotsuba. L engage Alber, un escroc, et Weddy, une voleuse, pour les aider.",
    type: 'Seinen',
    picture: '../assets/deathNote/018.jpeg',
    created: new Date('13 février 2007'),
    link1: '//ok.ru/videoembed/749347932839',
    link2: '',
    link3: '',
  },
  {
    episode: 19,
    season: 1,
    title: 'Matsuda',
    summary: "Se sentant inutile pour l'enquête, l'inspecteur Matsuda décide d'aller espionner la société Yotsuba tout seul.",
    type: 'Seinen',
    picture: '../assets/deathNote/019.jpeg',
    created: new Date('20 février 2007'),
    link1: '//ok.ru/videoembed/749348129447',
    link2: '',
    link3: '',
  },
  {
    episode: 20,
    season: 1,
    title: 'Expédient',
    summary: "L'équipe réussit à enregistrer une réunion secrète de Yotsuba. L veut attendre avant d'agir, ce que le reste de l'équipe n'approuve pas. Il se sert alors de Misa pour forcer la main à Light.",
    type: 'Seinen',
    picture: '../assets/deathNote/020.jpeg',
    created: new Date('27 février 2007'),
    link1: '//ok.ru/videoembed/749348653735',
    link2: '',
    link3: '',
  },
  {
    episode: 21,
    season: 1,
    title: 'Performance',
    summary: "Misa retrouve la mémoire grâce à Rem qui lui fait toucher une feuille de son Death Note. Elle obtient rapidement un rendez-vous avec Higuchi, qui s'avère être le nouveau Kira.",
    type: 'Seinen',
    picture: '../assets/deathNote/021.jpeg',
    created: new Date('6 mars 2007'),
    link1: '//ok.ru/videoembed/749348850343',
    link2: '',
    link3: '',
  },
  {
    episode: 22,
    season: 1,
    title: 'Conduite',
    summary: "L décide de piéger Higuchi pour le capturer en toute sécurité. Il demande alors à l'inspecteur Matsuda de participer à une émission où le vrai nom de Kira sera finalement révélé.",
    type: 'Seinen',
    picture: '../assets/deathNote/022.jpeg',
    created: new Date('13 mars 2007'),
    link1: '//ok.ru/videoembed/345616681600',
    link2: '',
    link3: '',
  },
  {
    episode: 23,
    season: 1,
    title: 'Frénésie',
    summary: "Higuchi tente par tous les moyens de trouver le véritable nom de Matsuda, sans succès. Aidée de la police, l'équipe de L se lance alors dans une course-poursuite pour neutraliser l'homme.",
    type: 'Seinen',
    picture: '../assets/deathNote/023.jpeg',
    created: new Date('20 mars 2007'),
    link1: '//ok.ru/videoembed/749349505703',
    link2: '',
    link3: '',
  },
  {
    episode: 24,
    season: 1,
    title: 'Résurrection',
    summary: "En arrêtant Higuchi, les enquêteurs manipulent tous le Death Note et Rem apparaît alors. Quand Light touche le Death Note à son tour, tous les souvenirs de Kira lui reviennent et il tue aussitôt Higuchi sous le nez de L. À présent, c'est au tour de ce dernier de mourir et Light demande à Misa de l'aider à nouveau pour avoir son vrai nom. La jeune femme ayant perdu ses yeux de Shinigami demande à Ryuk de passer le pacte une seconde fois, ce qui divise encore son espérance de vie par deux.",
    type: 'Seinen',
    picture: '../assets/deathNote/024.jpeg',
    created: new Date('27 mars 2007'),
    link1: '//ok.ru/videoembed/749349636775',
    link2: '',
    link3: '',
  },
  {
    episode: 25,
    season: 1,
    title: 'Silence',
    summary: "Grâce à une règle écrite dans le Death Note (qui stipule que son utilisateur meurt s'il ne s'en sert pas pendant plus treize jours), Light et Misa sont innocentés. Malgré sa liberté, Light reste auprès de L et, comme les meurtres continuent, le détective continue de soupçonner Misa. Pour la protéger, Rem décide alors de se sacrifier en tuant Watari et L.",
    type: 'Seinen',
    picture: '../assets/deathNote/025.jpeg',
    created: new Date('3 avril 2007'),
    link1: '//ok.ru/videoembed/749349964455',
    link2: '',
    link3: '',
  },
  {
    episode: 26,
    season: 1,
    title: 'Reprise',
    summary: "L est enterré en secret et l'équipe décide de faire de Light son successeur. Kira peut à nouveau tuer librement. Cinq ans se sont écoulés avril 2012 Light a 23 ans et a rejoint les forces de police. Tout lui sourit. Pourtant, de nouveaux obstacles vont bientôt se dresser face à lui.",
    type: 'Seinen',
    picture: '../assets/deathNote/026.jpeg',
    created: new Date('10 avril 2007'),
    link1: '//ok.ru/videoembed/749350095527',
    link2: '',
    link3: '',
  },
  {
    episode: 27,
    season: 1,
    title: 'Enlèvement',
    summary: "Near et Mello, deux garçons qui avaient été choisis par L, décident de retrouver Kira chacun de leur côté. Le 5 mars 2012 Near rencontre le Président. Near est intégré au SPK (Secret Provision for Kira) composé d'agents de la CIA et du FBI. Sayu, la sœur de Light, se fait alors enlever par un groupe qui désire obtenir le Death Note en échange.",
    type: 'Seinen',
    picture: '../assets/deathNote/027.jpeg',
    created: new Date('17 avril 2007'),
    link1: '//ok.ru/videoembed/346169281152',
    link2: '',
    link3: '',
  },
  {
    episode: 28,
    season: 1,
    title: 'Impatience',
    summary: "Near donne les pleins pouvoirs à Light pour organiser la libération de Sayu. Light envoie donc son père pour échanger Sayu contre le Death Note. Mais l'opération échoue ; Sayu est sauvée mais le Death Note est volé par une organisation dirigée par Mello. Mello tue alors la plupart des membres du SPK.",
    type: 'Seinen',
    picture: '../assets/deathNote/028.jpeg',
    created: new Date('24 avril 2007'),
    link1: '//ok.ru/videoembed/749350685351',
    link2: '',
    link3: '',
  },
  {
    episode: 29,
    season: 1,
    title: 'Père',
    summary: "Le père de Light conclut le pacte avec Ryūk. Grâce à ses yeux de Shinigami, il parvient à découvrir le vrai nom de Mello, mais il meurt sans avoir écrit le nom sur le Death Note en ayant communiqué le nom de Mello à son fils.",
    type: 'Seinen',
    picture: '../assets/deathNote/029.jpeg',
    created: new Date('1er mai 2007'),
    link1: '//ok.ru/videoembed/749351013031',
    link2: '',
    link3: '',
  },
  {
    episode: 30,
    season: 1,
    title: 'Justice',
    summary: "Mello vient à la rencontre de Near. Near suspecte Light d'être Kira et la règle des treize jours d'être fausse. Demegawa, un présentateur télé, se proclame porte-parole de Kira et organise une émeute contre le quartier général de Near.",
    type: 'Seinen',
    picture: '../assets/deathNote/030.jpeg',
    created: new Date('8 mai 2007'),
    link1: '//ok.ru/videoembed/749351275175',
    link2: '',
    link3: '',
  },
  {
    episode: 31,
    season: 1,
    title: 'Transfert',
    summary: "Aizawa suspecte Light et Misa et décide de fouiller leurs chambres. Misa renonce à son Death Note. Un nouveau Kira apparaît ; sa manière de penser est identique à celle de Light. Il tue Demegawa, comme Light l'espérait.",
    type: 'Seinen',
    picture: '../assets/deathNote/031.jpeg',
    created: new Date('15 mai 2007'),
    link1: '//ok.ru/videoembed/749351406247',
    link2: '',
    link3: '',
  },
  {
    episode: 32,
    season: 1,
    title: 'Choix',
    summary: "Mikami Teru prend la relève. Il choisit un nouveau porte-parole : Takada Kiyomi, une ex-amie d'université de Light.",
    type: 'Seinen',
    picture: '../assets/deathNote/032.jpeg',
    created: new Date('22 mai 2007'),
    link1: '//ok.ru/videoembed/749351602855',
    link2: '',
    link3: '',
  },
  {
    episode: 33,
    season: 1,
    title: 'Arrogance',
    summary: "Near arrive au Japon et son équipe commence à enquêter sur Mikami.",
    type: 'Seinen',
    picture: '../assets/deathNote/033.jpeg',
    created: new Date('29 mai 2007'),
    link1: '//ok.ru/videoembed/749351668391',
    link2: '',
    link3: '',
  },
  {
    episode: 34,
    season: 1,
    title: 'Vigilance',
    summary: "Mikami est suspecté par Near d'être le second Kira. Aizawa, ayant toujours des doutes sur Light, inspecte la chambre d'hôtel après une rencontre entre Light et Kiyomi et découvre que ceux-ci communiquent par écrit. Aizawa décide alors d'aller rencontrer Near qui lui dévoile une partie de son plan. Par la suite, Near et le SPK enlèvent Mogi et Misa dans le but de piéger Mikami et Light.",
    type: 'Seinen',
    picture: '../assets/deathNote/034.jpeg',
    created: new Date('5 juin 2007'),
    link1: '//ok.ru/videoembed/749351864999',
    link2: '',
    link3: '',
  },
  {
    episode: 35,
    season: 1,
    title: 'Tentative de meurtre',
    summary: "Near veut rencontrer Light. Mello enlève Kiyomi avec l'aide de Matt, un de ses amis d'enfance, abattu plus tard par un garde du corps un peu trop entreprenant de Kiyomi. Celle-ci utilise un morceau du Death Note pour tuer Mello. Takada est tuée plus tard par Light, ou du moins c'est ce qu'il croit.",
    type: 'Seinen',
    picture: '../assets/deathNote/035.jpeg',
    created: new Date('12 juin 2007'),
    link1: '//ok.ru/videoembed/345619696256',
    link2: '',
    link3: '',
  },
  {
    episode: 36,
    season: 1,
    title: '28 janvier',
    summary: "Light et Near se rencontrent enfin. Light savoure déjà sa victoire, qu'il annonce à Near à la fin de l'épisode.",
    type: 'Seinen',
    picture: '../assets/deathNote/036.jpeg',
    created: new Date('19 juin 2007'),
    link1: '//ok.ru/videoembed/749352651431',
    link2: '',
    link3: '',
  },
  {
    episode: 37,
    season: 1,
    title: 'Le nouveau monde',
    summary: "Grâce à un indice laissé par Mello, et à cause d'une erreur commise par Mikami, Near réussit à piéger Light. Ce dernier, pris de panique, tente désespérément de se servir d'une feuille du Death Note cachée dans sa montre, mais est touché par les balles provenant du pistolet de Matsuda. Mikami se suicide et Light s'enfuit et finira par mourir. Dans le manga, Ryuk inscrit alors « Yagami Light » dans son propre Death Note. C'est ainsi que meurent Kira et X-Kira.",
    type: 'Seinen',
    picture: '../assets/deathNote/037.jpeg',
    created: new Date('26 juin 2007'),
    link1: '//ok.ru/videoembed/749353044647',
    link2: '',
    link3: '',
  },
]
