import { Anime } from "../modeles/anime";


export const DEMONSLAYER : Anime[] = [
  {
    episode: 1,
    season: 1,
    title: "Cruauté",
    summary: "Résumé indisponible.",
    type: 'Shonen',
    picture: '../assets/demonSlayer/001.jpeg',
    created: new Date('6 avril 2019'),
    link1: '//myvi.ru/player/embed/html/ok8CT8iu3_cmICOVL79JzZsxkSPQS0cn3FJxZS5mHuNVkXEmU7I87byAMRsgQkau20',
    link2: '',
    link3: '',
  },
  {
    episode: 2,
    season: 1,
    title: "Urokodaki Sakonji, le formateur",
    summary: "Résumé indisponible.",
    type: 'Shonen',
    picture: '../assets/demonSlayer/002.jpeg',
    created: new Date('13 avril 2019'),
    link1: "//myvi.ru/player/embed/html/oH3QAfJAdilg99ZUR9n3acZv1A_yDApjdAKejHoja_Cr4mXtK7aZcm3NP25Zre17L0",
    link2: '',
    link3: '',
  },
  {
    episode: 3,
    season: 1,
    title: "Sabito et Makomo",
    summary: "Résumé indisponible.",
    type: 'Shonen',
    picture: '../assets/demonSlayer/003.jpeg',
    created: new Date('20 avril 2019'),
    link1: 'https://video.sibnet.ru/shell.php?videoid=3596494&share=1',
    link2: '',
    link3: '',
  },
  {
    episode: 4,
    season: 1,
    title: "La Sélection finale",
    summary: "Résumé indisponible.",
    type: 'Shonen',
    picture: '../assets/demonSlayer/004.jpeg',
    created: new Date('27 avril 2019'),
    link1: 'https://video.sibnet.ru/shell.php?videoid=3601339&share=1',
    link2: '',
    link3: '',
  },
  {
    episode: 5,
    season: 1,
    title: "Chacun son acier",
    summary: "Résumé indisponible.",
    type: 'Shonen',
    picture: '../assets/demonSlayer/005.jpeg',
    created: new Date('4 mai 2019'),
    link1: 'https://video.sibnet.ru/shell.php?videoid=3606313&share=1',
    link2: '',
    link3: '',
  },
  {
    episode: 6,
    season: 1,
    title: "Le chasseur accompagné d'un démon",
    summary: "Résumé indisponible.",
    type: 'Shonen',
    picture: '../assets/demonSlayer/006.jpeg',
    created: new Date('11 mai 2019'),
    link1: 'https://uqload.org/embed-q17zdxotls2c.html',
    link2: '',
    link3: '',
  },
  {
    episode: 7,
    season: 1,
    title: "Kibutsuji Muzan",
    summary: "Résumé indisponible.",
    type: 'Shonen',
    picture: '../assets/demonSlayer/007.jpeg',
    created: new Date('18 mai 2019'),
    link1: 'https://video.sibnet.ru/shell.php?videoid=3614777&share=1',
    link2: '',
    link3: '',
  },
  {
    episode: 8,
    season: 1,
    title: "Le Parfum du sang d'envoûtement",
    summary: "Résumé indisponible.",
    type: 'Shonen',
    picture: '../assets/demonSlayer/008.jpeg',
    created: new Date('25 mai 2019'),
    link1: 'https://video.sibnet.ru/shell.php?videoid=3618828&share=1',
    link2: '',
    link3: '',
  },
  {
    episode: 9,
    season: 1,
    title: "Les Démons aux ballons et aux flèches",
    summary: "Résumé indisponible.",
    type: 'Shonen',
    picture: '../assets/demonSlayer/009.jpeg',
    created: new Date('1er juin 2019'),
    link1: 'https://uqload.org/embed-a7cy1p596br9.html',
    link2: '',
    link3: '',
  },
  {
    episode: 10,
    season: 1,
    title: "Nous resterons ensemble",
    summary: "Résumé indisponible.",
    type: 'Shonen',
    picture: '../assets/demonSlayer/010.jpeg',
    created: new Date('8 juin 2019'),
    link1: 'https://uqload.org/embed-lannu367jj3z.html',
    link2: '',
    link3: '',
  },
  {
    episode: 11,
    season: 1,
    title: "La Maison aux tambours",
    summary: "Résumé indisponible.",
    type: 'Shonen',
    picture: '../assets/demonSlayer/011.jpeg',
    created: new Date('15 juin 2019'),
    link1: 'https://uqload.org/embed-43jl4oukslz0.html',
    link2: '',
    link3: '',
  },
  {
    episode: 12,
    season: 1,
    title: "Zen'itsu dort, le sanglier montre les crocs",
    summary: "Résumé indisponible.",
    type: 'Shonen',
    picture: '../assets/demonSlayer/012.jpeg',
    created: new Date('22 juin 2019'),
    link1: 'https://uqload.org/embed-5dax8sbwf4me.html',
    link2: '',
    link3: '',
  },
  {
    episode: 13,
    season: 1,
    title: "Ce à quoi je tiens plus qu'à ma vie",
    summary: "Résumé indisponible.",
    type: 'Shonen',
    picture: '../assets/demonSlayer/013.jpeg',
    created: new Date('29 juin 2019'),
    link1: 'https://uqload.org/embed-dsiwkn4lygcw.html',
    link2: '',
    link3: '',
  },
  {
    episode: 14,
    season: 1,
    title: "Le Blason des glycines",
    summary: "Résumé indisponible.",
    type: 'Shonen',
    picture: '../assets/demonSlayer/014.jpeg',
    created: new Date('6 juillet 2019'),
    link1: 'https://uqload.org/embed-kzbmfwfwfst6.html',
    link2: '',
    link3: '',
  },
  {
    episode: 15,
    season: 1,
    title: "Le Mont Natagumo",
    summary: "Résumé indisponible.",
    type: 'Shonen',
    picture: '../assets/demonSlayer/015.jpeg',
    created: new Date('13 juillet 2019'),
    link1: 'https://uqload.org/embed-hd2zwi9dmz7w.html',
    link2: '',
    link3: '',
  },
  {
    episode: 16,
    season: 1,
    title: "Faire passer les autres avant soi",
    summary: "Résumé indisponible.",
    type: 'Shonen',
    picture: '../assets/demonSlayer/016.jpeg',
    created: new Date('20 juillet 2019'),
    link1: 'https://uqload.org/embed-n5snvxnwww8c.html',
    link2: '',
    link3: '',
  },
  {
    episode: 17,
    season: 1,
    title: "Parfaire une seule technique",
    summary: "Résumé indisponible.",
    type: 'Shonen',
    picture: '../assets/demonSlayer/017.jpeg',
    created: new Date('27 juillet 2019'),
    link1: 'https://uqload.org/embed-15xiknldpfji.html',
    link2: '',
    link3: '',
  },
  {
    episode: 18,
    season: 1,
    title: "Des liens factices",
    summary: "Résumé indisponible.",
    type: 'Shonen',
    picture: '../assets/demonSlayer/018.jpeg',
    created: new Date('3 août 2019'),
    link1: 'https://uqload.org/embed-f01bvyzv7c89.html',
    link2: '',
    link3: '',
  },
  {
    episode: 19,
    season: 1,
    title: "Le Dieu du feu",
    summary: "Résumé indisponible.",
    type: 'Shonen',
    picture: '../assets/demonSlayer/019.jpeg',
    created: new Date('10 août 2019'),
    link1: 'https://uqload.org/embed-k48hwswt8lit.html',
    link2: '',
    link3: '',
  },
  {
    episode: 20,
    season: 1,
    title: "Une famille improvisée",
    summary: "Résumé indisponible.",
    type: 'Shonen',
    picture: '../assets/demonSlayer/020.jpeg',
    created: new Date('17 août 2019'),
    link1: 'https://uqload.org/embed-hvzthfkc7r1m.html',
    link2: '',
    link3: '',
  },
  {
    episode: 21,
    season: 1,
    title: "Violation du code",
    summary: "Résumé indisponible.",
    type: 'Shonen',
    picture: '../assets/demonSlayer/021.jpeg',
    created: new Date('24 août 2019'),
    link1: 'https://uqload.org/embed-y44nst4el55e.html',
    link2: '',
    link3: '',
  },
  {
    episode: 22,
    season: 1,
    title: "Le Maître",
    summary: "Résumé indisponible.",
    type: 'Shonen',
    picture: '../assets/demonSlayer/022.jpeg',
    created: new Date('31 août 2019'),
    link1: 'https://uqload.org/embed-opemydh90y15.html',
    link2: '',
    link3: '',
  },
  {
    episode: 23,
    season: 1,
    title: "La Réunion des piliers",
    summary: "Résumé indisponible.",
    type: 'Shonen',
    picture: '../assets/demonSlayer/023.jpeg',
    created: new Date('7 septembre 2019'),
    link1: 'https://uqload.org/embed-umz0c1k3g76e.html',
    link2: '',
    link3: '',
  },
  {
    episode: 24,
    season: 1,
    title: "L'Entraînement récupérateur",
    summary: "Résumé indisponible.",
    type: 'Shonen',
    picture: '../assets/demonSlayer/024.jpeg',
    created: new Date('14 septembre 2019'),
    link1: 'https://uqload.org/embed-a6tcounp73sq.html',
    link2: '',
    link3: '',
  },
  {
    episode: 25,
    season: 1,
    title: "Tsuyuri Kanao, la successeuse",
    summary: "Résumé indisponible.",
    type: 'Shonen',
    picture: '../assets/demonSlayer/025.jpeg',
    created: new Date('21 septembre 2019'),
    link1: 'https://uqload.org/embed-t9eflo5ouzr3.html',
    link2: '',
    link3: '',
  },
  {
    episode: 26,
    season: 1,
    title: "Nouvelle mission",
    summary: "Résumé indisponible.",
    type: 'Shonen',
    picture: '../assets/demonSlayer/026.jpeg',
    created: new Date('28 septembre 2019'),
    link1: 'https://uqload.org/embed-plcwrxpuss4l.html',
    link2: '',
    link3: '',
  },
]
