import { Anime } from "../modeles/anime";


export const FMA: Anime[] = [
  {
    episode: 1,
    season: 1,
    title: "L'Alchimiste Fullmetal",
    summary: "Le colonel Roy Mustang est chargé de retrouver Isaac, un ancien alchimiste d'état qui a déserté et qui veut s'emparer de Central. Roy Mustang est épaulé par deux autres alchimistes d'état comme lui, Alphonse et Edward Elric. Les deux frères se lancent à la poursuite de Isaac qui semble bien déterminé à détruire le centre de commandement. La chose ne sera pas aisée car cet alchimiste surnommé 'l'alchimiste de glace', qui manie les pouvoirs cachés de l'eau avec aisance, semble posséder une pierre philosophale qui décuple ses forces. Le criminel sera finalement tué par le Führer King Bradley.",
    type: 'Shonen',
    picture: '../assets/fma/001.jpeg',
    created: new Date('4 avril 2009'),
    link1: 'https://uqload.org/embed-4vadbxlhmkpe.html',
    link2: '',
    link3: '',
  },
  {
    episode: 2,
    season: 1,
    title: "Le Premier Jour",
    summary: "Alors que le train qu'ils ont pris les emmène à Liore, les frères Elric se remémorent les évènements qui les ont amenés à rejoindre l'armée. C'est 4 ans plus tôt que tout avait commencé. Afin de faire revenir leur mère, emporté par la maladie, les deux frères bravèrent un interdit de l'alchimie en réalisant une transmutation humaine. L'expérience tourne mal et entraîne de graves séquelles chez les deux frères. S'étant déplacé pour rencontrer un alchimiste dont on disait qu'il était doué, le colonel Mustang ne peut que constater avec effroi le résultat de cette expérience ratée. Bien que Edward soit anéanti par cet échec, le colonel remarque le potentiel de ce gamin et lui propose de rejoindre l'armée.",
    type: 'Shonen',
    picture: '../assets/fma/002.jpeg',
    created: new Date('11 avril 2009'),
    link1: 'https://uqload.org/embed-5zeccauepn1r.html',
    link2: '',
    link3: '',
  },
  {
    episode: 3,
    season: 1,
    title: "La Ville hérétique",
    summary: "Arrivés à Liore, les frères Elric se rendent dans l'église pour un entretient avec le père Cornello, dont les pouvoirs semblent provenir non pas de miracles mais d'une pierre philosophale. Ils y rencontrent une jeune fille du nom de Rose qui voit en le père Cornello, le porte-parole du dieu Leto et la personne qui permettra la résurrection de son petit ami mort il y a un an. La confrontation entre les frères et l'homme se faisant passer pour un messager de Dieu tourne court lorsque Al et Ed affichent au grand jour les plans de l'imposteur qui veut contrôler la population de Liore. C'est avec tristesse que Rose doit faire un trait sur son rêve.",
    type: 'Shonen',
    picture: '../assets/fma/003.jpeg',
    created: new Date('18 avril 2009'),
    link1: 'https://uqload.org/embed-xcxb1on8a53x.html',
    link2: '',
    link3: '',
  },
  {
    episode: 4,
    season: 1,
    title: "L'Angoisse de l'Alchimiste",
    summary: "Pour les remercier d'avoir réglé l'affaire de Liore seul, le colonel Mustang présente aux frère Elric un alchimiste du nom de Shou Tucker. Cet homme, qui vit seul avec sa fille Nina depuis le départ de sa femme, est reconnu comme le spécialiste de la transmutation animale. Ed et Al pensent pouvoir accroître leurs connaissances au contact de cet alchimiste. Bien qu'admiratif devant les pouvoirs de leur ôte, les deux frères découvrent avec effroi que sous le masque d'un bon père de famille se cache un homme prêt à tout pour réussir, quitte à sacrifier sa femme et sa fille.",
    type: 'Shonen',
    picture: '../assets/fma/004.jpeg',
    created: new Date('25 avril 2009'),
    link1: 'https://uqload.org/embed-99kvxw5qczqd.html',
    link2: '',
    link3: '',
  },
  {
    episode: 5,
    season: 1,
    title: "Pluie de chagrin",
    summary: "Edward, attristé par la mort de Nina, ne sait plus où il en est et doute quant à sa progression dans la maîtrise de l'alchimie. Complètement déboussolé, il est attaqué par un homme surnommé Scar. Cet homme est responsable de la mort de plusieurs alchimistes d'états et compte bien continuer avec Edward. Alphonse intervient mais les deux frères se retrouvent dans un bien piteux état. Ils ne devront leur salut qu'à l'arrivée de l'armée et particulièrement au major Alex Louis Armstrong qui les sauve des attaques de Scar qui s'avère être un Ishval aux pouvoirs impressionnants. Bien qu'entouré de nombreux soldats, Scar réussi à s'enfuir.",
    type: 'Shonen',
    picture: '../assets/fma/005.jpeg',
    created: new Date('2 mai 2009'),
    link1: 'https://uqload.org/embed-iu8jsx6394mj.html',
    link2: '',
    link3: '',
  },
  {
    episode: 6,
    season: 1,
    title: "Un foyer et Une famille",
    summary: "Afin de réparer leurs membres défectueux, Ed et Al prennent le train à destination de Resembool. Ils sont accompagnés par le major Armstrong qui leur sert temporairement de garde du corps. Ce dernier reconnaîtra le docteur Marcoh sur le quai d'une garde où ils s'arrêtent. C'est en lui rendant visite que notre équipe apprend que le docteur a réussi à créer une pierre philosophale incomplète. D'abord réticent, le docteur Marcoh donnera les indications nécessaires pour continuer ces recherches afin de créer une pierre philosophale parfaite. Nos trois voyageurs reprennent leur route vers Resembool où Al et Ed retrouveront leurs forces.",
    type: 'Shonen',
    picture: '../assets/fma/006.jpeg',
    created: new Date('9 mai 2009'),
    link1: 'https://uqload.org/embed-5i2lrsufch7o.html',
    link2: '',
    link3: '',
  },
  {
    episode: 7,
    season: 1,
    title: "La Vérité cachée",
    summary: "De retour de Resembool, les frères Elric se rendent à la première section de la bibliothèque nationale pour retrouver les écrits du docteur Marcoh. Ils découvrent malheureusement que tout a brûlé. Les deux frères sont confiés au lieutenant Maria Ross et au sergent Denny Brosh qui sont chargés de les escorter. Al et Ed semblent être dans une impasse mais le lieutenant Ross leur présente Sheska, une jeune femme qui a travaillé à la première section. Grâce à son incroyable mémoire, elle va retranscrire les écrits du docteur Marcoh et permettre aux deux frères de découvrir la vérité cachée derrière la création de la pierre philosophale.",
    type: 'Shonen',
    picture: '../assets/fma/007.jpeg',
    created: new Date('16 mai 2009'),
    link1: 'https://uqload.org/embed-or4q3szpjtxg.html',
    link2: '',
    link3: '',
  },
  {
    episode: 8,
    season: 1,
    title: "Le Cinquième Laboratoire",
    summary: "Al et Ed échappent à leur escorte et se dirigent vers le laboratoire n°5. Pendant que Al guette les alentours, Ed pénètre à l'intérieur du laboratoire afin d'y découvrir des indices sur les expérimentations sur ces prisonniers qui auraient permis la création d'une pierre philosophale. Chacun de leur côté, les deux frères sont attaqués par d'anciens prisonniers morts mais dont les âmes ont été scellées à des armures. Ed mène un combat bien difficile mais réussit à vaincre son adversaire qui accepte de lui révéler les secrets du laboratoire. Ces révélations seront écourtées par l'apparition de deux étrangers qui tuent le prisonnier et font exploser le bâtiment.",
    type: 'Shonen',
    picture: '../assets/fma/008.jpeg',
    created: new Date('23 mai 2009'),
    link1: 'https://uqload.org/embed-qbq7bldvg0qk.html',
    link2: '',
    link3: '',
  },
  {
    episode: 9,
    season: 1,
    title: "Sentiments composés",
    summary: "Après avoir échappé de justesse à l'explosion du laboratoire n°5, Ed se retrouve hospitalisé. Il fait appel à Winry pour qu'elle vienne à Central afin de réparer son auto mail. De son côté, Al est tourmenté par les propos tenus par Number 66 pendant le combat. Celui-ci a réussi à semer le doute dans l'esprit de Al qui se demande s'il a été réellement humain ou s'il n'est qu'un pantin créé de toute pièce par Ed. Ne pouvant plus contenir cette inquiétude pour lui, il ne peut s'empêcher d'interroger violemment son frère. Après quelques minutes de doute, les deux frères s'expliquent et les liens fraternels se resserrent.",
    type: 'Shonen',
    picture: '../assets/fma/009.jpeg',
    created: new Date('30 mai 2009'),
    link1: 'https://uqload.org/embed-v86b25nk8eto.html',
    link2: '',
    link3: '',
  },
  {
    episode: 10,
    season: 1,
    title: "Chacun sa route",
    summary: "À peine remis de ses blessures, Edward décide de reprendre la route avec Alphonse à destination de Dublith où vit leur maître. Le train qu'ils prennent passant par Rush valley, Winry se joint à eux afin de visiter cette ville réputée pour ses auto mails. De son côté, le lieutenant colonel Maes Hughes poursuit son enquête dans l'espoir de trouver l'élément qui relie les évènements de ces derniers jours. Bien qu'il soit resté très discret pendant ses recherches, il est attaqué par une femme qui semble prête à le tuer pour l'empêcher de transmettre les informations qu'il a récoltées. Bien qu'aillant échappé à son agresseur, il ne pourra survivre au complice de la jeune femme.",
    type: 'Shonen',
    picture: '../assets/fma/010.jpeg',
    created: new Date('6 juin 2009'),
    link1: 'https://uqload.org/embed-hlcmv6vx1iqs.html',
    link2: '',
    link3: '',
  },
  {
    episode: 11,
    season: 1,
    title: "Miracle à Rush Valley",
    summary: "Notre trio est arrivé à Rush valley où Winry est en totale admiration devant les différents modèles d'auto mails. Pendant leur visite, Ed se fait voler sa montre d'alchimiste par une jeune femme du nom de Paninya. Nos trois amis se lancent à sa poursuite et finissent par la stopper. Suite à cela, ils rencontrent monsieur Dominic, un fabricant d'auto mails de talent et dont Winry veut devenir l'élève. Bien qu'il refuse catégoriquement, il accepte de présenter Winry à une personne compétente dans la fabrication d'auto mails. Winry décide de rester à Rush valley pour perfectionner ses connaissances de mécanicienne, tandis que les garçons reprennent le chemin vers Dublith.",
    type: 'Shonen',
    picture: '../assets/fma/011.jpeg',
    created: new Date('13 juin 2009'),
    link1: 'https://uqload.org/embed-iyug6f4tqk63.html',
    link2: '',
    link3: '',
  },
  {
    episode: 12,
    season: 1,
    title: "Un est tout, tout n'est qu'un",
    summary: "Enfin arrivés à Dublith, Al et Ed se rendent à la maison de leur maître, Izumi Curtis, qu'ils n'ont pas vu depuis longtemps. Bien que leur maître n'ait que peu d'informations sur la pierre philosophale, elle leur évoque cependant le nom d'une personne qu'elle a rencontrée à Central et qui semble en savoir beaucoup : Hohenheim. La surprise est d'autant plus grande qu'il s'agit du père de Al et Ed qu'ils croyaient mort et qu'ils considèrent comme la raison de la mort de leur mère. Izumi découvrira bien vite l'état réel des deux frères et leur tentative ratée. Elle ne les blâme cependant pas car elle aussi a pu apercevoir la vérité.",
    type: 'Shonen',
    picture: '../assets/fma/012.jpeg',
    created: new Date('20 juin 2009'),
    link1: 'https://uqload.org/embed-ru6i5s68iyb6.html',
    link2: '',
    link3: '',
  },
  {
    episode: 13,
    season: 1,
    title: "Les Bêtes de Dublith",
    summary: "Bien qu'elle ne puisse reprocher à Al d'avoir vu la vérité, puisqu'elle a elle-même bravé les interdits, Izumi décide de ne plus considérer Ed et Al comme ses élèves qui décident de rentrer chez eux. C'est seulement à la gare que les deux frères comprennent que leur maître ne les rejette pas mais les considère désormais d'égal à égal. De retour chez Izumi, les deux frères réaffirment leur volonté de retrouver leurs corps. Agissant dans l'ombre, une bande dirigée par un certain Greed réussit à capturer Al pour lui faire avouer le secret qui permet de sceller une âme à un objet. Ed les retrouve mais le combat face à Greed, qui s'avère être un Homunculus, n'est pas des plus faciles.",
    type: 'Shonen',
    picture: '../assets/fma/013.jpeg',
    created: new Date('27 juin 2009'),
    link1: 'https://uqload.org/embed-rxfbcrc91lam.html',
    link2: '',
    link3: '',
  },
  {
    episode: 14,
    season: 1,
    title: "Ce qui se tapit au sous-sol",
    summary: "Le colonel Mustang arrive enfin à Central pour prendre ses nouvelles fonctions, ce qui ne semble pas être du goût de tout le monde. De leur côté, Ed, Al et Izumi sont toujours confrontés à Greed et sa bande. Ils devront leur salut à l'intervention de l'armée et notamment grâce au Führer Bradley. La présence de ce dernier est d'ailleurs étonnante pour l'arrestation de quelques rebelles. Cependant, il ne tardera pas à dévoiler sa véritable identitée à Greed lors du combat qui les oppose. Après avoir exterminé la bande de Greed, l'armée se retire mais tout ne semble pas terminé en sous-sol. Le Führer Bradley rejoint un groupe d'Homunculus dirigé par un homme que tous appellent 'Père'.",
    type: 'Shonen',
    picture: '../assets/fma/014.jpeg',
    created: new Date('4 juillet 2009'),
    link1: 'https://uqload.org/embed-xgytr40vmyco.html',
    link2: '',
    link3: '',
  },
  {
    episode: 15,
    season: 1,
    title: "Le Messager de l'Est",
    summary: "Une jeune fille du nom de May Chang, qui prétend venir du territoire de Xing, soigne Scar de ses blessures grâce à une technique appelée 'élixirologie'. Tout d'abord contre l'idée d'emmener la jeune fille à Central, il finira par accepter. Les deux frères retournent à Rush valley pour y voir Winry et faire réparer l'auto mail de Ed. Il feront la connaissance de Ling Yao, l'un des nombreux héritiers de l'empereur de Xing. Son intérêt pour la pierre philosophale inquiète les frères Elric. Lorsque Ed et Al annoncent qu'ils ont décidé de retourner à Central, Winry décide de se joindre à eux pour remercier le lieutenant colonel Hughes.",
    type: 'Shonen',
    picture: '../assets/fma/015.jpeg',
    created: new Date('11 juillet 2009'),
    link1: 'https://uqload.org/embed-rnqmjjx4jw0r.html',
    link2: '',
    link3: '',
  },
  {
    episode: 16,
    season: 1,
    title: "Les Traces d'un compagnon d'armes",
    summary: "Ed, Al et Winry sont de retour à Central et décident de laisser le prince et ses gardes du corps prendre leur propre chemin. Les garçons prennent la direction du Q.G. pour informer le lieutenant colonel Hughes de leur découverte sur les Homunculus, tandis que Winry se dirige vers la maison des Hughes où elle est impatiente de retrouver Gracia et sa fille. Les retrouvailles sont des plus douloureuses lorsque que tous apprennent la mort du lieutenant colonel Hughes. Bien qu'attristée par la mort de son mari, Gracia ne peut qu'encourager les frères Elric à continuer leur enquête et découvrir ce qui se cache derrière la pierre philosophale.",
    type: 'Shonen',
    picture: '../assets/fma/016.jpeg',
    created: new Date('18 juillet 2009'),
    link1: 'https://uqload.org/embed-oslrzxdqa02m.html',
    link2: '',
    link3: '',
  },
  {
    episode: 17,
    season: 1,
    title: "La Flamme froide",
    summary: "Afin de ralentir les recherches du colonel Mustang qui les mènent de plus en plus sur leur piste, les Homunculus s'arrangent pour faire accuser le sous-lieutenant Ross du meurtre du général Hughes. Cette dernière est arrêtée et mise en prison. Elle réussira à s'échapper grâce à une personne inattendue : Barry le boucher. Lors de son évasion, elle est rattrapée par le colonel Mustang qui met fin à ses jours par immolation. Suite à cette exécution, Ed est furieux contre le colonel mustang et l'estime des hommes du colonel envers leur supérieur est au plus bas. Cette déchéance de ce héros de la guerre d'Ishval semble pourtant cacher de mystérieux évènements.",
    type: 'Shonen',
    picture: '../assets/fma/017.jpeg',
    created: new Date('25 juillet 2009'),
    link1: 'https://uqload.org/embed-v0726jv3owft.html',
    link2: '',
    link3: '',
  },
  {
    episode: 18,
    season: 1,
    title: "L'Arrogance au creux de sa jeune main",
    summary: "Ed est de retour à Resembool où le commandant Armstrong l'a traîné de force. Bien qu'il ne comprenne pas trop, Ed accepte de suivre le commandant pour un voyage en direction de Xerxès où il pourra constater que le sous-lieutenant Ross est toujours en vie. Le sous-lieutenant Breda explique donc la mise en scène de la mort du sous-lieutenant Ross et la façon dont le colonel Mustang a organisé son équipe pour démasquer l'espion qui se cache au sein même de l'armée. À Central, les choses bougent puisque Barry, sous la protection de l'équipe du colonel Mustang, est attaqué par son propre corps auquel a été attaché une âme de cobaye.",
    type: 'Shonen',
    picture: '../assets/fma/018.jpeg',
    created: new Date('1er août 2009'),
    link1: 'https://uqload.org/embed-dp5wtgezbwej.html',
    link2: '',
    link3: '',
  },
  {
    episode: 19,
    season: 1,
    title: "La mort de ce qui ne peut pas mourir",
    summary: "Après avoir échappé à une attaque de Gluttony, le colonel Mustang et son équipe poursuivent le corps de Barry. Celui-ci les mène jusqu'au laboratoire n°3, où Barry décide de suivre son corps. Bien que peu discrète, cette entrée donne une excuse au colonel pour s'introduire dans le laboratoire où il ne tarde pas à tomber nez à nez avec Lust. Cette dernière n'hésite pas à lui montrer sa pierre philosophale qui est en fait son propre noyau. Le pouvoir de régénération de Lust est tel que le colonel devra mettre le maximum de son énergie dans ses attaques pour battre son adversaire.",
    type: 'Shonen',
    picture: '../assets/fma/019.jpeg',
    created: new Date('8 août 2009'),
    link1: 'https://uqload.org/embed-3l6ao5a4eovn.html',
    link2: '',
    link3: '',
  },
  {
    episode: 20,
    season: 1,
    title: "Le Père devant la tombe",
    summary: "Alors qu'il est encore à Resembool, Ed aperçoit Hohenheim se recueillant sur la tombe de sa mère. Les retrouvailles entre père et fils sont plutôt glaciales. Durant son court séjour, Hohenheim avertit Pinako qu'une chose horrible se prépare et qu'il serait préférable qu'elle parte se réfugier dans un autre pays. De son côté, Ed découvre que ce que lui et son frère ont transmuté ne peut pas être leur mère. Il acquière la certitude que les morts ne peuvent être ramenés à la vie et qu'il pourra récupérer le corps de son frère de l'autre côté de la porte. C'est avec cette nouvelle que Ed retourne à Central.",
    type: 'Shonen',
    picture: '../assets/fma/020.jpeg',
    created: new Date('16 août 2009'),
    link1: 'https://uqload.org/embed-d3kgrafhpduz.html',
    link2: '',
    link3: '',
  },
  {
    episode: 21,
    season: 1,
    title: "L'Avancée de l'imbécile",
    summary: "Le colonel Mustang continue ses recherches sur les Homunculus mais doit se résigner à abandonner temporairement le sous-lieutenant Havoc dont la moelle épinière a été touchée lors du dernier combat. De leur côté, les frères Elric décident de servir d'appât à Scar qui est revenu semer la mort en ville. En servant d'appât, Al et Ed espèrent attirer les Homunculus pour qui ils représentent un élément important dans leur futur plan. Les deux frères semblent en effet être des éléments de premier choix pour un sacrifice dont ils ne connaissent pas la raison.",
    type: 'Shonen',
    picture: '../assets/fma/021.jpeg',
    created: new Date('31 août 2009'),
    link1: 'https://vudeo.net/embed-titq6s5lpj2g.html',
    link2: '',
    link3: '',
  },
  {
    episode: 22,
    season: 1,
    title: "La silhouette que l'on voit au loin",
    summary: "Alors que le combat est engagé entre Scar et les frères Elric, Winry se dirige vers la scène de l'action après avoir entendu certains villageois parler de l'affrontement. Une fois sur place, elle apprend involontairement de la bouche de Ed que Scar est l'assassin de ses parents. Ce face-à-face avec la jeune fille remémore à Scar ce terrible jour où l'armée est venue anéantir le peuple d'Ishval et le sacrifice de son frère. Bien que conscient d'avoir tué deux médecins innocents, Scar ne renonce pas à son objectif d'exterminer les alchimistes d'état afin de venger l'honneur du peuple d'Ishval.",
    type: 'Shonen',
    picture: '../assets/fma/022.jpeg',
    created: new Date('6 septembre 2009'),
    link1: 'https://vudeo.net/embed-kzh84ds289hh.html',
    link2: '',
    link3: '',
  },
  {
    episode: 23,
    season: 1,
    title: "Une Jeune Fille sur le champ de bataille",
    summary: "Alors que le combat entre Scar et les deux frères bat de plus belle, Gluttony fait son apparition. Al et Ed ne devront leur salut qu'à l'apparition de Ling qui réussit à faire exploser Gluttony. Scar est maîtrisé mais les frères ne peuvent le capturer car May fait diversion, assurant la fuite de Scar. Bien que Gluttony se régénère, Ling et les deux frères réussissent à l'emprisonner et à l'emmener dans un endroit loin des yeux de l'armée. Cette base de repli est aussi l'occasion de sauver Lan Fan qui a perdu son bras gauche pendant qu'elle protégeait Ling des assauts du Führer Bradley qui se révèle être un Homunculus.",
    type: 'Shonen',
    picture: '../assets/fma/023.jpeg',
    created: new Date('14 septembre 2009'),
    link1: 'https://vudeo.net/embed-qedl3gatvumd.html',
    link2: '',
    link3: '',
  },
  {
    episode: 24,
    season: 1,
    title: "Dans le ventre",
    summary: "Alors qu'il est prisonnier, Gluttony se retrouve face-à-face avec le colonel Mustang et réussit à se libérer grâce à sa rage envers Mustang qui a tué Lust. Le combat se poursuit dans la forêt alentour où Gluttony provoque d'énormes dégâts grâce à l'ouverture de son ventre qui lui confère une toute nouvelle puissance. Al, Ed et Ling se portent au secours du colonel débordé par les évènements. Bien qu'Envy fasse son apparition pour ramener Gluttony, ce dernier utilise son pouvoir d'absorption sur Ed et Ling. De son côté, le colonel Mustang se rend au quartier général pour avertir le général Raven de la vraie nature du Führer Bradley.",
    type: 'Shonen',
    picture: '../assets/fma/024.jpeg',
    created: new Date('20 septembre 2009'),
    link1: 'https://vudeo.net/embed-nx94iibsillh.html',
    link2: '',
    link3: '',
  },
  {
    episode: 25,
    season: 1,
    title: "La Porte des ténèbres",
    summary: "Prisonniers du ventre de Gluttony, Ed et Ling cherchent une issue pour rejoindre Al. Rejoints par Envy, ils apprennent qu'il n'existe pas de moyen de sortir de cet endroit qui est en fait une copie de la porte de la vérité. Bien que lui aussi piégé, Envy décide d'en finir avec Ed et Ling. Il n'hésite plus à utiliser sa force en montrant sa véritable apparence. De son côté, le colonel Mustang comprend de mieux en mieux les rouages des haut représentants de l'armée et voit que le système qu'il comptait combattre se referme inexorablement sur lui.",
    type: 'Shonen',
    picture: '../assets/fma/025.jpeg',
    created: new Date('29 septembre 2009'),
    link1: 'https://vudeo.net/embed-s6g6l9gnbdel.html',
    link2: '',
    link3: '',
  },
  {
    episode: 26,
    season: 1,
    title: "Retrouvailles",
    summary: "Al et Gluttony font route vers l'endroit où se trouve 'Père' afin de trouver un moyen de sortir Ed, Ling et Envy qui sont toujours prisonniers. Alors qu'il est en train de se faire absorber par Envy, Ed repense aux morceaux de pierres qui se trouvent dans la fausse porte de la vérité. Ces pierres, une fois regroupées, ressemblent aux symboles présents à Xerxès. Grâce à la pierre philosophale de Envy, Ed réalise une transmutation humaine sur lui-même pour permettre à tout le monde de sortir. Une fois devant la vraie porte de la vérité, il aperçoit le corps d'un jeune garçon blond qui n'est autre que le corps de Al.",
    type: 'Shonen',
    picture: '../assets/fma/026.jpeg',
    created: new Date('4 octobre 2009'),
    link1: 'https://vudeo.net/embed-j12d4r15qe25.html',
    link2: '',
    link3: '',
  },
  {
    episode: 27,
    season: 1,
    title: "Le Banquet d'interlude",
    summary: "Assis dans une forêt près d'un feu de bois qui le réchauffe, Hohenheim se remémore les évènements de sa vie et ce qui a amené Amestris là où elle est aujourd'hui.",
    type: 'Shonen',
    picture: '../assets/fma/027.jpeg',
    created: new Date('11 octobre 2009'),
    link1: 'https://vudeo.net/embed-xdb6s5qyynxs.html',
    link2: '',
    link3: '',
  },
  {
    episode: 28,
    season: 1,
    title: "Père",
    summary: "Ed et Al se retrouvent devant 'Père', un être qui ressemble trait pour trait à Hohenheim. Cet être qui est le créateur des Homunculus possède de grands pouvoirs lui permettant d'empêcher les deux frères d'utiliser l'alchimie. Ce pouvoir ne semble pourtant pas affecter Scar et May qui se lancent dans le combat, surtout Scar qui connait désormais le véritable instigateur de la guerre d'Ishval. Ling est capturée et transformée en Homunculus par 'Père' qui voit l'occasion de créer un nouveau Greed avec ce corps. Devant la force de ses adversaires, Scar est obligé de s'enfuir.",
    type: 'Shonen',
    picture: '../assets/fma/028.jpeg',
    created: new Date('18 octobre 2009'),
    link1: 'https://vudeo.net/embed-e6iagimh6k4n.html',
    link2: '',
    link3: '',
  },
  {
    episode: 29,
    season: 1,
    title: "Les Divagations d'un imbécile",
    summary: "Envy emmène Al et Ed dans le bureau de Warth qui n'est autre que l'Homunculus caché derrière les traits du Führer King Bradley. Ces derniers découvrent avec stupéfaction que le quartier général des Homunculus se situe sous celui de l'armée. Ils y retrouvent le colonel Mustang qui est désormais lui aussi au courant de la véritable identité du Führer. Le face-à-face est des plus tendus mais les alchimistes d'état décident de conserver leur poste au sein de l'armée. Ed s'interroge sur la raison qui a permis à Scar et May d'utiliser leurs pouvoirs alors que lui était impuissant. Cette autre forme d'alchimie lui permettra peut-être de ramener son corps et celui de son frère sans pierre philosophale.",
    type: 'Shonen',
    picture: '../assets/fma/029.jpeg',
    created: new Date('25 octobre 2009'),
    link1: 'https://vudeo.net/embed-y5qlwgk6tabi.html',
    link2: '',
    link3: '',
  },
  {
    episode: 30,
    season: 1,
    title: "L'Extermination d'Ishbal",
    summary: "Ed se rend chez le lieutenant Hawkeye afin de lui rendre son arme. C'est l'occasion pour Ed de se renseigner sur ce qu'il s'est réellement passé pendant la guerre d'Ishval. Bien que peu fière de ce qu'elle a fait durant cette guerre, le lieutenant Hawkeye lui décrit le déroulement de cette guerre et les massacres qu'elle a occasionnés. De son côté, Scar interroge le docteur Marcoh afin de connaître les motivations du déclenchement de cette guerre. Ce dernier ne tarde pas à lui dévoiler les expériences menées sur les Ishval et dont le but était la création d'une pierre philosophale.",
    type: 'Shonen',
    picture: '../assets/fma/030.jpeg',
    created: new Date('1er novembre 2009'),
    link1: 'https://vudeo.net/embed-mzsap2eimdjz.html',
    link2: '',
    link3: '',
  },
  {
    episode: 31,
    season: 1,
    title: "Une promesse à 520 cenz",
    summary: "Les différents membres de l'équipe du colonel Mustang doivent prendre leurs nouvelles fonctions laissant le colonel seul à Central. Bien qu'isolé, ce dernier n'a pas dit son dernier mot et continue sa progression vers son but final. Pendant ce temps, Kimblee est libéré grâce aux Homunculus cachés derrière leurs identités militaires. Il est chargé de retrouver Scar et le docteur Marcoh qui se sont enfuis. L'objectif de Scar est de retourner au nord, là où il a caché les recherches de son frère qu'il compte décoder avec l'aide du docteur Marcoh.",
    type: 'Shonen',
    picture: '../assets/fma/031.jpeg',
    created: new Date('8 novembre 2009'),
    link1: 'https://vudeo.net/embed-bas803rtzxqo.html',
    link2: '',
    link3: '',
  },
  {
    episode: 32,
    season: 1,
    title: "Le Fils du Führer",
    summary: "Le colonel Mustang se rend sur la tombe de général Hughes où il rencontre discrètement le général Grumman auquel il demande de l'aide. Les frères Elric, toujours à la recherche de May et en quête d'informations sur l'élixirologie, se rendent à la bibliothèque centrale où ils apprendront du commandant Armstrong que May fait route vers le nord. Prêts à quitter la bibliothèque, les deux frères font la rencontre de Selim, le fils du Führer. Ed et Al se retrouvent dans la maison des Bradley où ils découvrent un Führer plus humain et paternel, bien que le regard glacial de l'Homunculus soit toujours présent. Après cette rencontre, les deux frères entament leur voyage vers le nord.",
    type: 'Shonen',
    picture: '../assets/fma/032.jpeg',
    created: new Date('15 novembre 2009'),
    link1: 'https://vudeo.net/embed-2plcgvyk0zj1.html',
    link2: '',
    link3: '',
  },
  {
    episode: 33,
    season: 1,
    title: "La Muraille nord de Briggs",
    summary: "Kimblee réussi à rattraper Scar dans sa fuite vers le nord. L'issue du combat qui s'engage entre les deux hommes sera finalement reportée à plus tard par un Kimblee qui reconnaît son manque d'entraînement face à Scar. De leur côté, les frères Elric achèvent leur voyage vers le nord et arrivent au pied de la forteresse de Briggs où l'armée locale leur réserve un accueil des plus brusques. Ed et Al y font la rencontre d'Olivier Mira Armstrong, la sœur du commandant Armstrong. Malgré une lettre de recommandation de ce dernier, les deux frères semblent bien peu de chose face à cette femme au caractère bien trempé.",
    type: 'Shonen',
    picture: '../assets/fma/033.jpeg',
    created: new Date('22 novembre 2009'),
    link1: 'https://vudeo.net/embed-ilsrrx4h1pg5.html',
    link2: '',
    link3: '',
  },
  {
    episode: 34,
    season: 1,
    title: "La Reine des glaces",
    summary: "Les frères Elric sont autorisés à rester dans la forteresse mais le général Armstrong veut connaître les raisons qui les ont amenées jusqu'ici. Bien qu'expliquant leur quête pour récupérer leurs corps, les deux frères font abstraction des Homunculus qui les obligeraient à révéler la véritable identité du Führer. Lors de leur visite dans les installations de la forteresse, Al et Ed retrouvent le sous-lieutenant Falman qui a été muté dans la forteresse par le QG nord. La visite est interrompue par l'apparition de Sloth, un Homunculus inconnu des deux frères et qui ne semble pas venu pour les affronter.",
    type: 'Shonen',
    picture: '../assets/fma/034.jpeg',
    created: new Date('29 novembre 2009'),
    link1: 'https://vudeo.net/embed-jodg2y4h3750.html',
    link2: '',
    link3: '',
  },
  {
    episode: 35,
    season: 1,
    title: "Les Contours de ce pays",
    summary: "Bien qu'ayant joint leurs forces à celles des membres de la forteresse afin de se débarrasser de l'Homunculus, le général Armstrong soupçonne les deux frères de cacher des informations. Les soupçons du général à propos de l'armée se voient renforcés par les révélations des deux frères qui divulguent le complot qui se déroule au sein même de l'armée. Al et Ed ne sont pourtant pas au bout de leurs surprises puisqu'ils découvrent que les différents champs de guerres qui ont conduit à l'annexion des pays voisins d'Amestris forment un cercle de transmutation qui pourrait servir à la création d'une pierre philosophale en sacrifiant tous les habitants du pays.",
    type: 'Shonen',
    picture: '../assets/fma/035.jpeg',
    created: new Date('6 décembre 2009'),
    link1: 'https://vudeo.net/embed-3yuubfm52agc.html',
    link2: '',
    link3: '',
  },
  {
    episode: 36,
    season: 1,
    title: "Portrait de famille",
    summary: "Le lieutenant-général Raven, accompagné de Kimblee, se rend à la forteresse de Briggs. Il prend possession des locaux et ordonne la libération de Sloth pour la poursuite de son plan. Bien que réticente au départ, le général Armstrong s'exécute et se retrouve par la même occasion dans les confidences du lieutenant-général Raven. Celui-ci propose au général de faire partie des élus de ce pays et d'acquérir l'immortalité, mais une fois les informations obtenues, le général Armstrong n'hésite pas à se débarrasser du lieutenant-général Raven. De son côté, Kimblee rend visite aux deux frères auxquels il amène une vieille connaissance. Winry a été officiellement contactée par le Führer pour entretenir l'auto-mail de Ed.",
    type: 'Shonen',
    picture: '../assets/fma/036.jpeg',
    created: new Date('13 décembre 2009'),
    link1: 'https://vudeo.net/embed-s8kvf6oy0o60.html',
    link2: '',
    link3: '',
  },
  {
    episode: 37,
    season: 1,
    title: "Le Premier Homonculus",
    summary: "Kimblee confie à Edward la tâche de retrouver Scar et le docteur Marcoh, ainsi que de créer un massacre à Briggs sous peine de représailles. Edward ne veut pas mentir plus longtemps à Winry et lui révèle les ordres qui lui ont été donnés et le fait qu'elle soit une otage de l'armée. Cette dernière, bien décidée à ne plus se contenter d'attendre sans rien dire, prend part au voyage de Ed et Al à la recherche de Scar et du docteur Marcoh. De son côté, le lieutenant Hawkeye découvre la véritable identité du fils du Führer. Sous les traits du petit garçon se cache le premier Homonculus.",
    type: 'Shonen',
    picture: '../assets/fma/037.jpeg',
    created: new Date('20 décembre 2009'),
    link1: 'https://vudeo.net/embed-2uu4dmk25puw.html',
    link2: '',
    link3: '',
  },
  {
    episode: 38,
    season: 1,
    title: "La Bataille de Baschool",
    summary: "Ed et Al se lancent à la recherche de May. Ils finissent par la retrouver, ainsi que le docteur Marcoh qui est méconnaissable. Ce dernier leur révèle l'existence du manuscrit rédigé par le frère de Scar qui semblait déjà avoir tout compris sur les enjeux de ces guerres. Il est primordial de décrypter ce recueil qui détient la clé du mystère. Les retrouvailles sont interrompues par une explosion due au combat entre Scar et deux chimères créées par l'armée. Les frères Elric s'élancent dans le combat et parviennent à venir à bout des deux chimères et à immobiliser Scar. Winry, qui les à suivis, s'approche de Scar pour une discussion en tête-à-tête mais elle se retrouve prisonnière de ce dernier.",
    type: 'Shonen',
    picture: '../assets/fma/038.jpeg',
    created: new Date('27 décembre 2009'),
    link1: 'https://vudeo.net/embed-e4a1o9kiwj0g.html',
    link2: '',
    link3: '',
  },
  {
    episode: 39,
    season: 1,
    title: "Un rêve éveillé",
    summary: "Bien que Winry ne pardonne pas à Scar, elle n'hésite pas à le soigner comme l'auraient fait ses parents. Très étonné, Scar accepte le plan proposé par la jeune fille qui doit lui permettre de s'échapper et de se rendre à la forteresse de Briggs pour aider le docteur Marcoh à décrypter le manuscrit rédigé par son frère. Le blizzard qui entoure la ville va permettre au groupe de s'échapper par le réseau minier. Les frères Elric, épaulés par le commandant Miles, jouent la comédie devant la fuite de Scar afin de tromper Kimblee et ne pas éveiller ses soupçons sur le plan qu'ils ont mis en œuvre.",
    type: 'Shonen',
    picture: '../assets/fma/039.jpeg',
    created: new Date('10 janvier 2010'),
    link1: 'https://vudeo.net/embed-fvot9kkndwkh.html',
    link2: '',
    link3: '',
  },
  {
    episode: 40,
    season: 1,
    title: "Homonculus, le petit être dans une fiole",
    summary: "Le général de division Armstrong arrive à Central, où elle a été convoquée par le Führer pour s'expliquer sur la disparition du lieutenant-général Raven. Se sentant acculée face au Führer, elle ne peut que lui révéler qu'elle connait sa véritable identité ainsi que ses plans. En échange de cela, elle souhaite prendre la place qu'occupait le lieutenant-général Rave. De son côté, Van Hohenheim se remémore son enfance d'esclave et surtout la rencontre avec l'Homonculus qui va définitivement changer sa vie. Celle-ci semble s'être terminée le jour où il est devenu une pierre philosophale humaine.",
    type: 'Shonen',
    picture: '../assets/fma/040.jpeg',
    created: new Date('17 janvier 2010'),
    link1: 'https://vudeo.net/embed-rfr6kst0p7h5.html',
    link2: '',
    link3: '',
  },
  {
    episode: 41,
    season: 1,
    title: "Abysses",
    summary: "Le commandant Miles décide de tout mettre en œuvre pour éliminer Kimblee. Bien que Ed soit plutôt pour le capturer et lui soutirer le maximum d'informations, sa tentative se soldera par un échec lorsqu'il se retrouve face à Kimblee en possession d'une pierre philosophale qui lui permettra de s'échapper et de blesser grièvement Ed. La seule chance de Ed pour s'en sortir repose sur son utilisation de l'alchimie de guérison. De son côté, Al a réussi à rattraper le groupe de Scar pour les informer que la forteresse de Briggs n'est plus un lieu sûr pour eux.",
    type: 'Shonen',
    picture: '../assets/fma/041.jpeg',
    created: new Date('24 janvier 2010'),
    link1: 'https://vudeo.net/embed-51d37at49vck.html',
    link2: '',
    link3: '',
  },
  {
    episode: 42,
    season: 1,
    title: "Le Début de la contre-attaque",
    summary: "Le petit groupe du docteur Marcoh finit par découvrir le sens caché du manuscrit rédigé par le frère de Scar. Ce cercle de transmutation composé d'éléments d'élixirologie n'augure rien de bon. De son côté, Kimblee, qui a réussi à s'en sortir face à Ed, se lance à la poursuite du petit groupe du docteur Marcoh. Il sera bien vite rattrapé par Pride qui lui confiera une autre tâche. Le cercle autour d'Amestris étant achevé, Kimblee devra mettre le pays à feu et à sang afin de répandre le sang nécessaire à la création de la pierre philosophale.",
    type: 'Shonen',
    picture: '../assets/fma/042.jpeg',
    created: new Date('31 janvier 2010'),
    link1: 'https://vudeo.net/embed-7e45w21xt8vp.html',
    link2: '',
    link3: '',
  },
  {
    episode: 43,
    season: 1,
    title: "La Morsure d'une fourmi",
    summary: "Zampano, qui a trahi le groupe du docteur Marcoh, mène Envy vers le lieu où le docteur s'est réfugié. Envy, impatient de pouvoir tuer le docteur Marcoh, ne se rend compte que trop tard du piège qui lui a été tendu. C'est finalement l'attaque conjointe de Scar et du docteur Marcoh qui redonnera à Envy sa forme première. Bien que dans une position inconfortable, Envy ne semble pas prêt à dévoiler le plan des Homonculus. Tandis que May retourne dans son pays et que Scar et le docteur Marcoh partent de leur côté, le reste du groupe se dirige vers Lior dans l'espoir de pouvoir sauver le peuple d'Amestris.",
    type: 'Shonen',
    picture: '../assets/fma/043.jpeg',
    created: new Date('7 février 2010'),
    link1: 'https://vudeo.net/embed-hfj4szn427sf.html',
    link2: '',
    link3: '',
  },
  {
    episode: 44,
    season: 1,
    title: "En avant toute !",
    summary: "Le groupe arrive à Lior où Al et Winry retrouvent Hohenheim. La vie dans la ville semble reprendre son court après les terribles émeutes qui ont suivi la chute du culte de Leto. Hohenheim se décide enfin à confier à Al qu'il est une pierre philosophale et qu'il compte tout faire pour sauver ce pays. Al, venu lui aussi pour sauver le pays, n'hésite pas à faire confiance à ce père qui a fait défaut durant de nombreuses années. De son côté, Ed se remet de ses blessures et doit fuir avec ses deux compagnons pour échapper à l'armé du nord. Son objectif est maintenant de retrouver Al.",
    type: 'Shonen',
    picture: '../assets/fma/044.jpeg',
    created: new Date('14 février 2010'),
    link1: 'https://vudeo.net/embed-7oc6wuig0atr.html',
    link2: '',
    link3: '',
  },
  {
    episode: 45,
    season: 1,
    title: "Le Jour promis",
    summary: "Ed et ses deux compagnons s'arrêtent dans un refuge que lui et son frère ont utilisé autrefois. Al ne s'y trouve pas mais c'est finalement Ling qu'ils y rencontreront. Ce dernier réussit à donner quelques informations à Ed avant que Greed ne reprenne le contrôle du corps de Ling. Après que celui-ci leur ait expliqué qu'il a coupé les ponts avec les autres Homonculus, Ed lui propose de rejoindre leur groupe. D'abord réticent, Greed accepte lorsque Ed lui propose d'être son larbin. Sans que cela n'attire le regard des Homonculus, l'organisation des membres de la révolution avance de plus belle.",
    type: 'Shonen',
    picture: '../assets/fma/045.jpeg',
    created: new Date('21 février 2010'),
    link1: 'https://vudeo.net/embed-xhgxu4d3zc80.html',
    link2: '',
    link3: '',
  },
  {
    episode: 46,
    season: 1,
    title: "L'ombre qui approche",
    summary: "Le jour promis approche à grands pas et l'organisation de la révolution se resserre autour des Homonculus. Al a de plus en plus de mal à contrôler ses pertes de conscience qui le ramènent près de son corps. C'est à ce plus mauvais moment que Gluttony et Pride en profitent pour capturer Al. Le groupe de la révolution, quant à lui, lance son plan pour libérer Amestris grâce à un jeu de manipulation des hautes instances. Cette première étape a pour but l'élimination du Führer King Bradley, la tête pensante de Central.",
    type: 'Shonen',
    picture: '../assets/fma/046.jpeg',
    created: new Date('28 février 2010'),
    link1: 'https://vudeo.net/embed-ldbikg1pzrj7.html',
    link2: '',
    link3: '',
  },
  {
    episode: 47,
    season: 1,
    title: "Le Messager des ténèbres",
    summary: "Ed arrive à Kanama où il retrouve son père qui lui explique ce qu'il en est, ainsi que le but ultime du jour promis. Bien que toujours en colère contre son père, Ed est surpris devant la réaction de Hohenheim lorsque celui-ci apprend les derniers mots de sa femme. Ed finit par retrouver Al dans la forêt voisine mais celui-ci est contrôlé par Pride. Bien que Pride soit temporairement sans pouvoir, Gluttony n'hésite pas à se jeter sur Ed et Greed qui ne devront leur salut qu'à l'arrivée de Lan Fan.",
    type: 'Shonen',
    picture: '../assets/fma/047.jpeg',
    created: new Date('7 mars 2010'),
    link1: 'https://vudeo.net/embed-0wfbcqegnn8q.html',
    link2: '',
    link3: '',
  },
  {
    episode: 48,
    season: 1,
    title: "La Promesse du passage souterrain",
    summary: "Alors que Ling et Lan Fan semblent maîtriser Gluttony sans difficulté, Heinkel n'est plus en position de force et seule l'intervention de Ed lui permet de rester en vie. Bien que résistant aux attaques de Pride, Ed va se retrouver face à Al manipulé par Pride. La libération de Al n'est possible que grâce à l'intervention de Fu, un des serviteurs de Ling. Pendant ce temps, le colonel Roy Mustang et son groupe prennent en otage la femme du Führer King Bradley.",
    type: 'Shonen',
    picture: '../assets/fma/048.jpeg',
    created: new Date('14 mars 2010'),
    link1: 'https://vudeo.net/embed-bdc4qqxrn49j.html',
    link2: '',
    link3: '',
  },
  {
    episode: 49,
    season: 1,
    title: "Amour familial",
    summary: "Ed et Greed ont bien du mal à résister aux attaques de Pride et seule l'intervention de Hohenheim et Al pourra les sauver. Ce dernier se fait volontairement enfermer avec Pride dans une cage de terre qui ne laisse pas pénétrer la lumière. Ce moment d'isolement sera l'occasion pour Pride de révéler l'admiration qu'il a pour celle qui l'a élevé. Bien que Pride soit enfermé, Ed et tous ses compagnons se préparent à l'arrivée du 'Jour promis' qui risque de bouleverser la vie de tous les habitants d'Amestris.",
    type: 'Shonen',
    picture: '../assets/fma/049.jpeg',
    created: new Date('21 mars 2010'),
    link1: 'https://vudeo.net/embed-pv3jlb71qffs.html',
    link2: '',
    link3: '',
  },
  {
    episode: 50,
    season: 1,
    title: "Panique à Central",
    summary: "Le 'Jour promis' est arrivé et la rébellion se déchaîne. Que ce soit Ed et ses compagnons, Mustang et son équipe ou les soldats de Briggs, tous se dirigent vers le cœur de Central. Les soldats de Central sont, quant à eux, prêts à tout pour ramener l'ordre dans la ville, quitte à devoir tuer la femme du Führer. Lors de sa progression, Mustang se voit rejoint par des frères d'arme tels que Jean Havoc et Maria Ross qui comptent bien aider leur ancien supérieur. De leur côté, Ed et sa bande réussissent à accéder au sous-sol en empruntant l'entrée du laboratoire n°3.",
    type: 'Shonen',
    picture: '../assets/fma/050.jpeg',
    created: new Date('28 mars 2010'),
    link1: 'https://vudeo.net/embed-ovilsd72lx5c.html',
    link2: '',
    link3: '',
  },
  {
    episode: 51,
    season: 1,
    title: "L'Armée immortelle",
    summary: "Ed et sa bande pénètrent enfin dans le sous-sol du laboratoire n°3 où une grosse surprise les attend. Ils se retrouvent nez à nez avec une horde de soldats composée d'âmes humaines et de pierres philosophales, et manipulée par l'armée afin de créer des soldats immortels. Pendant ce temps, Pride réussit à contacter Kimblee afin qu'il vienne le délivrer du piège où il est enfermé. Al, n'ayant plus le choix, se saisit de la pierre philosophale tendue par Heinkel afin d'affronter Pride et Kimblee.",
    type: 'Shonen',
    picture: '../assets/fma/051.jpeg',
    created: new Date('4 avril 2010'),
    link1: 'https://vudeo.net/embed-cuf7ihutg50r.html',
    link2: '',
    link3: '',
  },
  {
    episode: 52,
    season: 1,
    title: "L'union fait la force",
    summary: "Le combat qui oppose Al à Pride et Kimblee permet d'exploiter le potentiel de la pierre philosophale mais cette dernière ne lui permettra pas de vaincre le duo. Seule l'arrivée de Heinkel et du docteur Marcoh pourra lui permettre de se retirer de ce combat de front perdu d'avance. De son côté, Ed n'arrive pas à se débarrasser de ce flot continu de soldats immortels. L'entrée en scène de Mustang, qui arrive au cœur du combat, pourrait bien renverser la situation.",
    type: 'Shonen',
    picture: '../assets/fma/052.jpeg',
    created: new Date('11 avril 2010'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 53,
    season: 1,
    title: "Les Flammes de la vengeance",
    summary: "Mustang porte secours à Ed et sa bande en brûlant tous les soldats immortels dressés devant lui. Quelques instants plus tard, Envy se retrouve face à eux et ne se cache plus d'être le meurtrier de Hughes. Sous l'emprise de la vengeance, Mustang se lance dans un affrontement face à Envy qu'il veut voir mourir à petit feu, laissant la voie libre aux autres pour rejoindre 'Père'. Le reste de l'équipe de Mustang en profite pour informer la population du coup d'état qui se déroule via la radio nationale.",
    type: 'Shonen',
    picture: '../assets/fma/053.jpeg',
    created: new Date('18 avril 2010'),
    link1: 'https://vudeo.net/embed-otqv9eio8rdt.html',
    link2: '',
    link3: '',
  },
  {
    episode: 54,
    season: 1,
    title: "La Terre Brûlée",
    summary: "Toujours à la poursuite d'Envy, Mustang réussit à le rattraper et à lui faire reprendre sa forme primaire. Sur le point de l'éliminer, Riza, Scar et Ed font comprendre à Mustang que cette haine qui l'aveugle ne lui permettra pas de diriger le pays qu'il souhaite prospère. Devant ce retournement de situation, Envy ne peut que comprendre sa jalousie de l'être humain et préfère se suicider plutôt que de vivre dans la honte de cette infériorité face aux humains.",
    type: 'Shonen',
    picture: '../assets/fma/054.jpeg',
    created: new Date('25 avril 2010'),
    link1: 'https://vudeo.net/embed-do3bkdlr0r9w.html',
    link2: '',
    link3: '',
  },
  {
    episode: 55,
    season: 1,
    title: "L'Éthique de vie de ces adultes",
    summary: "Bien que tous les deux soient de redoutables guerriers, Oliver et Alex Armstrong ne parviennent pas à venir à bout de Sloth qui ne cesse de se régénérer. Seule l'arrivée d'Izumi et son mari permettra la destruction de Sloth. Pendant ce temps, à l'extérieur, les différentes sections de l'armée de Briggs prennent tour à tour les points stratégiques du quartier général. Au sous-sol, les retrouvailles entre Hohenheim et 'Père' annoncent un affrontement qui déterminera de l'avenir du pays.",
    type: 'Shonen',
    picture: '../assets/fma/055.jpeg',
    created: new Date('2 mai 2010'),
    link1: 'https://vudeo.net/embed-7s8147gbyvl5.html',
    link2: '',
    link3: '',
  },
  {
    episode: 56,
    season: 1,
    title: "Le Retour du Führer",
    summary: "Le retour du Führer provoque un regain de hargne parmi le reste des troupes de l'armée de Central et la porte principale ne tarde pas à être reprise. Une fois arrivé tout en haut, le Führer se retrouve face à Greed qui semble lui aussi bien impuissant face à cet homme plein de ressources. L'arrivée du garde du corps du prince promet un combat plein d'entrain, surtout que ce dernier se retrouve face à celui qui a provoqué la perte du bras de sa petite fille.",
    type: 'Shonen',
    picture: '../assets/fma/056.jpeg',
    created: new Date('9 mai 2010'),
    link1: 'https://vudeo.net/embed-ho0eney1kt7z.html',
    link2: '',
    link3: '',
  },
  {
    episode: 57,
    season: 1,
    title: "Repos éternel",
    summary: "Le combat qui oppose Fu et Greed face au Führer tourne à l'avantage de ce dernier qui semble intouchable. Même le sacrifice de Fu ne suffira pas à venir à bout du Führer. Au sous-sol, Ed et sa bande se retrouvent face au docteur Gold-toothed qui n'est autre que le créateur du Führer. Il ne tarde pas à envoyer les autres prétendants au titre de Führer contre Ed et sa bande. Cet assaut laisse le temps au docteur Gold-toothed de créer un cercle de transmutation qui ne tarde pas à aspirer Ed, Al et Izumi.",
    type: 'Shonen',
    picture: '../assets/fma/057.jpeg',
    created: new Date('16 mai 2010'),
    link1: 'https://vudeo.net/embed-iblsui5avadu.html',
    link2: '',
    link3: '',
  },
  {
    episode: 58,
    season: 1,
    title: "Sacrifices humains",
    summary: "Avec l'aide des soldats de Brigg, Ling réussit par se débarrasser du Führer qui finit dans les douves du château. Le souhait du capitaine Buccaneer étant de protéger la grande porte comme le lui a ordonné le général Armstrong, Ling fait appel au pouvoir de Greed pour protéger la grande porte ainsi que le peuple. Au sous-sol, le docteur Gold-toothed demande à Mustang de faire une transmutation humaine. Celui-ci refuse mais le docteur n'hésite pas à se servir de Riza pour faire réagir Mustang.",
    type: 'Shonen',
    picture: '../assets/fma/058.jpeg',
    created: new Date('23 mai 2010'),
    link1: 'https://vudeo.net/embed-udov4sunxb6z.html',
    link2: '',
    link3: '',
  },
  {
    episode: 59,
    season: 1,
    title: "Lumière perdue",
    summary: "Bien que le colonel Mustang refuse de procéder à une transmutation humaine malgré l'état de Riza, le Führer et Pride réussissent à lui faire effectuer cette transmutation de force. Le colonel Mustang se retrouve projeté avec Ed et les trois autres 'sacrifices' et perd l'usage de la vue au passage de la porte de la vérité. Al qui est toujours devant la porte de la vérité doit faire le terrible choix de laisser son corps qu'il vient enfin de retrouver pour aider ses camarades.",
    type: 'Shonen',
    picture: '../assets/fma/059.jpeg',
    created: new Date('30 mai 2010'),
    link1: 'https://vudeo.net/embed-89n06iy38oed.html',
    link2: '',
    link3: '',
  },
  {
    episode: 60,
    season: 1,
    title: "L'Œil du ciel, la porte de la terre",
    summary: "May tente de se débarrasser de 'Père' à l'aide de son élixirologie, laissant le champ libre à Ed et Al pour se débarrasser de Pride affaiblit durant la transmutation mais la tâche s'annonce des plus difficiles. La dernière tentative de Greed, venu en renfort pour s'accaparer le monde, semble pourtant bien inutile puisque 'Père' réussit finalement à ouvrir la porte de la Terre. Tous ces sacrifices doivent lui permettre d'absorber Dieu et ainsi contrôler le monde entier.",
    type: 'Shonen',
    picture: '../assets/fma/060.jpeg',
    created: new Date('6 juin 2010'),
    link1: 'https://vudeo.net/embed-hkm6g2utb3fx.html',
    link2: '',
    link3: '',
  },
  {
    episode: 61,
    season: 1,
    title: "Celui qui avale Dieu",
    summary: "Bien que 'Père' ait finalement avalé Dieu et semble désormais immortel, Hohenheim parvient à l'affaiblir et à rendre leurs âmes aux habitants d'Amestris. Il réussit grâce à un cercle de transmutation inversé et aux pierres philosophales qu'il a dispersées un peu partout dans le pays. 'Père' s'enfuit afin de créer de nouvelles pierres philosophales mais il est suivi de près par Hohenheim et les autres. Ed, quant à lui, reste afin d'en finir avec Pride.",
    type: 'Shonen',
    picture: '../assets/fma/061.jpeg',
    created: new Date('13 juin 2010'),
    link1: 'https://vudeo.net/embed-q4mct517wi4f.html',
    link2: '',
    link3: '',
  },
  {
    episode: 62,
    season: 1,
    title: "Contre-attaque déchaînée",
    summary: "Alors que 'Père' est retourné à la surface, Hohenheim et tout le reste de la bande se lance à sa poursuite afin de mener le dernier combat. Malgré le flux d'attaques incessantes, 'Père' reste intouchable. Il sera une nouvelle fois déstabilisé par une attaque surprise de Greed qui permettra d'affaiblir l'homme jusqu'alors intouchable. Al se sacrifie afin de permettre à Ed de retrouver les membres jadis perdus et d'utiliser tout son potentiel.",
    type: 'Shonen',
    picture: '../assets/fma/062.jpeg',
    created: new Date('20 juin 2010'),
    link1: 'https://vudeo.net/embed-iwcjy94r9o4o.html',
    link2: '',
    link3: '',
  },
  {
    episode: 63,
    season: 1,
    title: "De l'autre côté de la porte",
    summary: "Grâce à Greed qui se laisse absorber par 'Père' et utilise son pouvoir de carbonisation, Ed peut désormais venir à bout du petit être de la fiole qui se voit détruit par son orgueil. Son désir absolu de liberté et de contrôle du monde le conduit à sa perte. Ed trouve finalement le moyen de ramener Al avec son corps en affrontant une dernière fois la vérité. Toutes ces épreuves ont finalement fait comprendre à Ed les choses sur lesquelles il pouvait vraiment compter.",
    type: 'Shonen',
    picture: '../assets/fma/063.jpeg',
    created: new Date('27 juin 2010'),
    link1: 'https://vudeo.net/embed-vusdbr54bf1v.html',
    link2: '',
    link3: '',
  },
  {
    episode: 64,
    season: 1,
    title: "Au bout du voyage",
    summary: "La paix est enfin revenue à Amestris. Mustang est bien déterminé à assurer cette paix dans le pays entier en créant des liens forts avec le peuple Ishval et ainsi ne plus reproduire les erreurs du passé. Al décide de partir dans les pays de l'est afin d'y étudier l'élixirologie et Ed se dirige, quant à lui, vers les pays de l'ouest. Les frères Elric espèrent ainsi en apprendre beaucoup plus sur le monde qui les entoure.",
    type: 'Shonen',
    picture: '../assets/fma/064.jpeg',
    created: new Date('4 juillet 2010'),
    link1: 'https://vudeo.net/embed-wb3at0qlxoxr.html',
    link2: '',
    link3: '',
  },
]
