import { Anime } from "../modeles/anime";

export const GOLDENBOY : Anime[] = [
  {
    episode: 1,
    season: 1,
    title : 'Leçons d’informatique',
    summary: 'Résumé non disponible',
    type: 'Shonen',
    picture: '../assets/goldenBoy/001.jpeg',
    created: new Date('27 octobre 1995'),
    link1: 'https://www.youtube.com/embed/yrIr1x34lI8',
    link2: '',
    link3: '',
  },
  {
    episode: 2,
    season: 1,
    title : 'L’Ange de la séduction',
    summary: 'Résumé non disponible',
    type: 'Shonen',
    picture: '../assets/goldenBoy/002.jpeg',
    created: new Date('22 novembre 1995'),
    link1: 'https://www.youtube.com/embed/rOOyw6H75rI',
    link2: '',
    link3: '',
  },
  {
    episode: 3,
    season: 1,
    title : 'Naissance d\'un amour',
    summary: 'Résumé non disponible',
    type: 'Shonen',
    picture: '../assets/goldenBoy/003.jpeg',
    created: new Date('22 décembre 1995'),
    link1: 'https://www.youtube.com/embed/QXCigrW2Z1Y',
    link2: '',
    link3: '',
  },
  {
    episode: 4,
    season: 1,
    title : 'Eaux troubles',
    summary: 'Résumé non disponible',
    type: 'Shonen',
    picture: '../assets/goldenBoy/004.jpeg',
    created: new Date('26 avril 1996'),
    link1: 'https://www.youtube.com/embed/tEsJzMC-nqI',
    link2: '',
    link3: '',
  },
  {
    episode: 5,
    season: 1,
    title : 'Jeunesse effrénée',
    summary: 'Résumé non disponible',
    type: 'Shonen',
    picture: '../assets/goldenBoy/005.jpeg',
    created: new Date('24 mai 1996'),
    link1: 'https://www.youtube.com/embed/_ppAVKDdL2Y',
    link2: '',
    link3: '',
  },
  {
    episode: 6,
    season: 1,
    title : 'L\'animation, c\'est génial',
    summary: 'Résumé non disponible',
    type: 'Shonen',
    picture: '../assets/goldenBoy/006.jpeg',
    created: new Date('28 juin 1996'),
    link1: 'https://www.youtube.com/embed/5Up0v93dIw8',
    link2: '',
    link3: '',
  },
]
