import { Anime } from "../modeles/anime";


export const GTO : Anime[] = [
  {
    episode: 1,
    season: 1,
    title : 'Lesson 1',
    summary: "Eikichi Onizuka est un jeune homme de 22 ans qui aspire à devenir professeur malgré une jeunesse tumultueuse consacrée aux bagarres et mauvaises fréquentations. Il commence par suivre un stage de deux semaines dans le lycée Musashi-No-Kita et doit prendre en charge la classe la plus turbulente...",
    type: 'Shonen',
    picture: '../assets/greatTeacherOnizuka/001.jpeg',
    created: new Date('30 juin 1999'),
    link1: '//ok.ru/videoembed/951602252333',
    link2: '',
    link3: '',
  },
  {
    episode: 2,
    season: 1,
    title : 'Lesson 2',
    summary: "Après avoir manqué l'examen pour devenir professeur dans le public, Onizuka se voit offrir une chance d'occuper un poste dans un établissement privé, le Holy Forest Academy. Le jour de l'entretien, il fait la rencontre d'Azusa Fuyutsuki et de Hirochi Uchiyamada, un sous-directeur très remonté contre lui.",
    type: 'Shonen',
    picture: '../assets/greatTeacherOnizuka/002.jpeg',
    created: new Date('7 juillet 1999'),
    link1: '//ok.ru/videoembed/852891732530',
    link2: '',
    link3: '',
  },
  {
    episode: 3,
    season: 1,
    title : 'Lesson 3',
    summary: "Onizuka obtient le poste de professeur titulaire et enseigne à la classe des 3-4, composée des pires élèves que l'établissement ait jamais connus... Deux professeurs avant lui ont dû quitter leur poste suite à une dépression nerveuse. Pour être embauché, une seule condition : résider sur les lieux.",
    type: 'Shonen',
    picture: '../assets/greatTeacherOnizuka/003.jpeg',
    created: new Date('21 juillet 1999'),
    link1: '//ok.ru/videoembed/852891863602',
    link2: '',
    link3: '',
  },
  {
    episode: 4,
    season: 1,
    title : 'Lesson 4',
    summary: "Être le professeur des 3-4 n'est pas chose aisée, même pour Onizuka qui ne peut lutter contre les photographies malsaines révélant au grand jour toute sa débauche... Même sa collègue Azusa Fuyutsuki voit en lui un pervers impardonnable. Pendant qu'il tente tant bien que mal de se disculper, ses élèves veulent à tout prix le faire renvoyer.",
    type: 'Shonen',
    picture: '../assets/greatTeacherOnizuka/004.jpeg',
    created: new Date('11 août 1999'),
    link1: '//ok.ru/videoembed/951602514477',
    link2: '',
    link3: '',
  },
  {
    episode: 5,
    season: 1,
    title : 'Lesson 5',
    summary: "Pour s'être montré beaucoup trop amical envers Onizuka alors que bon nombre d'élèves ont l'intention de le renvoyer, Yoshikawa se fait brutaliser par Anko et ses amies. Excédé par les exactions auxquelles se livrent ces dernières, Yoshikawa décide de mettre fin à ses jours en se jetant du toit de l'établissement, mais il est sauvé in extremis par Onizuka...",
    type: 'Shonen',
    picture: '../assets/greatTeacherOnizuka/005.jpeg',
    created: new Date('18 août 1999'),
    link1: '//ok.ru/videoembed/852891929138',
    link2: '',
    link3: '',
  },
  {
    episode: 6,
    season: 1,
    title : 'Lesson 6',
    summary: "Après avoir compromis Anko, la fille de la présidente du PTA, Onizuka est convoqué à une réunion de parents d'élèves en vue de fournir des explications pour justifier ses actes. Anko voit là une parfaite occasion pour renvoyer ce professeur en influençant sa mère. Mais Yoshikawa a bien l'intention d'aider Onizuka jusqu'au bout et demande assistance auprès de Kikuchi.",
    type: 'Shonen',
    picture: '../assets/greatTeacherOnizuka/006.jpeg',
    created: new Date('25 août 1999'),
    link1: '//ok.ru/videoembed/852891994674',
    link2: '',
    link3: '',
  },
  {
    episode: 7,
    season: 1,
    title : 'Lesson 7',
    summary: "Murai est très ennuyée car c'est la période où les professeurs visitent les parents à leur domicile. Or sa mère est encore dans sa pleine jeunesse et il craint qu'Onizuka ne profite de cette visite pour la séduire... Il incite alors ses camarades par la force à refuser la visite. Mais manque de chance, Onizuka et sa mère parviennent tout de même à se rencontrer malgré sa vigilance...",
    type: 'Shonen',
    picture: '../assets/greatTeacherOnizuka/007.jpeg',
    created: new Date('1er septembre 1999'),
    link1: '//ok.ru/videoembed/852892060210',
    link2: '',
    link3: '',
  },
  {
    episode: 8,
    season: 1,
    title : 'Lesson 8',
    summary: "Onizuka devient de plus en plus populaire auprès des 3-4 et de plus en plus d'élèves se rallient à sa cause, ce qui a pour effet d'agacer au plus haut point ceux et celles qui sont encore contre lui. Une fois la classe terminée, Murai surprend sa mère et Onizuka, qui avaient prévu un rendez-vous au bowling. Mais en pleine partie, la mère de Murai doit repartir, laissant ce dernier et ses amis seuls avec le professeur avec qui le courant ne passe pas vraiment...",
    type: 'Shonen',
    picture: '../assets/greatTeacherOnizuka/008.jpeg',
    created: new Date('8 septembre 1999'),
    link1: '//ok.ru/videoembed/852892125746',
    link2: '',
    link3: '',
  },
  {
    episode: 9,
    season: 1,
    title : 'Lesson 9',
    summary: "Victime d'un des projectiles d'Onizuka, le professeur d'éducation physique Fukuroda lui lance un défi de natation. Si Onizuka perd, il ne doit plus jamais sortir du rôle de simple professeur durant ses heures d'enseignement. Après la confrontation, Miyabi élabore un nouveau plan pour faire renvoyer de manière certaine Onizuka en lui faisant endosser le vol de sous-vêtements féminin. Pour se faire, elle demande à Tomoko Nomura d'introduire les sous-vêtements dans le casier d'Onizuka.",
    type: 'Shonen',
    picture: '../assets/greatTeacherOnizuka/005.jpeg',
    created: new Date('22 septembre 1999'),
    link1: '//ok.ru/videoembed/852892191282',
    link2: '',
    link3: '',
  },
  {
    episode: 10,
    season: 1,
    title : 'Lesson 10',
    summary: "Suite à la dernière opération manquée de Miyabi pour faire renvoyer Onizuka, Tomoko Nomura se fait rejeter par cette dernière qui la tient responsable de cet échec. Depuis lors elle est la cible de mauvaises plaisanteries en tout genre, notamment du fait de sa 'lenteur' d'esprit, ce qui ne facilite en rien son intégration auprès de ses autres camarades. Pour tenter de la réhabiliter, Onizuka a pour projet d'en faire une nouvelle idole...",
    type: 'Shonen',
    picture: '../assets/greatTeacherOnizuka/010.jpeg',
    created: new Date('12 septembre 1999'),
    link1: '//ok.ru/videoembed/951603366445',
    link2: '',
    link3: '',
  },
  {
    episode: 11,
    season: 1,
    title : 'Lesson 11',
    summary: "Le concours de beauté a enfin débuté, et Tomoko a une adversaire de taille, Miyabi, dont la prestation enchante les juges. Pour Murai et ses amis, le cas de Tomoko est désespéré, ils ne voient absolument pas en quoi ses maladresses successives peuvent contribuer à en faire une future star selon les dires d'Onizuka... Mais ce dernier reste confiant et croit au potentiel de Tomoko.",
    type: 'Shonen',
    picture: '../assets/greatTeacherOnizuka/011.jpeg',
    created: new Date('17 octobre 1999'),
    link1: '//ok.ru/videoembed/852892322354',
    link2: '',
    link3: '',
  },
  {
    episode: 12,
    season: 1,
    title : 'Lesson 12',
    summary: "Mademoiselle Fuyutsuki est épiée dans ses moindres faits et gestes dans l'ombre par Teshigawara, un professeur de mathématiques sortant de l'université de Tokyo. Il a pour objectif de construire sa vie avec elle, et élabore un plan pour tenter une approche progressive visant à nouer des premières relations avec elle. Il apprend qu'elle recherche un ordinateur personnel pour ses travaux, il voit là une excellente occasion pour mettre à exécution la première phase de son plan.",
    type: 'Shonen',
    picture: '../assets/greatTeacherOnizuka/012.jpeg',
    created: new Date('31 octobre 1999'),
    link1: '//ok.ru/videoembed/852892387890',
    link2: '',
    link3: '',
  },
  {
    episode: 13,
    season: 1,
    title : 'Lesson 13',
    summary: "Teshigawara donne des cours particuliers à la fille de Madame Ota, qui est la présidente de la société de l'Etude des Représailles dans l'Education. Il veut se servir de cette dernière pour faire renvoyer Onizuka en lui faisant part d'une rumeur comme quoi un ancien délinquant serait devenu enseignant. C'est en compagnie de ses conseillers que Madame Ota décide d'aller observer un cours dispensé par Onizuka...",
    type: 'Shonen',
    picture: '../assets/greatTeacherOnizuka/013.jpeg',
    created: new Date('21 novembre 1999'),
    link1: '//ok.ru/videoembed/852892453426',
    link2: '',
    link3: '',
  },
  {
    episode: 14,
    season: 1,
    title : 'Lesson 14',
    summary: "Après la visite de Madame Ota, Onizuka n'était pas loin du renvoi, mais on lui accorde un dernier recours pour rester enseignant, participer à l'examen du Togaku en même temps que ses élèves et se positionner major de la promotion. Pour l'aider dans ses travaux de révisions, Mademoiselle Fuyutsuki lui propose de l'héberger chez elle durant la semaine pour y suivre un programme très intensif de remise à niveau...",
    type: 'Shonen',
    picture: '../assets/greatTeacherOnizuka/014.jpeg',
    created: new Date('5 décembre 1999'),
    link1: '//ok.ru/videoembed/951603497517',
    link2: '',
    link3: '',
  },
  {
    episode: 15,
    season: 1,
    title : 'Lesson 15',
    summary: "Alors qu'il doit passer un examen important pour assurer sa carrière de professeur, Onizuka est témoin de l'enlèvement de la fille d'un député. Malgré les efforts qu'il a fournis pour se remettre à niveau, il décide tout de même de partir à sa rescousse et fini par tomber dans le repaire des ravisseurs. Ces derniers n'ont pas l'air commodes, et veulent faire pression sur le père de la jeune fille compte tenu de sa position politique.",
    type: 'Shonen',
    picture: '../assets/greatTeacherOnizuka/015.jpeg',
    created: new Date('12 décembre 1999'),
    link1: '//ok.ru/videoembed/951603694125',
    link2: '',
    link3: '',
  },
  {
    episode: 16,
    season: 1,
    title : 'Lesson 16',
    summary: "À la demande de Miyabi et de ses amies, la ravissante mais non moins dangereuse Urumi Kanzaki décide à son tour d'entrer en scène pour renvoyer Onizuka. Elle est réputée pour son tristement célèbre terrorisme scolaire, mettant à mal de nombreux professeurs sans jamais laisser de preuves derrière elle pour l'accuser... Et l'approcher n'est pas une mince affaire, c'est une surdouée protégée par l'éducation...",
    type: 'Shonen',
    picture: '../assets/greatTeacherOnizuka/016.jpeg',
    created: new Date('19 décembre 1999'),
    link1: '//ok.ru/videoembed/852892650034',
    link2: '',
    link3: '',
  },
  {
    episode: 17,
    season: 1,
    title : 'Lesson 17',
    summary: "Kanzaki continue à mener la vie dure à tous ses professeurs, laissant ces derniers hautement dépressifs. Excédé par ses procédés, Onizuka décide de prendre les choses en main et veut régler une bonne fois pour toute le compte de cette turbulente élève malgré le statut spécial de Kanzaki, mais le sous-directeur veille toujours à sa protection. Plus tard, Onizuka apprend de ses élèves que son comportement est dû à terrible traumatisme qu'elle a vécu étant jeune.",
    type: 'Shonen',
    picture: '../assets/greatTeacherOnizuka/017.jpeg',
    created: new Date('16 janvier 2000'),
    link1: '//ok.ru/videoembed/852892781106',
    link2: '',
    link3: '',
  },
  {
    episode: 18,
    season: 1,
    title : 'Lesson 18',
    summary: "Après la tentative d'Onizuka d'enterrer Kanzaki vivante suite à une chute du toit d'un immeuble, ce dernier est contraint et forcé de céder à tous ses désirs comme un esclave... L'une des requêtes de Kanzaki consiste à lui ramener de véritables sushis Oh-Toro... Malgré sa situation financière, Onizuka n'a pas d'autre choix que de céder à toutes ses exigences s'il ne veut pas se retrouver en prison pour tentative d'homicide...",
    type: 'Shonen',
    picture: '../assets/greatTeacherOnizuka/018.jpeg',
    created: new Date('23 janvier 2000'),
    link1: '//ok.ru/videoembed/852893436466',
    link2: '',
    link3: '',
  },
  {
    episode: 19,
    season: 1,
    title : 'Lesson 19',
    summary: "Onizuka et ses élèves décident de rendre une visite à l'ancien professeur de Kanzaki, Mademoiselle Fujimori, à l'origine du changement de comportement de Kanzaki. Après avoir entendu toute l'histoire depuis le début, Onizuka décide alors de dispenser à Kanzaki une leçon 'spéciale' dans l'espoir de lui faire ouvrir les yeux",
    type: 'Shonen',
    picture: '../assets/greatTeacherOnizuka/019.jpeg',
    created: new Date('30 janvier 2000'),
    link1: '//ok.ru/videoembed/852893567538',
    link2: '',
    link3: '',
  },
  {
    episode: 20,
    season: 1,
    title : 'Lesson 20',
    summary: "Murai vient de recevoir une lettre d'amour d'une certaine F... Il cherche alors désespérément à savoir qui cette fille peut bien être, alors qu'Onizuka fait tout pour qu'il ne trouve pas (il veut pas que Murai ai une copine avant lui). Kujirakawa, une élève de la 3è-2, vient alors voir Murai ...",
    type: 'Shonen',
    picture: '../assets/greatTeacherOnizuka/020.jpeg',
    created: new Date('6 février 2000'),
    link1: '//ok.ru/videoembed/852893895218',
    link2: '',
    link3: '',
  },
  {
    episode: 21,
    season: 1,
    title : 'Lesson 21',
    summary: "Mademoiselle Fuyutsuki fait l'objet d'une grande admiration de la part de ses élèves masculins, ce qui a pour effet d'agacer au plus haut point les élèves du sexe opposé qui décident alors en guise de représailles de boycotter ses cours et de lui rendre la vie impossible en lui jouant de très mauvais tours. Mais face aux attaques répétées à son encontre, elle finit par craquer et s'enfuit sans prévenir personne...",
    type: 'Shonen',
    picture: '../assets/greatTeacherOnizuka/021.jpeg',
    created: new Date('13 février 2000'),
    link1: '//ok.ru/videoembed/852894288434',
    link2: '',
    link3: '',
  },
  {
    episode: 22,
    season: 1,
    title : 'Lesson 22',
    summary: "Délaissée par un professeur en qui elle avait entièrement confiance, la jeune Hitomi a commencé à détester tous les professeurs. Malgré la main tendue par Mademoiselle Fuyutsuki avec qui elle s'entendait pourtant bien par le passé, elle continue à ne pas se laisser approcher par un professeur. Onizuka va tenter avec ses méthodes bien particulières de la raisonner.",
    type: 'Shonen',
    picture: '../assets/greatTeacherOnizuka/022.jpeg',
    created: new Date('20 février 2000'),
    link1: '//ok.ru/videoembed/852894353970',
    link2: '',
    link3: '',
  },
  {
    episode: 23,
    season: 1,
    title : 'Lesson 23',
    summary: "Onizuka reçoit un carton complet de lettres de malédiction, stipulant que si la chaîne est brisée, des malheurs voire même la mort attendraient celui qui ne les renverrait pas à d'autres destinataires. Incrédule, il les brûle sans y prêter aucune considération. Depuis lors, il ne cesse d'être victime de drôles de coïncidences, échappant à maintes reprises à la mort...",
    type: 'Shonen',
    picture: '../assets/greatTeacherOnizuka/023.jpeg',
    created: new Date('27 février 2000'),
    link1: '//ok.ru/videoembed/852894878258',
    link2: '',
    link3: '',
  },
  {
    episode: 24,
    season: 1,
    title : 'Lesson 24',
    summary: "Hiroshi Uchiyamada, 51 ans, sous-directeur au lycée 'Seirin', est souvent angoissé par son travail. Le seul endroit où il se sent à l'aise, c'est chez lui. Mais récemment, Onizuka est devenu le professeur particulier de sa fille, jusqu'au jour où une photo compromettante de ce dernier déchaîne la colère de Hiroshi.",
    type: 'Shonen',
    picture: '../assets/greatTeacherOnizuka/024.jpeg',
    created: new Date('5 mars 2000'),
    link1: '//ok.ru/videoembed/852895009330',
    link2: '',
    link3: '',
  },
  {
    episode: 25,
    season: 1,
    title : 'Lesson 25',
    summary: "Hiroshi Uchiyamada, 51 ans, sous-directeur au lycée 'Seirin', est souvent angoissé par son travail. Le seul endroit où il se sent à l'aise, c'est chez lui. Mais récemment, Onizuka est devenu le professeur particulier de sa fille, jusqu'au jour où une photo compromettante de ce dernier déchaîne la colère de Hiroshi.",
    type: 'Shonen',
    picture: '../assets/greatTeacherOnizuka/025.jpeg',
    created: new Date('12 mars 2000'),
    link1: '//ok.ru/videoembed/852895140402',
    link2: '',
    link3: '',
  },
  {
    episode: 26,
    season: 1,
    title : 'Lesson 26',
    summary: "La vérité éclate : l'argent que gagnait Nao avec ce qu'elle vendait aux lycéens avait pour but de financer une opération chirurgicale pour son frère. Évidemment, lorsque le sous-directeur apprend cela, il entre dans une colère noire et comble de malchance pour Nao, il semble qu'elle trempe également dans une affaire de fraude.",
    type: 'Shonen',
    picture: '../assets/greatTeacherOnizuka/026.jpeg',
    created: new Date('12 mars 2000'),
    link1: '//ok.ru/videoembed/852895402546',
    link2: '',
    link3: '',
  },
  {
    episode: 27,
    season: 1,
    title : 'Lesson 27',
    summary: "Toroko, devenue star, va participer au dernier feuilleton du moment. Cependant, l'égoïsme du scénariste fait que son temps d'apparition se réduit petit à petit. Onizuka décide alors de prendre les choses en main et de s'occuper personnellement du management de Toroko.",
    type: 'Shonen',
    picture: '../assets/greatTeacherOnizuka/027.jpeg',
    created: new Date('2 avril 2000'),
    link1: '//ok.ru/videoembed/852895533618',
    link2: '',
    link3: '',
  },
  {
    episode: 28,
    season: 1,
    title : 'Lesson 28',
    summary: "Participant à un concours, Toroko ignore à quel point ses rivales sont redoutables, et malgré tous les efforts d'Onizuka, il semble que le comptage des bulletins de votes soit truqué. De plus, son adresse est publiée dans un magasine dédié aux fans, et son maillot de bain pour la séance de photos a disparu. Les ennuis s'enchaînent et ne font que commencer.",
    type: 'Shonen',
    picture: '../assets/greatTeacherOnizuka/028.jpeg',
    created: new Date('16 avril 2000'),
    link1: '//ok.ru/videoembed/952369547821',
    link2: '',
    link3: '',
  },
  {
    episode: 29,
    season: 1,
    title : 'Lesson 29',
    summary: "Toute la classe s'est ralliée à Onizuka, sauf Miyabi qui est décidée plus que jamais à le faire virer.Seule elle n'a aucune chance alors elle va s'allier à Sakurada. Ce dernier va demander à Fujiyoshi de réunir l'argent de la sortie scolaire en liquide, soit 1.120.000 yen (plus de 10.000 €)",
    type: 'Shonen',
    picture: '../assets/greatTeacherOnizuka/029.jpeg',
    created: new Date('23 avril 2000'),
    link1: '//ok.ru/videoembed/852895730226',
    link2: '',
    link3: '',
  },
  {
    episode: 30,
    season: 1,
    title : 'Lesson 30',
    summary: "Fujiyoshi s'est acheté une montre avec l'argent de la sortie et a perdu le reste ! Alors que toute la classe est contre lui, Onizuka se rend compte que cet argent c'est celui qui l'a dépensé la veille. C'est alors que Murai reçoit une lettre de Fujiyoshi disant qu'il a décidé de se suicider. Onizuka se sent tellement fautif qu'il se met à sa recherche sans prendre le temps de souffler un moment.",
    type: 'Shonen',
    picture: '../assets/greatTeacherOnizuka/030.jpeg',
    created: new Date('30 avril 2000'),
    link1: '//ok.ru/videoembed/852895861298',
    link2: '',
    link3: '',
  },
  {
    episode: 31,
    season: 1,
    title : 'Lesson 31',
    summary: "Pour se faire pardonner, Onizuka a promit à tous les 3è de leurs payer un séjour à Okinawa, la région aux plages de sable fin. Le petit problème c'est ... qu'il n'a pas l'argent. Son pote Saejima l'a escroqué en lui refourguant un faux ticket gagnant de loto donc il doit trouver 8 millions de Yen en une semaine. Ça s'annonce plutôt mal !",
    type: 'Shonen',
    picture: '../assets/greatTeacherOnizuka/031.jpeg',
    created: new Date('7 mai 2000'),
    link1: '//ok.ru/videoembed/952369613357',
    link2: '',
    link3: '',
  },
  {
    episode: 32,
    season: 1,
    title : 'Lesson 32',
    summary: "On dirait bien que la chance est au rendez-vous pour Onizuka, il a gagné le gros lot à la loterie : une Mercedes. Il ne lui reste plus qu'à la vendre pour pouvoir payer la sortie à Okinawa. Mais Miyabi ne s'avoue pas vaincue pour autant car elle prévoie de récupérer la voiture avant qu'Onizuka l'a vende. Ce dernier va-t-il tomber dans le piège ?",
    type: 'Shonen',
    picture: '../assets/greatTeacherOnizuka/032.jpeg',
    created: new Date('14 mai 2000'),
    link1: '//ok.ru/videoembed/852896188978',
    link2: '',
    link3: '',
  },
  {
    episode: 33,
    season: 1,
    title : 'Lesson 33',
    summary: "Urumi, qui n'a pas digéré le coup de la Mercedes, décide d'employer les grands moyens. Miyabi et ses copines vont malgré elles aider à récupérer l'argent. Elle va les faire enlever et demander une rançon à leurs parents. Kikuchi ne partage pas le même point de vue qu'Urumi et décide de demander de l'aide à Onizuka.",
    type: 'Shonen',
    picture: '../assets/greatTeacherOnizuka/033.jpeg',
    created: new Date('28 mai 2000'),
    link1: '//ok.ru/videoembed/852896320050',
    link2: '',
    link3: '',
  },
  {
    episode: 34,
    season: 1,
    title : 'Lesson 34',
    summary: "Tomoko est enfin devenu une star, mais son patron l'oblige à faire des photos quasiment nue car il lui manque de l'argent. Après avoir décalqué la tronche aux Yakuzas qui se servaient de Tomoko, Onizuka se réfugie chez son 'pote' Saejima avec elle. Mais celui-ci a des emmerdes aussi : il a volé une valise pleine d'or que des Yakuzas veulent s'approprier.",
    type: 'Shonen',
    picture: '../assets/greatTeacherOnizuka/034.jpeg',
    created: new Date('4 juin 2000'),
    link1: '//ok.ru/videoembed/852896385586',
    link2: '',
    link3: '',
  },
  {
    episode: 35,
    season: 1,
    title : 'Lesson 35',
    summary: "La mère de Murai est vraiment attirante et ce dernier commence à se demander pourquoi elle est encore seule. Comme pour répondre à sa question il la voit entrer dans un salon de mariage avec un vieux pas beau. Et depuis, Murai remarque qu'elle a un comportement pour le moins bizarre. Et si elle allait se marier avec le vieux en cachette ?",
    type: 'Shonen',
    picture: '../assets/greatTeacherOnizuka/035.jpeg',
    created: new Date('11 juin 2000'),
    link1: '//ok.ru/videoembed/852896647730',
    link2: '',
    link3: '',
  },
  {
    episode: 36,
    season: 1,
    title : 'Lesson 36',
    summary: "Fuyutsuki se rend compte que pour plaire quand elle sera à Okinawa, il lui faut avoir des gros seins. Le choix du maillot de bain est donc important et il lui faudra compter sur l'aide de Nao pour qu'elle se métamorphose. Le problème c'est qu'il faut savoir s'arrêter au bon moment ...",
    type: 'Shonen',
    picture: '../assets/greatTeacherOnizuka/036.jpeg',
    created: new Date('18 juin 2000'),
    link1: '//ok.ru/videoembed/852896909874',
    link2: '',
    link3: '',
  },
  {
    episode: 37,
    season: 1,
    title : 'Lesson 37',
    summary: "Tous les élèves s'amusent comme des fous pour leur premier jour à Okinawa, sauf Yoshikawa qui est toujours maltraité par Anko et ses copines. Onizuka s'occupe alors de la répartition des chambres et celui-ci se retrouve ... dans la même que celle des 3 filles. Est-ce que Yoshikawa va encore se laisser par ces petites pestes ?",
    type: 'Shonen',
    picture: '../assets/greatTeacherOnizuka/037.jpeg',
    created: new Date('16 juillet 2000'),
    link1: '//ok.ru/videoembed/852897237554',
    link2: '',
    link3: '',
  },
  {
    episode: 38,
    season: 1,
    title : 'Lesson 38',
    summary: "Onizuka découvre qu'un trésor se cacherait dans une île aux environs. Il y emmène alors les 3è-4 pour le trouver, mais sans leurs révéler la vraie raison de leur escapade. Mais Yoshikawa a disparu dans la forêt ainsi que Anko et ses amies. Elles ont décidé de se venger et de le perdre. Mais est-ce vraiment le seul à être perdu ?",
    type: 'Shonen',
    picture: '../assets/greatTeacherOnizuka/038.jpeg',
    created: new Date('30 juillet 2000'),
    link1: '//ok.ru/videoembed/852897303090',
    link2: '',
    link3: '',
  },
  {
    episode: 39,
    season: 1,
    title : 'Lesson 39',
    summary: "Anko s'est fait emporter par le courant et Yoshikawa rassemble tout son courage pour la sauver. Ils se retrouvent alors prit au piège dans une grotte sans moyen de s'échapper. Quand Onizuka l'apprend, il croit que ces deux là ont trouvé le trésor et qu'ils veulent le garder pour eux seuls.",
    type: 'Shonen',
    picture: '../assets/greatTeacherOnizuka/039.jpeg',
    created: new Date('13 août 2000'),
    link1: '//ok.ru/videoembed/852897630770',
    link2: '',
    link3: '',
  },
  {
    episode: 40,
    season: 1,
    title : 'Lesson 40',
    summary: "Anko ressent un sentiment tout nouveau pour elle : son coeur bat très fort en présence de Yoshikawa, et elle n'arrive plus à le martyriser. Pendant ce temps le sous-directeur, qui a echappé de peu à la noyade, recoit la visite d'une élève très troublante ...",
    type: 'Shonen',
    picture: '../assets/greatTeacherOnizuka/040.jpeg',
    created: new Date('20 août 2000'),
    link1: '//ok.ru/videoembed/852897827378',
    link2: '',
    link3: '',
  },
  {
    episode: 41,
    season: 1,
    title : 'Lesson 41',
    summary: "Onizuka décide d'organiser une soirée spéciale 'kimodameshi' (test du courage). Le jeu se déroule en couple et Onizuka désigne Anko comme partenaire pour Yoshikawa. Ces deux là commencent à se rapprocher et tout va bien jusqu'au moment où ils rencontrent un groupe de voyous ...",
    type: 'Shonen',
    picture: '../assets/greatTeacherOnizuka/041.jpeg',
    created: new Date('27 août 2000'),
    link1: '//ok.ru/videoembed/852897892914',
    link2: '',
    link3: '',
  },
  {
    episode: 42,
    season: 1,
    title : 'Lesson 42',
    summary: "Miyabi a retrouvé son ancien prof principal, Saito. Ce dernier était sorti avec Mizuki, une ancienne 4è-4 qui s'est suicidée par sa faute. Miyabi a juré de se venger de tous les adultes qui sont responsable dans cette histoire et Saito est la première victime. Onizuka va devoir s'en mêler pour éviter que les problèmes continuent.",
    type: 'Shonen',
    picture: '../assets/greatTeacherOnizuka/042.jpeg',
    created: new Date('10 septembre 2000'),
    link1: '//ok.ru/videoembed/852898023986',
    link2: '',
    link3: '',
  },
  {
    episode: 43,
    season: 1,
    title : 'Lesson 43',
    summary: "Miyabi est accusée par le conseil scolaire d'avoir poignardé le professeur Saito. Onizuka est aussi dans leur ligne de mire et la directrice a grand mal à les convaincre. Mais Onizuka n'est pas du genre à lâcher ses élèves, et même si Miyabi ne l'a jamais considéré comme un prof, il est prêt à en subir les conséquences",
    type: 'Shonen',
    picture: '../assets/greatTeacherOnizuka/043.jpeg',
    created: new Date('17 septembre 2000'),
    link1: '//ok.ru/videoembed/852898155058',
    link2: '',
    link3: '',
  },
]

