import { Anime } from "../modeles/anime";


export const JOJO : Anime[] = [
  {
    episode: 1,
    season: 1,
    title : "Dio l'envahisseur",
    summary: "Jonathan Joestar, Jojo de son surnom, est un adolescent qui vit avec son père, Joseph Joestar. Courageux et bienveillant, Jojo fait la rencontre de son nouveau demi-frère, Dio Brando, qui vient vivre avec eux suite à la mort de Dario Brando, son paternel. Dès son arrivée, Dio met à exécution quelques-uns de ses plans machiavéliques pour nuire à Jojo et à sa réputation.",
    type: 'Shonen',
    picture: '../assets/jojo/001.jpeg',
    created: new Date('5 octobre 2012'),
    link1: '//sendvid.com/embed/nzcik4dw',
    link2: '',
    link3: '',
  },
  {
    episode: 2,
    season: 1,
    title : "Une lettre du passé",
    summary: "Sept ans plus tard, Jonathan et Dio sont tous les deux sur le point d'obtenir leur diplôme. En apparence, ils semblent s'être réconciliés, mais la réalité est tout autre. Dio est sur le point de réaliser un de ses objectifs premiers : tuer le père de Jonathan Joestar pour récupérer sa fortune. Grâce à une lettre retrouvée, Jonathan découvre la terrible vérité et tente ensuite de contrecarrer les plans de son demi-frère.",
    type: 'Shonen',
    picture: '../assets/jojo/002.jpeg',
    created: new Date('12 octobre 2012'),
    link1: '//sendvid.com/embed/h8e472zk',
    link2: '',
    link3: '',
  },
  {
    episode: 3,
    season: 1,
    title : "Adolescence avec Dio",
    summary: "Jonathan a réussi à se procurer un antidote pour son père, même au péril de sa vie, et revient lui donner. Affecté par le complot maléfique de Dio, il tente de l'arrêter mais n'y parvient pas, car Dio use du masque de pierre pour s'échapper !",
    type: 'Shonen',
    picture: '../assets/jojo/003.jpeg',
    created: new Date('19 octobre 2012'),
    link1: '//sendvid.com/embed/0n4amf5q',
    link2: '',
    link3: '',
  },
  {
    episode: 4,
    season: 1,
    title : "Overdrive",
    summary: "Jonathan doit trouver le moyen d'arrêter Dio, mais il est gravement blessé par son précédent combat contre lui. Dio se révèle être un redoutable adversaire depuis qu'il est en possession du masque de pierre. Heureusement, Erina est venue prendre soin de Jojo et à deux, ils feront la rencontre du mystérieux Baron Zeppeli, futur professeur pour l'enseignement des ondes, autrement dit l'Overdrive. Jonathan suivra assidûment ses directives.",
    type: 'Shonen',
    picture: '../assets/jojo/004.jpeg',
    created: new Date('26 octobre 2012'),
    link1: '//sendvid.com/embed/sdx695i7',
    link2: '',
    link3: '',
  },
  {
    episode: 5,
    season: 1,
    title : "Chevaliers des ténèbres",
    summary: "Jonathan, accompagné de Speedwagon et du Baron Zeppeli, se rend dans une petite ville du nom de Wind Knights Lot, où il pense trouver Dio qui continue de prendre la fuite. Ils se feront piéger, mais ce piège les conduira jusqu'à Dio qui les attend de pied ferme avec ses chevaliers, et ce pour des combats sans merci.",
    type: 'Shonen',
    picture: '../assets/jojo/005.jpeg',
    created: new Date('2 novembre 2012'),
    link1: '//sendvid.com/embed/0vdc1ihb',
    link2: '',
    link3: '',
  },
  {
    episode: 6,
    season: 1,
    title : "Courage du lendemain",
    summary: "Le combat contre le chevalier noir Blueford se poursuit ! Tarukus est également prêt à prendre la relève à tout moment. Jojo n'est visiblement pas au bout de ses peines, surtout que Dio s'est une fois de plus échappé, laissant le sale travail à ses acolytes !",
    type: 'Shonen',
    picture: '../assets/jojo/006.jpeg',
    created: new Date('9 novembre 2012'),
    link1: '//sendvid.com/embed/2nrpnf8j',
    link2: '',
    link3: '',
  },
  {
    episode: 7,
    season: 1,
    title : "Le successeur",
    summary: "Grâce à Poco, le Baron Zeppeli peut aller secourir Jojo, qui est enchaîné et pris au piège. Contre lui, Tarukus est déchaîné et ne fait preuve d'aucune pitié. Le Baron Zeppeli fera face à son tragique destin afin de sauver Jojo.",
    type: 'Shonen',
    picture: '../assets/jojo/007.jpeg',
    created: new Date('16 novembre 2012'),
    link1: '//sendvid.com/embed/zrlwawq4',
    link2: '',
    link3: '',
  },
  {
    episode: 8,
    season: 1,
    title : "Le combat sanglant ! JoJo et Dio",
    summary: "Désormais en possession de l'énergie vitale du Baron Zeppeli, Jojo est plus puissant que jamais et va sans crainte à la rencontre de Dio. Ce face-à-face les conduit à nouveau dans une bataille sanglante, où Dio fait tout pour transformer Jojo en un de ses serviteurs.",
    type: 'Shonen',
    picture: '../assets/jojo/008.jpeg',
    created: new Date('23 novembre 2012'),
    link1: '//sendvid.com/embed/hvo5b3u7',
    link2: '',
    link3: '',
  },
  {
    episode: 9,
    season: 1,
    title : "La dernière Onde !",
    summary: "Erina et Jojo se marient et sont heureux. Leur lune de miel les fait s'éloigner de leurs amis. Ce voyage en bateau couvre un dénouement tragique où sang et morts sont au rendez-vous...",
    type: 'Shonen',
    picture: '../assets/jojo/009.jpeg',
    created: new Date('30 novembre 2012'),
    link1: '//sendvid.com/embed/3ckv9fzn',
    link2: '',
    link3: '',
  },
  {
    episode: 10,
    season: 1,
    title : "Jojo de New York",
    summary: "49 ans après la mort de Jonathan, on retrouve son petit-fils, Joseph Joestar, à New York. Tout comme ses aïeuls, Joseph a de la gueule et sait se faire entendre ! Il fera très vite la connaissance de Smokey, un petit voleur à la recherche de pigeons !",
    type: 'Shonen',
    picture: '../assets/jojo/010.jpeg',
    created: new Date('7 décembre 2012'),
    link1: '//sendvid.com/embed/nrvcbkj9',
    link2: '',
    link3: '',
  },
  {
    episode: 11,
    season: 1,
    title : "Le virtuose du jeu",
    summary: "Straizo est bel et bien de retour, mais n'est plus le valeureux moine d'autrefois. Des rayons à haute pression, une jolie femme en détresse, une molaire arrachée, Straizo provoque habilement Joseph Joestar. Mission accomplie, Jojo s'engage dans un autre combat à mort contre lui où il devra faire preuve d'imagination pour ne pas périr maladroitement.",
    type: 'Shonen',
    picture: '../assets/jojo/011.jpeg',
    created: new Date('14 décembre 2012'),
    link1: 'https://uqload.org/embed-8afu41ez32dh.html',
    link2: '',
    link3: '',
  },
  {
    episode: 12,
    season: 1,
    title : "L'homme du pilier",
    summary: "Après avoir obtenu de précieuses informations de Straizo, Jojo se rend à moto au Mexique pour retrouver Speedwagon et le ramener, sain et sauf. C'est là qu'il fera la rencontre de l'homme du pilier...",
    type: 'Shonen',
    picture: '../assets/jojo/012.jpeg',
    created: new Date('21 décembre 2012'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 13,
    season: 1,
    title : "Jojo contre la créature ultime",
    summary: "Santviento, l'homme du pilier, est désormais une menace, et Jojo doit l'éliminer avant qu'il ne s'enfuie du laboratoire allemand. Avec l'aide de Stroheim, ils feront tout ce qu'ils peuvent pour l'arrêter.",
    type: 'Shonen',
    picture: '../assets/jojo/013.jpeg',
    created: new Date('4 janvier 2013'),
    link1: '//uqload.org/embed-rkf6kh0yohir.html',
    link2: '',
    link3: '',
  },
  {
    episode: 14,
    season: 1,
    title : "Guerriers d'élite ancestraux",
    summary: "Nouvellement arrivé à Rome, Jojo recherche un homme de la lignée du Baron Zeppeli, un certain Caesar. Il détient des informations vitales et maîtrise suffisamment les ondes pour pouvoir arrêter les hommes du pilier. Mais quand Jojo découvrira quel genre de personnalité Caesar Zeppeli affiche...",
    type: 'Shonen',
    picture: '../assets/jojo/014.jpeg',
    created: new Date('11 janvier 2013'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 15,
    season: 1,
    title : "L'aptitude des héros",
    summary: "Trois nouveaux hommes du pilier se sont réveillés, confirmant ainsi les dires de Stroheim. Caesar et Jojo tentent de les affronter. Jojo en profite aussi pour révéler sa nouvelle technique spéciale !",
    type: 'Shonen',
    picture: '../assets/jojo/015.jpeg',
    created: new Date('18 janvier 2013'),
    link1: 'https://uqload.org/embed-sslmxirjco2m.html',
    link2: '',
    link3: '',
  },
  {
    episode: 16,
    season: 1,
    title : "Lisa Lisa, coach de l'onde",
    summary: "Jojo est désormais pris au dépourvu avec deux anneaux mortels qui vont se dissoudre dans un mois. En compagnie de Caesar, il ira à Venise faire la rencontre de Lisa Lisa, son futur maître, qui va l'aider à se sortir de ce pétrin !",
    type: 'Shonen',
    picture: '../assets/jojo/016.jpeg',
    created: new Date('25 janvier 2013'),
    link1: 'https://uqload.org/embed-za090mngm3az.html',
    link2: '',
    link3: '',
  },
  {
    episode: 17,
    season: 1,
    title : "Le piège parfait !",
    summary: "Convoitant ardemment la Pierre Rouge, Esidisi se rend jusqu'à l'île Air Supplena. L'ultime épreuve que Jojo devait passer se retrouve transformée en combat bouillant contre cet homme du pilier ! Loin d'être à court d'idées, Jojo trouvera des stratagèmes brillants afin de le combattre.",
    type: 'Shonen',
    picture: '../assets/jojo/017.jpeg',
    created: new Date('1er février 2013'),
    link1: 'https://uqload.org/embed-9z1gvq398fzn.html',
    link2: '',
    link3: '',
  },
  {
    episode: 18,
    season: 1,
    title : "Stroheim contre-attaque !",
    summary: "Esidisi n'a toujours pas rendu l'âme, s'accrochant difficilement à la vie, sous forme de cerveau et de veines. Jojo, qui croyait s'en être débarrassé, sera surpris de découvrir sa nouvelle technique de possession.",
    type: 'Shonen',
    picture: '../assets/jojo/018.jpeg',
    created: new Date('8 février 2013'),
    link1: 'https://uqload.org/embed-m59ucg1hep1i.html',
    link2: '',
    link3: '',
  },
  {
    episode: 19,
    season: 1,
    title : "Ruée vers la falaise de la mort",
    summary: "Une fois arrivé à Saint-Moritz, le groupe de lanceurs d'ondes avait été intercepté par l'armée allemande et se rendit dans leur chalet, non loin de la frontière entre la Suisse et l'Italie. Stroheim avait prévu de les interroger, mais Kars était déjà sur place. Le commandant allemand, une machine de guerre démontrant tout le potentiel de la science de sa patrie, engage maintenant Kars en combat.",
    type: 'Shonen',
    picture: '../assets/jojo/019.jpeg',
    created: new Date('15 février 2013'),
    link1: 'https://uqload.org/embed-bjd1aexb5bm8.html',
    link2: '',
    link3: '',
  },
  {
    episode: 20,
    season: 1,
    title : "La jeunesse solitaire de Caesar",
    summary: "Le retour d'un passé douloureux a enflammé Caesar, qui se rend seul au château où sont possiblement cachés Kars et Wamuu. Il a en tête de relâcher la rage qui l'habite sur eux.",
    type: 'Shonen',
    picture: '../assets/jojo/020.jpeg',
    created: new Date('22 février 2013'),
    link1: 'https://uqload.org/embed-8mr4ruy3m7fx.html',
    link2: '',
    link3: '',
  },
  {
    episode: 21,
    season: 1,
    title : "Cent contre Deux",
    summary: "Caesar a vaillamment donné sa vie pour affaiblir Wamuu et lui dérober le dernier anneau qui sauvera Jojo. Cela ne laissera toutefois pas indifférents Jojo et Lisa Lisa qui ont découvert, à retardement, la mort de leur ami. Ils se dirigent droit au cœur du château pour venger Caesar.",
    type: 'Shonen',
    picture: '../assets/jojo/021.jpeg',
    created: new Date('1er mars 2013'),
    link1: 'https://uqload.org/embed-9g92njn4thyq.html',
    link2: '',
    link3: '',
  },
  {
    episode: 22,
    season: 1,
    title : "Un véritable guerrier !",
    summary: "La vengeance est reportée au pied du Piz Bernina, à 15 kilomètres au sud-est du château. Jojo affrontera Wamuu en un contre un, et Lisa Lisa se chargera de Kars par la suite. Des combats effrénés pour la Pierre Rouge !",
    type: 'Shonen',
    picture: '../assets/jojo/022.jpeg',
    created: new Date('8 mars 2013'),
    link1: 'https://uqload.org/embed-w7n7v6pq8gjv.html',
    link2: '',
    link3: '',
  },
  {
    episode: 23,
    season: 1,
    title : "Le guerrier emporté par le vent",
    summary: "Le combat entre Wamuu et Jojo se poursuit, empli de rebondissements. Le valeureux guerrier qu'est Wamuu ne fera pas de cadeau, son pouvoir du vent est redoutable.",
    type: 'Shonen',
    picture: '../assets/jojo/023.jpeg',
    created: new Date('15 mars 2013'),
    link1: 'https://uqload.org/embed-gtg7pqrhdy3s.html',
    link2: '',
    link3: '',
  },
  {
    episode: 24,
    season: 1,
    title : "Les liens qui unissent Jojo",
    summary: "Jojo est ignorant de la vérité concernant son lien avec Lisa Lisa, mais il fera tout pour la sauver, elle qui est blessée et pendue par les pieds. Il usera à nouveau d'une stratégie des plus originales pour les sortir de ce pétrin.",
    type: 'Shonen',
    picture: '../assets/jojo/024.jpeg',
    created: new Date('22 mars 2013'),
    link1: 'https://uqload.org/embed-0te4kxw0qo76.html',
    link2: '',
    link3: '',
  },
  {
    episode: 25,
    season: 1,
    title : "La naissance de l'être suprême",
    summary: "La créature ultime, Kars, naît ! Il résiste désormais aux rayons du soleil, il peut manipuler la vie à loisir, plus rien ne l'arrêtera. C'est du moins ce qu'il croit...",
    type: 'Shonen',
    picture: '../assets/jojo/025.jpeg',
    created: new Date('29 mars 2013'),
    link1: 'https://uqload.org/embed-dd5pek9mr8yr.html',
    link2: '',
    link3: '',
  },
  {
    episode: 26,
    season: 1,
    title : "L'homme qui devint un Dieu",
    summary: "Kars est le dernier homme du pilier à vaincre avant la victoire des lanceurs d'ondes et le retour à la normale pour la famille Joestar. Jojo sera sans pitié !",
    type: 'Shonen',
    picture: '../assets/jojo/026.jpeg',
    created: new Date('5 avril 2013'),
    link1: 'https://uqload.org/embed-z3yl6fcv0roq.html',
    link2: '',
    link3: '',
  },
  {
    episode: 1,
    season: 2,
    title : "Le possédé",
    summary: "Jotaro Kujo, 17 ans, 1,95 m, bien que lycéen, issu d'une famille assez spéciale, se découvre un pouvoir, appelé « Stand ». Son papy vient lui rendre visite pour lui expliquer de quoi il retourne.",
    type: 'Shonen',
    picture: '../assets/jojo/s2001.png',
    created: new Date('4 avril 2014'),
    link1: 'https://uqload.org/embed-psz0cfkgvs30.html',
    link2: '',
    link3: '',
  },
  {
    episode: 2,
    season: 2,
    title : "Qui rendra le jugement ?",
    summary: "Noriaki Kakyoin, un jeune peintre, se présente à Jotaro. Il semble bien présomptueux… Qui peut bien se cacher derrière ce jeune homme qui vient de rejoindre le lycée de Jotaro ? ",
    type: 'Shonen',
    picture: '../assets/jojo/s2002.png',
    created: new Date('11 avril 2014'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 3,
    season: 2,
    title : "Le maléfice de Dio",
    summary: "Alors que Noriaki Kakyoin est maîtrisé, ils découvrent un bourgeon de chair qui permettrait à Dio de le manipuler. Comment a-t-il été infecté ? Et qu’en est-il de toute la famille Joestar ?",
    type: 'Shonen',
    picture: '../assets/jojo/s2003.jpeg',
    created: new Date('18 avril 2014'),
    link1: 'https://uqload.org/embed-l1uq2prrlfr7.html',
    link2: '',
    link3: '',
  },
  {
    episode: 4,
    season: 2,
    title : "Tower of Gray",
    summary: "En route vers l’Égypte, nos compagnons vont avoir une drôle de surprise dans l’avion censé les mener à destination. Quel est donc cet insecte qui vole autour des passagers ?",
    type: 'Shonen',
    picture: '../assets/jojo/s2004.jpeg',
    created: new Date('25 avril 2014'),
    link1: 'https://uqload.org/embed-w5f02t3u75aa.html',
    link2: '',
    link3: '',
  },
  {
    episode: 5,
    season: 2,
    title : "Silver Chariot",
    summary: "Alors qu’ils avaient invité quelqu’un à leur table, ce dernier nous dévoile son jeu. Polnareff s’avère être un autre sbire de Dio. Comment se finira le duel entre Polnareff et Avdol ?",
    type: 'Shonen',
    picture: '../assets/jojo/s2005.jpeg',
    created: new Date('2 mai 2014'),
    link1: 'https://uqload.org/embed-ankx7yd6yt7p.html',
    link2: '',
    link3: '',
  },
  {
    episode: 6,
    season: 2,
    title : "Dark Blue Moon",
    summary: "De nouveau en route pour l’Égypte, notre équipe fait voyage en bateau. Alors qu’ils mettent la main sur passager clandestin, un nouveau Stand surgit. Qui se cache donc derrière ?",
    type: 'Shonen',
    picture: '../assets/jojo/s2006.jpeg',
    created: new Date('9 mai 2014'),
    link1: 'https://uqload.org/embed-ej1i6gkgw8ap.html',
    link2: '',
    link3: '',
  },
  {
    episode: 7,
    season: 2,
    title : "Strength",
    summary: "Alors que Jojo et ses compagnons sont en pleine mer, ils découvrent un paquebot qui semble abandonné. Ils vont tenter de trouver le capitaine du navire pour pouvoir naviguer vers leur destination, l’Égypte.",
    type: 'Shonen',
    picture: '../assets/jojo/s2007.jpeg',
    created: new Date('16 Mai 2014'),
    link1: 'https://uqload.org/embed-gjg1hyptixf5.html',
    link2: '',
    link3: '',
  },
  {
    episode: 8,
    season: 2,
    title : "Devil",
    summary: "Nos héros vont enfin pouvoir se relaxer dans un hôtel, suite à toutes leurs mésaventures. Enfin, c’est ce qu’ils espèrent…",
    type: 'Shonen',
    picture: '../assets/jojo/s2008.jpeg',
    created: new Date('23 Mai 2014'),
    link1: 'https://uqload.org/embed-kuk1is2c2hcl.html',
    link2: '',
    link3: '',
  },
  {
    episode: 9,
    season: 2,
    title : "Yellow Temperance",
    summary: "Alors qu’ils pensaient que Kakyoin était devenu l’un des leurs, celui-ci dévoile enfin son vrai jeu. Qu’a-t-il pu bien pu lui arriver ? Anne et Jojo tentent de le découvrir…",
    type: 'Shonen',
    picture: '../assets/jojo/s2009.jpeg',
    created: new Date('30 mai 2014'),
    link1: 'https://uqload.org/embed-ofbmdxrwrzw1.html',
    link2: '',
    link3: '',
  },
  {
    episode: 10,
    season: 2,
    title : "Emperor et Hanged Man, Partie 1",
    summary: "Après une multitude de péripéties, nos amis arrivent enfin à Calcutta, et découvrent ainsi l’Inde. Polnareff, quant à lui, va croiser le chemin d’un ennemi qui fera ressurgir son passé.",
    type: 'Shonen',
    picture: '../assets/jojo/s2010.png',
    created: new Date('6 Juin 2014'),
    link1: 'https://uqload.org/embed-s5l7egk43i26.html',
    link2: '',
    link3: '',
  },
  {
    episode: 11,
    season: 2,
    title : "Emperor et Hanged Man, Partie 2",
    summary: "Polnareff et Kakyoin vont devoir faire face à l’ennemi juré de Polnareff, l’homme aux deux mains droites. Mais où se cache-t-il, et quel est le point faible de ce Stand, qui n’apparaît que dans les miroirs ?",
    type: 'Shonen',
    picture: '../assets/jojo/s2011.jpeg',
    created: new Date('13 Juin 2014'),
    link1: 'https://uqload.org/embed-25rpmnz5aesx.html',
    link2: '',
    link3: '',
  },
  {
    episode: 12,
    season: 2,
    title : "Empress",
    summary: "Cette fois, c’est Joseph Joestar qui est pris pour cible. L’infection qu’il a au bras ne semble pas anodine. L’hôpital où il se rendra sera-t-il suffisant pour s’en débarrasser ?",
    type: 'Shonen',
    picture: '../assets/jojo/s2012.jpeg',
    created: new Date('20 Juin 2014'),
    link1: 'https://uqload.org/embed-r3murhqy75az.html',
    link2: '',
    link3: '',
  },
  {
    episode: 13,
    season: 2,
    title : "Wheel of Fortune",
    summary: "Alors qu’ils quittaient l’Inde pour rejoindre le Pakistan, nos amis se sont frottés à un chauffard du dimanche. Polnareff va nous montrer ses talents de pilote, mais son adversaire a l’air plein de ressources. ",
    type: 'Shonen',
    picture: '../assets/jojo/s2013.jpeg',
    created: new Date('27 Juin 2014'),
    link1: 'https://uqload.org/embed-96vh8payhdk6.html',
    link2: '',
    link3: '',
  },
  {
    episode: 14,
    season: 2,
    title : "Justice, Partie 1",
    summary: "Notre fine équipe, continuant sa route dans le désert, n’y voit plus rien à cause d’un épais brouillard. Ils vont alors s’arrêter dans une ville où tous les habitants semblent impassibles.",
    type: 'Shonen',
    picture: '../assets/jojo/s2014.jpeg',
    created: new Date('4 Juillet 2014'),
    link1: 'https://uqload.org/embed-fchpo3wydjpn.html',
    link2: '',
    link3: '',
  },
  {
    episode: 15,
    season: 2,
    title : "Justice, Partie 2",
    summary: "Alors que la vieille Enya tente de se débarrasser du corps de Hol Horse, elle va devoir faire face à Polnareff qui cherchait à savoir d’où venait tout ce grabuge.",
    type: 'Shonen',
    picture: '../assets/jojo/s2015.jpeg',
    created: new Date(' 11 Juillet 2014'),
    link1: 'https://uqload.org/embed-ofbmdxrwrzw1.html',
    link2: '',
    link3: '',
  },
  {
    episode: 16,
    season: 2,
    title : "Lovers, Partie 1",
    summary: "La fine équipe de Jojo arrive enfin à Karachi. Alors qu’ils souhaitent prendre un en-cas, la vieille Enya, qui se réveille enfin, croit reconnaître quelqu’un et prend peur.",
    type: 'Shonen',
    picture: '../assets/jojo/s2016.jpeg',
    created: new Date('18 Juillet 2014'),
    link1: 'https://uqload.org/embed-tybkrppsui8a.html',
    link2: '',
    link3: '',
  },
  {
    episode: 17,
    season: 2,
    title : "Lovers, Partie 2",
    summary: "Alors que Dan of Steel s’en prend à Joseph Joestar, Jojo essaie de le retenir tant bien que mal. Pendant ce temps, Polnareff et Kakyoin tentent de trouver le Stand Lovers de ce dernier.",
    type: 'Shonen',
    picture: '../assets/jojo/s2017.jpeg',
    created: new Date('25 Juillet 2014'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 18,
    season: 2,
    title : "The Sun",
    summary: "Souhaitant éviter l’Iran et l’Irak à cause de l’instabilité politique, nos héros vont tenter une percée à travers le désert. Il ne leur reste qu’à trouver le moyen de transport et à résister à la chaleur. ",
    type: 'Shonen',
    picture: '../assets/jojo/s2018.jpeg',
    created: new Date('1 Août 2014'),
    link1: 'https://uqload.org/embed-tnekajpe76vo.html',
    link2: '',
    link3: '',
  },
  {
    episode: 19,
    season: 2,
    title : "Death 13, Partie 1",
    summary: "Toujours dans le désert saoudien, Jojo et ses compagnons décident d’acheter un avion, suite à la mort des dromadaires. Ils doivent cependant embarquer avec eux un bébé fiévreux afin de le faire soigner. Pendant ce temps, Kakyoin fait de bien étranges rêves…",
    type: 'Shonen',
    picture: '../assets/jojo/s2019.jpeg',
    created: new Date('8 Août 2014'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 20,
    season: 2,
    title : "Death 13, Partie 2",
    summary: "Kakyoin tente vainement de persuader ses compagnons que le bébé est un détenteur de Stand. Pensant qu’il délire, ceux-ci s’endorment sereinement… Cependant, ils comprennent leur erreur en se retrouvant dans le monde des cauchemars, sans personne pour les réveiller…",
    type: 'Shonen',
    picture: '../assets/jojo/s2020.jpeg',
    created: new Date('15 Août 2014'),
    link1: 'https://uqload.org/embed-hrr58vye8nox.html',
    link2: '',
    link3: '',
  },
  {
    episode: 21,
    season: 2,
    title : "Judgement, Partie 1",
    summary: "Joseph Joestar décide de faire un détour par une petite île. Ils y découvrent un habitant qui leur semble familier. En parallèle, Polnareff fait face à une lampe qu’il a trouvé sur la plage.",
    type: 'Shonen',
    picture: '../assets/jojo/s2021.jpeg',
    created: new Date('22 Août 2014'),
    link1: 'https://uqload.org/embed-1qwld5sv1b15.html',
    link2: '',
    link3: '',
  },
  {
    episode: 22,
    season: 2,
    title : "Judgement, Partie 2",
    summary: "Judgement se joue de Polnareff et des êtres chers qu'il a perdus. Alors qu'il s'apprête à abandonner, une chose étrange apparaît devant ses yeux. ",
    type: 'Shonen',
    picture: '../assets/jojo/s2022.jpeg',
    created: new Date('29 Août 2014'),
    link1: 'https://uqload.org/embed-7a1g32udte3o.html',
    link2: '',
    link3: '',
  },
  {
    episode: 23,
    season: 2,
    title : "High Priestess, Partie 1",
    summary: "Après le retour d’Avdol, la troupe au grand complet embarque dans un luxueux sous-marin pour atteindre l’Égypte par la mer Rouge. Mais, alors qu’ils sont presque arrivés, ils subissent une nouvelle attaque de Stand…",
    type: 'Shonen',
    picture: '../assets/jojo/s2023.jpeg',
    created: new Date('5 Septembre 2014'),
    link1: 'https://uqload.org/embed-j3pw4otvmktd.html',
    link2: '',
    link3: '',
  },
  {
    episode: 24,
    season: 2,
    title : "High Priestess, Partie 2",
    summary: "Nos amis sont en bien mauvaise posture, avec leur sous-marin qui prend l’eau. Ils s’équipent donc de bonbonnes d’air pour rejoindre les côtes égyptiennes à la nage. Mais High Priestess n’a pas dit son dernier mot, profitant à chaque fois de l’environnement pour berner ses ennemis.",
    type: 'Shonen',
    picture: '../assets/jojo/s2024.jpeg',
    created: new Date('12 Septembre 2014'),
    link1: 'https://uqload.org/embed-2lap82t5bjl2.html',
    link2: '',
    link3: '',
  },
  {
    episode: 25,
    season: 2,
    title : "Iggy (The Fool) et N’Doul (Geb), Partie 1",
    summary: "En plein milieu du désert, notre fine équipe attend l’arrivée d’un nouvel allié, au caractère quelque peu difficile. Mais ce dernier tombe à pic car une nouvelle menace semble peser sur nos héros. ",
    type: 'Shonen',
    picture: '../assets/jojo/s2025.jpeg',
    created: new Date('9 Janvier 2015'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 26,
    season: 2,
    title : "Iggy (The Fool) et N’Doul (Geb), Partie 2",
    summary: "N’Doul a le dessus sur ses adversaires. Rien ne semble pouvoir arrêter le Stand Geb dans ce désert. Iggy va-t-il changer la donne, face à cette nouvelle menace ?",
    type: 'Shonen',
    picture: '../assets/jojo/s2026.jpeg',
    created: new Date('15 Janvier 2015'),
    link1: 'https://uqload.org/embed-754y21tbp0ej.html',
    link2: '',
    link3: '',
  },
  {
    episode: 27,
    season: 2,
    title : "Oingo (Khnum) et Boingo (Thoth)",
    summary: "À peine remis de leur combat face à N’Doul, nos héros vont croiser le chemin de deux frères, dont les Stands semblent se compléter. Que se cache derrière le manga écrit par l’un d’eux ? Et quel est le secret du Stand du second ?",
    type: 'Shonen',
    picture: '../assets/jojo/s2027.jpeg',
    created: new Date('23 Janvier 2015'),
    link1: 'https://uqload.org/embed-by6664inkra9.html',
    link2: '',
    link3: '',
  },
  {
    episode: 28,
    season: 2,
    title : "Anubis, Partie 1",
    summary: "Un sabre traîne au milieu d’un chemin, mais celui-ci n’est pas si ordinaire qu’il n’y paraît. D’ailleurs, il va croiser le chemin de notre fine équipe…",
    type: 'Shonen',
    picture: '../assets/jojo/s2028.jpeg',
    created: new Date('30 Janvier 2015'),
    link1: 'https://uqload.org/embed-d8tdc18z0qh8.html',
    link2: '',
    link3: '',
  },
  {
    episode: 29,
    season: 2,
    title : "Anubis, Partie 2",
    summary: "Alors qu’ils venaient de vaincre le porteur du sabre, ce dernier a un nouvel hôte, et il semble encore plus puissant. Comment Jotaro et Polnareff vont-ils s’y prendre pour s’en débarrasser ? ",
    type: 'Shonen',
    picture: '../assets/jojo/s2029.jpeg',
    created: new Date('6 Fevrier 2015'),
    link1: 'https://uqload.org/embed-0gas0yft3dlz.html',
    link2: '',
    link3: '',
  },
  {
    episode: 30,
    season: 2,
    title : "Mariah (Bast), Partie 1",
    summary: "Arrivés à Louxor, ancienne capitale de l’Égypte, Kakyoin étant toujours à l’hôpital suite à son précédent combat, nos héros souhaitent s’arrêter pour récupérer un peu. C’était sans compter une nouvelle aventure liée aux toilettes…",
    type: 'Shonen',
    picture: '../assets/jojo/s2030.jpeg',
    created: new Date('13 Fevrier 2015'),
    link1: 'https://uqload.org/embed-uoln3otejxkr.html',
    link2: '',
    link3: '',
  },
  {
    episode: 31,
    season: 2,
    title : "Mariah (Bast), Partie 2",
    summary: "Après avoir fait la rencontre d’une jolie femme, Mariah, nos deux acolytes ont constaté qu’ils s’étaient fait rouler, et s’attirent comme des aimants. Ils tentent de mettre en place un stratagème pour parvenir au bout de ce Stand, mais Mariah est pleine de ressources.",
    type: 'Shonen',
    picture: '../assets/jojo/s2031.jpeg',
    created: new Date('20 Fevrier 2015'),
    link1: 'https://uqload.org/embed-yri8w74f2bi5.html',
    link2: '',
    link3: '',
  },
  {
    episode: 32,
    season: 2,
    title : "Alessi (Sethan), Partie 1",
    summary: "Alors que Joestar et Avdol se démènent contre Mariah, un autre combat prend place entre un nouvel ennemi et Polnareff. Iggy, quant à lui, cherche toujours quelque chose à se mettre sous la dent.",
    type: 'Shonen',
    picture: '../assets/jojo/s2032.jpeg',
    created: new Date('27 Fevrier 2015'),
    link1: 'https://uqload.org/embed-gbwmwmof80y5.html',
    link2: '',
    link3: '',
  },
  {
    episode: 33,
    season: 2,
    title : "Alessi (Sethan), Partie 2",
    summary: "Polnareff, redevenu tout frêle, tente par tous les moyens d’échapper à Sethan, le Stand d’Alessi. Mais ce dernier semble vouloir ne laisser aucune chance à Polnareff… Aura-t-il de l’aide ou s’en sortira-t-il par lui-même ?",
    type: 'Shonen',
    picture: '../assets/jojo/s2033.jpeg',
    created: new Date('6 Mars 2015'),
    link1: 'https://uqload.org/embed-bzpv2qzs0w1g.html',
    link2: '',
    link3: '',
  },
  {
    episode: 34,
    season: 2,
    title : "D’Arby the Gambler, Partie 1",
    summary: "Enfin arrivée au Caire, notre équipe cherche le nouveau repaire de Dio. Ils entrent donc dans un café, aux abords de la ville, afin d'obtenir des informations grâce à la photo du manoir idéographié par Joseph. Ils feront alors la rencontre de D'Arby, un homme mordu des jeux, prêt à leur fournir les informations qu'ils ont besoin à condition qu'ils acceptent de faire une partie.",
    type: 'Shonen',
    picture: '../assets/jojo/s2034.jpeg',
    created: new Date('13 Mars 2015'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 35,
    season: 2,
    title : "D’Arby the Gambler, Partie 2",
    summary: "Après avoir capturé les âmes de Polnareff et Joseph, D’Arby a un nouvel adversaire : Jotaro ! Voyons lequel des deux est le plus doué à ce fameux jeu qu’est le poker. ",
    type: 'Shonen',
    picture: '../assets/jojo/s2035.jpeg',
    created: new Date('20 Mars 2015'),
    link1: 'https://uqload.org/embed-bpsto463k43h.html',
    link2: '',
    link3: '',
  },
  {
    episode: 36,
    season: 2,
    title : "Hol Horse et Boingo, Partie 1",
    summary: "Maintenant débarrassée de D’Arby, notre fine équipe se remet à la recherche du manoir où serait Dio. Mais le temps presse. En effet, ils apprennent qu’il ne resterait que 4 jours à Holly… C’est sans compter le retour de Hol Horse et Boingo ! Quelle sera la prophétie, cette fois-ci ?",
    type: 'Shonen',
    picture: '../assets/jojo/s2036.jpeg',
    created: new Date('27 Mars 2015'),
    link1: 'https://uqload.org/embed-3ho3xr97e4yz.html',
    link2: '',
    link3: '',
  },
  {
    episode: 37,
    season: 2,
    title : "Hol Horse et Boingo, Partie 2",
    summary: "Alors que Hol Horse avait Polnareff à sa merci, il a préféré respecter la prophétie de Boingo… C’est alors que Joseph, Avdol et Jotaro viennent voir pourquoi Polnareff a fait demi-tour, mettant Hol Horse dans une situation critique.",
    type: 'Shonen',
    picture: '../assets/jojo/s2037.jpeg',
    created: new Date('3 Avril 2015'),
    link1: 'https://uqload.org/embed-kk5m7fudaz9h.html',
    link2: '',
    link3: '',
  },
  {
    episode: 38,
    season: 2,
    title : "Pet Shop, le gardien des enfers, Partie 1",
    summary: "À la recherche du manoir où Dio serait, notre équipe ne perd pas espoir. En parallèle, Iggy passe enfin à l’action et s’est trouvé un adversaire à sa hauteur.",
    type: 'Shonen',
    picture: '../assets/jojo/s2038.jpeg',
    created: new Date('10 Avril 2015'),
    link1: 'https://uqload.org/embed-07jtvx3y49om.html',
    link2: '',
    link3: '',
  },
  {
    episode: 39,
    season: 2,
    title : "Pet Shop, le gardien des enfers, Partie 2",
    summary: "Alors que la patte d’Iggy est prise dans la glace de Pet Shop, il réussit à survivre à son attaque. Le combat se poursuit alors dans les souterrains.",
    type: 'Shonen',
    picture: '../assets/jojo/s2039.jpeg',
    created: new Date('17 Avril 2015'),
    link1: 'https://uqload.org/embed-mipzexwv0v3x.html',
    link2: '',
    link3: '',
  },
  {
    episode: 40,
    season: 2,
    title : "D’Arby the Player, Partie 1",
    summary: "Maintenant que l’entrée du manoir où se trouverait Dio est enfin dégagée, un nouvel obstacle apparaît. Il s’agit de D’Arby, le petit frère, cette fois ! Lui aussi aime parier, mais dans un tout autre style de jeu…",
    type: 'Shonen',
    picture: '../assets/jojo/s2040.jpeg',
    created: new Date('24 Avril 2015'),
    link1: 'https://uqload.org/embed-m28lskgkm5as.html',
    link2: '',
    link3: '',
  },
  {
    episode: 41,
    season: 2,
    title : "D’Arby the Player, Partie 2",
    summary: "Après avoir terminé la course de voiture, Jotaro prend la relève et s’essaie à un tout autre style de jeu. Mais il ne semble pas être au point… ou peut-être est-ce une ruse pour déstabiliser l’adversaire ?",
    type: 'Shonen',
    picture: '../assets/jojo/s2041.jpeg',
    created: new Date('31 Avril 2015'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 42,
    season: 2,
    title : "Vanilla Ice, Miasmes d’outre-espace, Partie 1",
    summary: "Le match de baseball se poursuit contre D’Arby. Jotaro semble avoir trouvé une stratégie que D’Arby a du mal à cerner… Réussira-t-il à atteindre les 11 points de la victoire ?",
    type: 'Shonen',
    picture: '../assets/jojo/s2042.jpeg',
    created: new Date('8 Mai 2015'),
    link1: 'https://uqload.org/embed-z2zt141yumhc.html',
    link2: '',
    link3: '',
  },
  {
    episode: 43,
    season: 2,
    title : "Vanilla Ice, Miasmes d’outre-espace, Partie 2",
    summary: "C’est au tour de Polnareff, Avdol et Iggy d’entrer dans le manoir. Ces derniers font face à un nouvel adversaire, très proche de Dio. Avdol s’en sortira-t-il indemne ?",
    type: 'Shonen',
    picture: '../assets/jojo/s2043.jpeg',
    created: new Date('15 Mai 2015'),
    link1: 'https://uqload.org/embed-dbys4aniarzc.html',
    link2: '',
    link3: '',
  },
  {
    episode: 44,
    season: 2,
    title : "Vanilla Ice, Miasmes d’outre-espace, Partie 3",
    summary: "Alors que les combats prennent fin, la mère de Holly fait un voyage au Japon pour aller voir sa fille. Mais Rosas, son majordome, ne lui a pas encore révélé que sa fille risque de mourir dans les jours à venir…",
    type: 'Shonen',
    picture: '../assets/jojo/s2044.jpeg',
    created: new Date('22 Mai 2015'),
    link1: 'https://uqload.org/embed-ajmxvqmk1pf0.html',
    link2: '',
    link3: '',
  },
  {
    episode: 45,
    season: 2,
    title : "Le monde de Dio, Partie 1",
    summary: "Maintenant que tous les obstacles ont été surmontés, voilà que nos héros font face à leur plus grosse menace, Dio lui-même ! ",
    type: 'Shonen',
    picture: '../assets/jojo/s2045.jpeg',
    created: new Date('29 Mai 2015'),
    link1: 'https://uqload.org/embed-3aoxd9y1oe1m.html',
    link2: '',
    link3: '',
  },
  {
    episode: 46,
    season: 2,
    title : "Le monde de Dio, Partie 2",
    summary: "Kakyoin croit avoir trouvé le moyen de percer le secret du Stand de Dio. Seulement, ce dernier et son Stand lui réservent une surprise hors du… temps. The World s'avère extrêmement puissant ! Les compagnons de Kakyoin comprendront-ils trop tard ?",
    type: 'Shonen',
    picture: '../assets/jojo/s2046.jpeg',
    created: new Date('5 Juin 2015'),
    link1: 'https://uqload.org/embed-hty7k1tawcb8.html',
    link2: '',
    link3: '',
  },
  {
    episode: 47,
    season: 2,
    title : "Le monde de Dio, Partie 3",
    summary: "Kakyoin ayant donné sa vie pour révéler la nature du pouvoir de The World, et Joseph l'ayant suivi dans la mort malgré ses efforts, c'est au tour de Jotaro d'affronter le monstrueux Dio. Quels tours de passe-passe lui sauveront la vie, cette fois ? Star Platinum est aussi un type de Stand intéressant…",
    type: 'Shonen',
    picture: '../assets/jojo/s2047.jpeg',
    created: new Date('12 Juin 2015'),
    link1: 'https://uqload.org/embed-d016db3cps0j.html',
    link2: '',
    link3: '',
  },
  {
    episode: 48,
    season: 2,
    title : "Un long périple, adieu les amis",
    summary: "L'affront final où tout va se jouer a enfin lieu, et ce sera dans un enchaînement de bulles temporelles que Jotaro et Dio se battront inlassablement ! La colère sera-t-elle un atout ou une faiblesse, pour notre héros ?",
    type: 'Shonen',
    picture: '../assets/jojo/s2048.jpeg',
    created: new Date('19 Juin 2015'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 1,
    season: 3,
    title : "Jotaro Kujo rencontre Josuke Higashikata",
    summary: "Josuke Higashikata, fils illégitime de Joseph Joestar, habite dans la ville de Morio, et ignore la présence du grand danger qui y rôde. Ne maîtrisant pas encore son Stand, il recevra quelques conseils de Jotaro venu à sa rencontre…",
    type: 'Shonen',
    picture: '../assets/jojo/s3001.jpeg',
    created: new Date('1 Avril 2016'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 2,
    season: 3,
    title : "Josuke Higashikata rencontre Angelo !",
    summary: "Angelo épie désormais la famille Higashikata. En se faisant passer pour un laitier, il tente d'insinuer son Stand dans le corps de Tomoko ou de Josuke en leur livrant leur bouteille. Heureusement, Jotaro n'est pas loin et préviendra Josuke…",
    type: 'Shonen',
    picture: '../assets/jojo/s3002.jpeg',
    created: new Date('8 Avril 2016'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 3,
    season: 3,
    title : "Les frères Nijimura, Partie 1",
    summary: "Malgré que l'affaire Angelo soit réglée, Jotaro décide de prolonger son séjour à Morio. Angelo, avant de se faire piéger dans un rocher génial, a dévoilé des informations qui ébranlent Jotaro. Un homme en uniforme pourrait volontairement doter quelqu'un d'un Stand… ",
    type: 'Shonen',
    picture: '../assets/jojo/s3003.jpeg',
    created: new Date('15 Avril 2016'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 4,
    season: 3,
    title : "Les frères Nijimura, Partie 2",
    summary: "Après avoir combattu le premier des deux frères Nijimura, Okuyasu, Josuke se prépare à affronter le second, manifestement plutôt maniaque.",
    type: 'Shonen',
    picture: '../assets/jojo/s3004.jpeg',
    created: new Date('22 Avril 2016'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 5,
    season: 3,
    title : "Les frères Nijimura, Partie 3",
    summary: "Alors que Josuke, sorti vainqueur de sa précédente bataille génialement dangereuse, veut s'enfuir de la baraque des Nijimura au plus vite, Koichi, lui, veut chercher l'arc et la flèche. Josuke, impressionné par la témérité de son ami, décide de l'accompagner. ",
    type: 'Shonen',
    picture: '../assets/jojo/s3005.jpeg',
    created: new Date('29 Avril 2016'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 6,
    season: 3,
    title : "Koichi Hirose (Echoes)",
    summary: "Koichi, très heureux de son nouveau VTT, se rend grâce à ce dernier au lycée. Or, au beau milieu du chemin se trouve un sac, contenant un chat, qu'il écrase ! Le propriétaire de l'animal ne laissera pas partir Koichi les mains dans les poches… ",
    type: 'Shonen',
    picture: '../assets/jojo/s3006.jpeg',
    created: new Date('6 mai 2016'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 7,
    season: 3,
    title : "Toshikazu Hazamada (Surface)",
    summary: "Tamami Kobayashi a été vaincu par Josuke et Koichi. Les deux jeunes garçons apprennent de la bouche de ce dernier que d'autres manieurs de Stand rôderaient encore dans Morio, dont un certain Toshikazu Hazamada. Il ne leur faut pas longtemps pour croiser le manieur et son Stand, qui a la faculté de manipuler ses adversaires à sa guise, tels des marionnettes.",
    type: 'Shonen',
    picture: '../assets/jojo/s3007.jpeg',
    created: new Date('13 mai 2016'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 8,
    season: 3,
    title : "Yukako Yamagishi est amoureuse - Partie 1",
    summary: "Josuke et Okuyasu surprennent Koichi en galante compagnie. En effet, il a rendez-vous avec l'une des plus belles filles du lycée : Yukako Yamagishi. Mais lorsqu'elle lui déclare ses sentiments, Koichi ne sait pas encore quel cauchemar l'attend...",
    type: 'Shonen',
    picture: '../assets/jojo/s3008.jpeg',
    created: new Date('20 mai 2016'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 9,
    season: 3,
    title : "Yukako Yamagishi est amoureuse - Partie 2",
    summary: "Koichi est en facheuse posture ! Yukako est en fait une manieuse de Stand et son obsession pour le jeune garçon l'a poussée à le séquestrer dans une maison isolée de Morio. Toutes les tentatives de Koichi pour s'échapper se soldent par un échec et pire encore, son Echoes se renferme dans un cocon ! De leur côté, Josuke et Okuyasu font tout pour retrouver leur ami...",
    type: 'Shonen',
    picture: '../assets/jojo/s3009.jpeg',
    created: new Date('27 mai 2016'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 10,
    season: 3,
    title : "Allons manger italien !",
    summary: "Josuke et Okuyasu découvrent qu'un nouveau restaurant italien vient d'ouvrir à Morio. Curieux de le tester, ils rencontrent Tonio Trussardi, le cuisinier de l'établissement, qui choisit lui-même les plats qu'il sert à ses clients. D'abord réticent, Okuyasu décide de tester le concept. Mais tandis que le repas commence, son corps se comporte de plus en plus bizarrement...",
    type: 'Shonen',
    picture: '../assets/jojo/s3010.jpeg',
    created: new Date('3 Juin 2016'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 11,
    season: 3,
    title : "Red Hot Chili Pepper - Partie 1",
    summary: "Alors qu'il se fait remonter les bretelles comme il se doit par sa mère, Josuke reçoit la visite inopportune du Stand électrique qui a tué Keicho Nijimura et dérobé l'arc et la flèche ! Ce dernier semble avoir gagné en puissance et est bien décidé à affronter Jotaro... Les manieurs de Stand se réunissent alors pour échafauder un plan face à cet ennemi insaisissable.",
    type: 'Shonen',
    picture: '../assets/jojo/s3011.jpeg',
    created: new Date('10 juin 2016'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 12,
    season: 3,
    title : "Red Hot Chili Pepper - Partie 2",
    summary: "Tandis que Joseph Joestar s’apprête à accoster au port de Morio, les manieurs de Stand sont sur le pied de guerre pour assurer sa protection. Mais pour cela, ils doivent monter à bord de son bateau avant Red Hot Chili Peppers. Or, contre toute attente, l'hôte du Stand électrique se dévoile au dernier moment et attaque Josuke et Koichi, restés sur le quai !",
    type: 'Shonen',
    picture: '../assets/jojo/s3012.jpeg',
    created: new Date('17 juin 2016'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 13,
    season: 3,
    title : "On est tombé sur un sale truc !",
    summary: "Akira Otoishi vaincu, l’arc et la flèche ont pu être récupérés et placés en lieu sûr. La ville de Morio connaît donc enfin un peu de tranquillité. Ce n’est pourtant pas le cas de Josuke qui doit s’occuper de Joseph Joestar, le père qu’il n’a jamais connu ! Alors que les gaffes et les quiproquos s’enchaînent entre les deux hommes, un manieur de Stand d’un genre nouveau apparaît soudainement...",
    type: 'Shonen',
    picture: '../assets/jojo/s3013.jpeg',
    created: new Date('23 juin 2016'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 14,
    season: 3,
    title : "Visite chez un mangaka - Partie 1",
    summary: "Alors qu’il se rend à l’école, Koichi croise la route de Hazamada, le manieur de 'Surface'. Ce dernier lui apprend que leur auteur de manga favori, Rohan Kishibe, vit à Morio ! En bon fans, ils décident de lui rendre visite pour lui demander des dédicaces. Mais ce qu’ils s’apprêtent à découvrir dépasse de loin tout ce qu’ils auraient pu imaginer...",
    type: 'Shonen',
    picture: '../assets/jojo/s3014.jpeg',
    created: new Date('1er juillet 2016'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 15,
    season: 3,
    title : "Visite chez un mangaka - Partie 2",
    summary: "Victime du terrible Stand Heaven’s Door, Koichi est devenu une source d’information vivante pour le mangaka Rohan Kishibe. De plus, il n’a aucun moyen d’avertir ses proches car il perd systématiquement la mémoire. Pourtant, il faudra bien trouver une solution, et vite : plus le temps passe, et plus Koichi se rapproche de la mort…",
    type: 'Shonen',
    picture: '../assets/jojo/s3015.jpeg',
    created: new Date('8 juillet 2016'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 16,
    season: 3,
    title : "La chasse est ouverte !",
    summary: "Jotaro invite Josuke à le rejoindre pour une partie de chasse d’un genre très particulier : éliminer un rat qui a été victime de 'l’arc et de la flèche' et qui a développé un Stand ! Devenu une véritable menace pour tout son environnement, ce manieur d’un genre inédit s’avère beaucoup plus retors que prévu. Qui de l’homme ou de l’animal l’emportera ?",
    type: 'Shonen',
    picture: '../assets/jojo/s3016.jpeg',
    created: new Date('15 juillet 2016'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 17,
    season: 3,
    title : "L'aventure de Rohan Kishibe",
    summary: "Alors qu’il cherche à retrouver la maison de son enfance, Rohan Kishibe invite Koichi à résoudre le mystère d’une rue qui ne figure sur aucun plan de la ville. Une fois à l’intérieur, ils découvrent une zone totalement déserte, où règne une atmosphère étrange. Les choses prennent une tournure encore plus angoissante lorsqu’ils comprennent qu’ils tournent en rond, sans possibilité de trouver le chemin du retour ! Seraient-ils victimes d’un nouveau Stand ?",
    type: 'Shonen',
    picture: '../assets/jojo/s3017.jpeg',
    created: new Date('22 juillet 2016'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 18,
    season: 3,
    title : "La moisson de Shigechi - Partie 1",
    summary: "Fauché comme les blés, Josuke se lamente sur son sort, lorsqu’il tombe nez à nez sur un Stand d’un nouveau genre, dont la particularité est de récolter les pièces égarées en ville ! Bien décidé à en avoir le coeur net, il se lance à sa poursuite, bientôt rejoint par Okuyasu. Les deux compères découvrent alors une multitude de petits Stands identiques, et un nouveau manieur : Shigekiyo Yangu, un collégien apparemment très simple d’esprit. Josuke décide alors de mettre à profit l’étonnant pouvoir de ce Stand pour s’enrichir...",
    type: 'Shonen',
    picture: '../assets/jojo/s3018.jpeg',
    created: new Date('29 juillet 2016'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 19,
    season: 3,
    title : "La moisson de Shigechi - Partie 2",
    summary: "Josuke, Okuyasu et Shigechi ont réussi à entrer en possession d’un billet gagnant de loterie d’une valeur de cinq millions de yens ! Mais pour pouvoir le valider, ils vont devoir justifier que ce billet est bien le leur. Or, le banquier qui doit s’en assurer s’avère plus perspicace que prévu…",
    type: 'Shonen',
    picture: '../assets/jojo/s3019.jpeg',
    created: new Date('5 août 2016'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 20,
    season: 3,
    title : "Yukako Yamagishi se rêve en Cendrillon",
    summary: "Ne supportant plus la distance qui la sépare de Koichi, Yukako décide de rentrer dans un salon de beauté appelé 'Cendrillon'. En effet, celui-ci propose des soins supposés 'attirer l’amour'. Malgré ses réticences, Yukako se prête au jeu. Mais les résultats, qui dépassent toutes ses attentes, impliquent aussi de respecter des règles très précises...",
    type: 'Shonen',
    picture: '../assets/jojo/s3020.jpeg',
    created: new Date('12 août 2016'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 21,
    season: 3,
    title : "Yoshikage Kira veut la tranquillité - Partie 1",
    summary: "Yoshikage Kira, tueur en série vivant la vie d’un modeste employé de bureau, croise la route de Shigechi, Josuke et Okuyasu. À la suite d’une méprise, Shigechi s’empare d’une preuve qui pourrait mettre Kira derrière les barreaux, si la police venait à la découvrir. Le tueur décide alors de suivre le garçon et de récupérer son bien, le plus discrètement possible...",
    type: 'Shonen',
    picture: '../assets/jojo/s3021.jpeg',
    created: new Date('19 août 2016'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 22,
    season: 3,
    title : "Yoshikage Kira veut la tranquillité - Partie 2",
    summary: "Shigechi a finalement découvert l’identité de Kira, le fameux tueur en série que personne n’a jamais pu attraper ! Malgré la puissance de Harvest, Shigechi n’est pas de taille face au pouvoir spécial de Killer Queen, le Stand de Kira. Alors qu’il réussit in extremis à s’enfuir, Shigechi utilise ses dernières forces pour retrouver et prévenir Josuke...",
    type: 'Shonen',
    picture: '../assets/jojo/s3022.jpeg',
    created: new Date('26 août 2016'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 23,
    season: 3,
    title : "Sheer Heart Attack - Partie 1",
    summary: "Grâce au bouton légué par Shigechi avant sa mort, Jotaro et Koichi ont fini par retrouver la veste du tueur en série. Mais au moment où ils s’apprêtent à découvrir son identité, celui-ci leur envoie un Stand redoutable : Sheer Heart Attack. Et sa puissance destructrice n’a d’égale que sa résistance aux coups, y compris ceux de Star Platinum. Bien décidé à traquer le criminel, Koichi décide d’envoyer Echoes à sa poursuite, malgré les mises en garde de Jotaro…",
    type: 'Shonen',
    picture: '../assets/jojo/s3023.jpeg',
    created: new Date('2 septembre 2016'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 24,
    season: 3,
    title : "Sheer Heart Attack - Partie 2",
    summary: "Koichi a évolué en même temps que son Stand, Echoes, qui dispose désormais d’un nouveau pouvoir. Celui-ci met tellement en difficulté Kira qu’il doit se résoudre à venir récupérer sa bombe automatique, Sheer Heart Attack. Le moment de la confrontation directe entre Koichi et Kira commence !",
    type: 'Shonen',
    picture: '../assets/jojo/s3024.jpeg',
    created: new Date('9 septembre 2016'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 25,
    season: 3,
    title : "Atom Heart Father",
    summary: "Kira s’étant échappé, les manieurs de Stand décident d’aller enquêter dans sa maison. Mais leur investigation est soudainement interrompue par une présence inquiétante : le fantôme du père de Kira, bien décidé à éliminer tous ceux qui en ont après son fils !s3",
    type: 'Shonen',
    picture: '../assets/jojo/s3025.jpeg',
    created: new Date('16 septembre 2016'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 26,
    season: 3,
    title : "Pierre-feuille-ciseaux !",
    summary: "Tandis qu’il essaie de retrouver la piste de Kira, Rohan Kishibe est abordé par un enfant qui le défie au jeu du « pierre, feuille, ciseaux ». Et bien que son insistance à jouer soit anormale, il ne semble pas représenter une quelconque menace. Excédé, Rohan décide finalement de se débarrasser de lui violemment...",
    type: 'Shonen',
    picture: '../assets/jojo/s3026.jpeg',
    created: new Date('23 septembre 2016'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 27,
    season: 3,
    title : "Je suis un extraterrestre",
    summary: "Alors qu’ils sont sur le chemin du lycée, Josuke et Okuyasu découvrent un garçon étendu, inconscient, au milieu d’un champ. Celui-ci prétend venir d’une autre planète, et étudier la Terre. Naturellement, ni Josuke ni Okuyasu ne le croient. Mais d’étranges phénomènes se présentent alors à eux...",
    type: 'Shonen',
    picture: '../assets/jojo/s3027.jpeg',
    created: new Date('30 septembre 2016'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 28,
    season: 3,
    title : "Highway Star - Partie 1",
    summary: "Avec l’aide de Mikitaka, l’extraterrestre autoproclamé, Josuke essaie de tricher aux dés pour soutirer de l’argent à Rohan. Mais la partie dégénère très vite, à tel point que Josuke se retrouve en très fâcheuse posture. Rohan, conscient de la supercherie dont il est victime, est en effet prêt à tout pour prendre Josuke à son propre piège… Et pour découvrir la vérité !",
    type: 'Shonen',
    picture: '../assets/jojo/s3028.jpeg',
    created: new Date('7 octobre 2016'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 29,
    season: 3,
    title : "Highway Star - Partie 2",
    summary: "Alors qu’il a essayé de sauver Rohan Kishibe dans le tunnel des Deux bois, Josuke est devenu la prochaine cible de Highway Star, un Stand qui ne possède aucun point faible ! La seule façon de lui échapper consiste à dépasser continuellement la vitesse de 60 km/h. Josuke n’a pas le choix : il doit découvrir l’identité du manieur de Stand pour le supprimer ! Mais comment mener cette enquête alors qu’il doit rouler à pleine vitesse sans jamais s’arrêter ?",
    type: 'Shonen',
    picture: '../assets/jojo/s3029.jpeg',
    created: new Date('14 octobre 2016'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 30,
    season: 3,
    title : "Yoshikage Kira attire les chats",
    summary: "Chez les Kawajiri, Shinobu, la femme au foyer, tombe sur un chat qui a élu domicile dans la cave. Alors qu’elle essaye de le faire sortir, un accident malencontreux provoque le décès de l’animal. Et c’est Kosaku -Kira- Kawajiri qui doit se charger d’enterrer la dépouille. Seulement, le lendemain, une forme inhabituelle apparaît dans le jardin, à l’endroit précis où la bête a été inhumée…",
    type: 'Shonen',
    picture: '../assets/jojo/s3030.jpeg',
    created: new Date('21 octobre 2016'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 31,
    season: 3,
    title : "Jeudi 15 juillet - Partie 1",
    summary: "Toujours à la recherche de son fils, le père de Kira est bien décidé à empêcher les manieurs de Stand de poursuivre leurs investigations. Son « plan d’attaque » démarre le 15 juillet. Et cette journée en apparence ordinaire va en réalité se révéler particulièrement agitée pour de nombreuses personnes…",
    type: 'Shonen',
    picture: '../assets/jojo/s3031.jpeg',
    created: new Date('28 octobre 2016'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 32,
    season: 3,
    title : "Jeudi 15 juillet - Partie 2",
    summary: "Tandis que Josuke affronte l’homme qui vit dans le pylône, Rohan Kishibe reçoit la visite de l’architecte qui doit lui faire un devis pour sa maison. Étrangement, cet homme refuse catégoriquement de dévoiler son dos, et pour cela, il frôle littéralement et constamment les murs. Piqué par son insatiable curiosité, Rohan décide de lui tendre un piège…",
    type: 'Shonen',
    picture: '../assets/jojo/s3032.jpeg',
    created: new Date('4 novembre 2016'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 33,
    season: 3,
    title : "Jeudi 15 juillet - Partie 3",
    summary: "Josuke affronte Enigma, un Stand qui peut transformer une personne en papier si elle cède à la peur ! Mais cet ennemi se révèle plus fort que lui. Yuya Fungami décide alors de prendre son courage à deux mains et se lance à la poursuite de Koichi et de Josuke. Pendant ce temps, Rohan réussit enfin à voir à quoi ressemble le dos de l’architecte, Masazo Kinoto ! Sans le savoir, il vient d’activer « Cheap Trick » et de tomber dans un piège inextricable !",
    type: 'Shonen',
    picture: '../assets/jojo/s3033.jpeg',
    created: new Date('11 novembre 2016'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 34,
    season: 3,
    title : "Jeudi 15 juillet - Partie 4",
    summary: "",
    type: 'Shonen',
    picture: '../assets/jojo/s3034.jpeg',
    created: new Date('18 novembre 2016'),
    link1: 'Rohan Kishibe doit trouver un moyen de se débarrasser de Cheap Trick, le Stand qui a pris possession de son dos. Il appelle ainsi Koichi à la rescousse mais ce dernier ne croit pas un mot de cette histoire abracadabrante. À nouveau seul, Rohan décide donc de se rendre directement au Morio Grand Hotel. Mais comment se déplacer dehors sans que personne ne puisse voir son dos ?s303',
    link2: '',
    link3: '',
  },
  {
    episode: 35,
    season: 3,
    title : "Another One Bites the Dust - Partie 1",
    summary: "Démasqué par Hayato, qui l’a filmé en train d’assassiner deux personnes, Kira est mis en difficulté et finit par supprimer le jeune garçon. Ce geste, qui pourrait bien le mener à sa perte, le plonge dans un désarroi total. C’est alors que la flèche se met à agir seule et à le traverser une nouvelle fois… Pour quelle raison ? À quelle nouvelle faculté vient-elle de donner naissance ?",
    type: 'Shonen',
    picture: '../assets/jojo/s3035.jpeg',
    created: new Date('25 novembre 2016'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 36,
    season: 3,
    title : "Another One Bites the Dust - Partie 2",
    summary: "Yoshikage Kira a placé un dispositif de sécurité dans le corps de Hayato : chaque fois qu’une personne l’interroge à son sujet, elle explose ! Et la seconde suivante, Hayato remonte le temps une heure en arrière, contraint de revivre les mêmes situations, sans pouvoir modifier le moindre événement. Face à ce pouvoir terrifiant, quelle solution cet enfant de 11 ans trouvera-t-il pour s’en sortir et vaincre Kira ?",
    type: 'Shonen',
    picture: '../assets/jojo/s3036.jpeg',
    created: new Date('2 décembre 2016'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 37,
    season: 3,
    title : "Crazy Diamond is Unbreakable - Partie 1",
    summary: "En se servant de Stray Cat, le chat-plante élevé secrètement dans son grenier, Hayato a tenté un plan audacieux pour tuer Kira, mais il a échoué au dernier moment ! Rien ne semble désormais en mesure d’empêcher la mort programmée de Rohan et des autres manieurs de Stand. À moins que Hayato ait prévu un ultime coup de poker ?",
    type: 'Shonen',
    picture: '../assets/jojo/s3037.jpeg',
    created: new Date('9 décembre 2016'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 38,
    season: 3,
    title : "Crazy Diamond is Unbreakable - Partie 2",
    summary: "Confronté à Kira, Josuke se réfugie dans une maison vide avec Hayato et le corps inanimé d’Okuyasu, mortellement touché. Acculé dans ce lieu fermé, Josuke est à nouveau attaqué par les bulles explosives de son ennemi, qui parviennent à le suivre à la trace. Comment Kira peut-il localiser sa cible, lui qui n’a aucun moyen de savoir ce qui se passe dans cette maison ? Josuke devra éclaircir ce mystère rapidement s’il ne veut pas perdre cet ultime combat...",
    type: 'Shonen',
    picture: '../assets/jojo/s3038.jpeg',
    created: new Date('16 décembre 2016'),
    link1: '',
    link2: '',
    link3: '',
  },
  {
    episode: 39,
    season: 3,
    title : "Adieu Morio - La jeunesse au cœur d'or",
    summary: "Kira est finalement vaincu par les manieurs de Stand, et son identité est révélée au grand jour. Alors que les secours, alertés par le bruit des diverses explosions, arrivent sur place, Kira s’apprête à déchaîner son pouvoir une dernière fois. S’il y parvient, tous les efforts menés seront anéantis...",
    type: 'Shonen',
    picture: '../assets/jojo/s3039.jpeg',
    created: new Date('23 décembre 2016'),
    link1: '',
    link2: '',
    link3: '',
  },
]

