import { Anime } from './../modeles/anime';


export const JUJUTSUKAISEN : Anime[] = [
  {
    episode: 1,
    season: 1,
    title : 'Ryomen Sukuna',
    summary: "Élève de seconde, Yuji Itadori, véritable force de la nature, ne voit guère dans le surnaturel qu’un prétexte à fréquenter le club de spiritisme de son lycée, où il se sent bien et dont les activités lui permettent de rentrer pas trop tard. N’étant lui-même pas doté de pouvoirs occultes, il ne croit pas aux fantômes et ne prête qu’une oreille polie aux explications d’un inconnu qui lui réclame l’objet qu’il a dérobé dans une station météo. Selon son visiteur, il s’agit en réalité d’une relique extrêmement puissante qui a été placée là pour protéger son lycée contre des monstres...",
    type: 'Shonen',
    picture: '../assets/jujutsuKaisen/001.jpeg',
    created: new Date('3 octobre 2020'),
    link1: '//sendvid.com/embed/bo6k9vqc',
    link2: '',
    link3: '',
  },
  {
    episode: 2,
    season: 1,
    title : 'Pour moi-même',
    summary: "Ayant volontairement avalé la relique maudite, Yuji va devoir faire face aux conséquences de ce coup de tête aussi téméraire que peu réfléchi, à savoir l’arrivée sur place d’un exorciste d’élite chargé de le tuer, mais aussi très curieux de le voir de près. Ce n’est pas tous les jours que quelqu’un parvient à mettre en échec le terrible démon Sukuna…",
    type: 'Shonen',
    picture: '../assets/jujutsuKaisen/002.jpeg',
    created: new Date('10 octobre 2020'),
    link1: '//sendvid.com/embed/b8hvx8fc',
    link2: '',
    link3: '',
  },
  {
    episode: 3,
    season: 1,
    title : 'La bâtisseuse',
    summary: "Megumi et Yuji accueillent leur unique camarade, que Gojo va immédiatement mettre à l'épreuve. Il craint en effet que, peu habituée à la sournoiserie des fléaux de la capitale, la jeune provinciale n’ait pas le grain de folie nécessaire pour oser les affronter.",
    type: 'Shonen',
    picture: '../assets/jujutsuKaisen/003.jpeg',
    created: new Date('17 octobre 2020'),
    link1: '//sendvid.com/embed/kgmvtfja',
    link2: '',
    link3: '',
  },
  {
    episode: 4,
    season: 1,
    title : 'Naissance de la matrice',
    summary: "Un fléau potentiellement de classe S a été repéré dans une prison pour mineurs. Yuji, Megumi et Nobara sont envoyés sur place pour essayer de retrouver des survivants, si tant est qu’il y en ait, et ordre leur est donné de ne surtout pas approcher le fléau lui-même. Malheureusement, ils ne vont pas avoir le choix…",
    type: 'Shonen',
    picture: '../assets/jujutsuKaisen/004.jpeg',
    created: new Date('24 octobre 2020'),
    link1: '//sendvid.com/embed/ckggq0b7',
    link2: '',
    link3: '',
  },
  {
    episode: 5,
    season: 1,
    title : 'Naissance de la matrice (2)',
    summary: "Tandis que Nobara est conduite à l’hôpital, Megumi attend le retour de Yuji, qu’il a laissé aux prises avec le fléau de classe S. C’est pourtant quelqu’un de très différent qui va surgir tout à coup…",
    type: 'Shonen',
    picture: '../assets/jujutsuKaisen/005.jpeg',
    created: new Date('31 octobre 2020'),
    link1: '//sendvid.com/embed/egjq1068',
    link2: '',
    link3: '',
  },
  {
    episode: 6,
    season: 1,
    title : 'Après la pluie',
    summary: "Yuji essaie de négocier avec Sukuna afin qu’il le ressuscite, mais le démon veut lui imposer certaines conditions. Megumi et Nobara, eux, s’entraînent avec les première, pendant qu’un serveur de restaurant a une sacrément bonne intuition…",
    type: 'Shonen',
    picture: '../assets/jujutsuKaisen/006.jpeg',
    created: new Date('7 novembre 2020'),
    link1: '//sendvid.com/embed/1gngvrze',
    link2: '',
    link3: '',
  },
  {
    episode: 7,
    season: 1,
    title : 'Attaque surprise',
    summary: "En route pour un rendez-vous avec le proviseur, Gojo est attaqué par un fléau de classe S non répertorié. Le combat tourne vite à son avantage, son adversaire n’étant pas en mesure de le toucher. Ce que Gojo ignore, c’est que l’assaillant n’est pas venu seul…",
    type: 'Shonen',
    picture: '../assets/jujutsuKaisen/007.jpeg',
    created: new Date('14 novembre 2020'),
    link1: '//sendvid.com/embed/ztt4ktu7',
    link2: '',
    link3: '',
  },
  {
    episode: 8,
    season: 1,
    title : 'Ennui',
    summary: "Profitant de la réunion préparatoire au tournoi à venir, deux élèves de l’École d’exorcisme de Kyoto rendent une petite visite de courtoisie à Megumi et Nobara. C’est aussi l’occasion pour Gojo d’aller s’expliquer avec leur proviseur.",
    type: 'Shonen',
    picture: '../assets/jujutsuKaisen/008.jpeg',
    created: new Date('21 novembre 2020'),
    link1: '//sendvid.com/embed/882nskgu',
    link2: '',
    link3: '',
  },
  {
    episode: 9,
    season: 1,
    title : 'Petit poisson et retour de bâton',
    summary: "Après avoir fait la connaissance des élèves de Kyoto, revenons à Yuji, chargé par Gojo d’enquêter sur un curieux meurtre commis dans un cinéma. Cerise sur le gâteau, l’exorciste avec lequel il doit travailler s’est déjà fait son opinion sur lui, et elle n’est pas reluisante…",
    type: 'Shonen',
    picture: '../assets/jujutsuKaisen/009.jpeg',
    created: new Date('28 novembre 2020'),
    link1: '//sendvid.com/embed/mp49vhl1',
    link2: '',
    link3: '',
  },
  {
    episode: 10,
    season: 1,
    title : 'Altération absolue',
    summary: "Yuji parvient assez facilement à entrer en contact avec Junpei Yoshino, seul témoin de la tuerie du cinéma. La tâche est en revanche beaucoup moins aisée pour Nanami, son adversaire ayant le pouvoir de modeler l’enveloppe corporelle de ses victimes, mais aussi leur âme.",
    type: 'Shonen',
    picture: '../assets/jujutsuKaisen/010.jpeg',
    created: new Date('5 decembre 2020'),
    link1: '//sendvid.com/embed/dr60s0ac',
    link2: '',
    link3: '',
  },
  {
    episode: 11,
    season: 1,
    title : 'Intransigeance',
    summary: "Mahito était prévenu, Nanami déteste faire des heures supplémentaires. Son affrontement avec Mahito lui donne cependant matière à réfléchir, et on ne peut pas dire que le résultat soit joyeux. Yuji dîne chez Junpei et sympathise avec lui. Parviendra-t-il à contrebalancer l’influence de Mahito et à chasser les ténèbres qui s’amoncellent dans l’âme de ce garçon tourmenté ? ",
    type: 'Shonen',
    picture: '../assets/jujutsuKaisen/011.jpeg',
    created: new Date('12 decembre 2020'),
    link1: '//sendvid.com/embed/jn34atse',
    link2: '',
    link3: '',
  },
  {
    episode: 12,
    season: 1,
    title : 'Pour toi, un jour',
    summary: "Aveuglé par la colère et le chagrin, Junpei a laissé la noirceur qui l’habitait déjà le submerger, sans s’apercevoir qu’il ne fait que servir les intérêts de Mahito. De son côté, Yuji a été mis au courant de la situation et accourt pour tenter de l’aider. Le spectacle auquel il assiste va le méduser…",
    type: 'Shonen',
    picture: '../assets/jujutsuKaisen/012.jpeg',
    created: new Date('19 decembre 2020'),
    link1: '//sendvid.com/embed/dgvdo2ql',
    link2: '',
    link3: '',
  },
  {
    episode: 13,
    season: 1,
    title : 'A demain',
    summary: "Sous le déluge des coups infligés par Yuji et Nanami, Mahito voit sa fin arriver. Il se décide donc à jouer une carte majeure, acquise depuis peu : l’Extension du territoire.",
    type: 'Shonen',
    picture: '../assets/jujutsuKaisen/013.jpeg',
    created: new Date('26 decembre 2020'),
    link1: '//sendvid.com/embed/oaxp5bsi',
    link2: '',
    link3: '',
  },
  {
    episode: 14,
    season: 1,
    title : 'Le tournoi - épreuve par équipes (0)',
    summary: "Enfin, ça y est ! Yuji va pouvoir faire son grand retour à l’occasion de l’Amicale, le tournoi opposant Tokyo et Kyoto ! Et Gojo, qui a réfléchi à la question, lui prépare une arrivée en fanfare. Mais on se rendra vite compte que l’Amicale porte, cette année, assez mal son nom…",
    type: 'Shonen',
    picture: '../assets/jujutsuKaisen/014.jpeg',
    created: new Date('16 janvier 2021'),
    link1: '//sendvid.com/embed/sbrwgqb9',
    link2: '',
    link3: '',
  },
  {
    episode: 15,
    season: 1,
    title : 'Le tournoi - épreuve par équipes (1)',
    summary: "Après le coup d’envoi, donné par Gojo et Utahime, chaque groupe commence à appliquer sa stratégie. Yuji, renfort inattendu, est chargé de contenir la puissance de feu de Todo, pour permettre aux pisteurs de Tokyo de trouver les fléaux disséminés dans l’enceinte. Or, du côté de Kyoto, c’est plutôt une chasse au Yuji qui s’est ouverte.",
    type: 'Shonen',
    picture: '../assets/jujutsuKaisen/015.jpeg',
    created: new Date('23 janvier 2021'),
    link1: '//sendvid.com/embed/drxhg7w8',
    link2: '',
    link3: '',
  },
  {
    episode: 16,
    season: 1,
    title : 'Le tournoi - épreuve par équipes (2)',
    summary: "Depuis que Todo connaît les goûts de Yuji en matière de filles, la brute sadique s’est transformée en camarade d’entraînement prodigue en conseils. C’est plus compliqué pour Panda, qui doit se battre contre Mechamaru, et Nobara, opposée à Momo. Mais, tout comme son adversaire, Panda nous réserve bien des surprises… ",
    type: 'Shonen',
    picture: '../assets/jujutsuKaisen/016.jpeg',
    created: new Date('30 janvier 2021'),
    link1: '//sendvid.com/embed/aspmf8o5',
    link2: '',
    link3: '',
  },
  {
    episode: 17,
    season: 1,
    title : 'Le tournoi - épreuve par équipes (3)',
    summary: "Trompée par les propos méprisants de Mai au sujet de Maki, Miwa aborde son combat contre cette dernière avec une certaine désinvolture, qui vole vite en éclats devant la différence de niveau abyssale entre les deux exorcistes. Quant à Momo, elle s’est lancée dans un long monologue qui ne semble pas tellement convaincre Nobara…",
    type: 'Shonen',
    picture: '../assets/jujutsuKaisen/017.jpeg',
    created: new Date('6 fevrier 2021'),
    link1: '//sendvid.com/embed/f1s05zdy',
    link2: '',
    link3: '',
  },
  {
    episode: 18,
    season: 1,
    title : 'Le sage',
    summary: "Si les précédents combats se sont déroulés en extérieur, c’est bien dans les locaux même de l’École que Megumi fait face à Noritoshi Kamo, héritier d’un des trois grands clans d’exorcistes et détenteur d’une technique aux effets impressionnants. Moins impressionnants, toutefois, que le fléau avec lequel Inumaki se retrouve nez à nez…",
    type: 'Shonen',
    picture: '../assets/jujutsuKaisen/018.jpeg',
    created: new Date('13 fevrier 2021'),
    link1: '//sendvid.com/embed/9wiurpjr',
    link2: '',
    link3: '',
  },
  {
    episode: 19,
    season: 1,
    title : 'Rayon noir',
    summary: "Inumaki, Kamo et Megumi ont fort à faire pour réussir ne serait-ce qu’à contenir Hanami assez longtemps pour pouvoir appeler à l’aide le personnel encadrant. La capacité particulière d’Inumaki, pourtant redouté des autres exorcistes, se révèle peu efficace sur le fléau en plus d’être dangereuse pour l’incantateur. Sans renforts, les trois jeunes gens sont perdus…",
    type: 'Shonen',
    picture: '../assets/jujutsuKaisen/019.jpeg',
    created: new Date('20 fevrier 2021'),
    link1: '//sendvid.com/embed/bz6c7koz',
    link2: '',
    link3: '',
  },
  {
    episode: 20,
    season: 1,
    title : 'Hors norme',
    summary: "Où Todo démontre qu’il a bien d’autres atouts que sa force brute… et où Gojo rappelle que décidément, mieux vaut se trouver ailleurs quand il s'y met vraiment.",
    type: 'Shonen',
    picture: '../assets/jujutsuKaisen/020.jpeg',
    created: new Date('27 fevrier 2021'),
    link1: '//sendvid.com/embed/kldi631v',
    link2: '',
    link3: '',
  },
  {
    episode: 21,
    season: 1,
    title : 'Le match de base-ball',
    summary: "La diversion opérée par Mahito et sa bande pour s’emparer des doigts de Sukuna a parfaitement atteint son objectif. Les exorcistes, eux, comptent leurs morts et discutent des mesures à prendre. Il va par ailleurs bien falloir en finir avec ce tournoi et désigner un vainqueur…",
    type: 'Shonen',
    picture: '../assets/jujutsuKaisen/021.jpeg',
    created: new Date('6 mars 2021'),
    link1: '//sendvid.com/embed/b1xwic9b',
    link2: '',
    link3: '',
  },
  {
    episode: 22,
    season: 1,
    title : 'Instinct grégaire',
    summary: "Megumi, Yuji et Nobara enquêtent sur une série de meurtres mystérieux perpétrés par un ou plusieurs fléaux. De troublantes similarités semblent les relier, mais ils ne se sont produits ni au même moment, ni dans la même ville. En revanche, les trois victimes avaient fréquenté le même collège… que l’un de nos héros connaît très bien.",
    type: 'Shonen',
    picture: '../assets/jujutsuKaisen/022.jpeg',
    created: new Date('13 mars 2021'),
    link1: '//sendvid.com/embed/7lztjymk',
    link2: '',
    link3: '',
  },
  {
    episode: 23,
    season: 1,
    title : 'Instinct grégaire (2)',
    summary: "Par un fâcheux hasard, les créatures de Mahito ont surgi au moment même où notre trio de choc arrivait sur place. Sans compter le fléau du pont Yasohachi, qui va faire ressurgir d’assez mauvais souvenirs…",
    type: 'Shonen',
    picture: '../assets/jujutsuKaisen/023.jpeg',
    created: new Date('20 mars 2021'),
    link1: '//sendvid.com/embed/9bvbhv7w',
    link2: '',
    link3: '',
  },
  {
    episode: 24,
    season: 1,
    title : 'Complices',
    summary: "Pendant que Megumi fait un petit somme, Nobara et Yuji se mesurent à des adversaires au comportement vraiment très déstabilisant. Détenteurs d’une technique utilisant leur propre sang, les deux frères Kechizu et Eso promettent une mort atroce à nos deux jeunes exorcistes. Qui de Nobara ou de Yuji aura les ressources pour venir à bout de ces créatures étranges ? ",
    type: 'Shonen',
    picture: '../assets/jujutsuKaisen/024.jpeg',
    created: new Date('27 mars 2021'),
    link1: '//sendvid.com/embed/hmc7sa3a',
    link2: '',
    link3: '',
  },
]
