import { Anime } from "../modeles/anime";

export const SAMURAICHAMPLOO : Anime[] = [
  {
    episode: 1,
    season: 1,
    title : 'Hier sera un autre jour',
    summary: 'Fû, serveuse dans un restaurant, est agressée par le fils de l’administrateur local. Elle arrive néanmoins à sauver sa vie, en échange de raviolis, grâce à Mugen, un vagabond de passage. Pendant ce temps, Jin, rônin, sauve la vie d’un paysan endetté en mettant à terre les gardes du corps dudit administrateur. Il se rend ensuite dans le restaurant, et à cause d’un quiproquo, Mugen et lui engagent le combat. Malheureusement, les lieux sont en proie aux flammes, et les deux hommes sont rapidement capturés, torturés et condamnés à mort. Fû promet de les délivrer s’ils acceptent de l’aider à retrouver le samouraï qui sent le tournesol.',
    type: 'Seinen',
    picture: '../assets/samuraiChamploo/001.jpeg',
    created: new Date('20 mai 2004'),
    link1: "//ok.ru/videoembed/44310923823",
    link2: '',
    link3: '',
  },
  {
    episode: 2,
    season: 1,
    title : 'La Vengeance aux deux visages',
    summary: 'Mugen et Jin acceptent le marché de Fû, mais se rendent vite compte qu’ils manquent d’argent pour leur voyage. En s’arrêtant dans une auberge, ils apprennent qu’un monstre sévit dans les montagnes et décident de le capturer. Alors que Mugen suit une fille pour une nuit d’amour et que Jin part se relaxer aux sources chaudes, Fû est enlevée par un des hommes du fils de l’administrateur, allié à une brute défigurée.',
    type: 'Seinen',
    picture: '../assets/samuraiChamploo/002.jpeg',
    created: new Date('3 juin 2004'),
    link1: '//ok.ru/videoembed/315958495929',
    link2: '',
    link3: '',
  },
  {
    episode: 3,
    season: 1,
    title : 'Porte-Sabres à louer, première partie',
    summary: 'Fatigués, Jin et Mugen arrivent à faire faux bond à Fû, chacun continuant son propre chemin. Mugen se fait alors remarquer par les impitoyables Nagatomi, un clan de yakuzas, alors que Jin se met au service de leurs rivaux, les Kawaraika. Fû, quant à elle, se fait arnaquer par des Nagatomi et se voit obligée de travailler dans un bordel pour leur rembourser une dette pharaonique.',
    type: 'Seinen',
    picture: '../assets/samuraiChamploo/003.jpeg',
    created: new Date('10 juin 2004'),
    link1: "//ok.ru/videoembed/44400904751",
    link2: '',
    link3: '',
  },
  {
    episode: 4,
    season: 1,
    title : 'Porte-Sabres à louer, seconde partie',
    summary: 'Alors que Jin tente de porter secours à Osuzu au bordel, il se trouve nez à nez avec Mugen, dans le camp adverse, et avec Fû, enfermée dans la cage des prostituées. L’affrontement est inévitable et le sauvetage tourne court. Mugen, qui ne partage pas les mêmes idées que le chef, se rebelle finalement contre les Nagatomi. La situation dégénère quand Sôsuke poignarde l’un d’entre eux en voulant protéger Osuzu. Les Nagatomi proposent de régler définitivement le conflit par une partie de dés.',
    type: 'Seinen',
    picture: '../assets/samuraiChamploo/004.jpeg',
    created: new Date('17 juin 2004'),
    link1: "//ok.ru/videoembed/44381899311",
    link2: '',
    link3: '',
  },
  {
    episode: 5,
    season: 1,
    title : 'Délire artistique',
    summary: 'Alors que Jin et Mugen cherchent de l’argent pour une traversée en bateau, Moronobu, un peintre d’estampes, demande à Fû s’il peut faire son portrait. Elle ignore encore que l’artiste fait en réalité partie d’un grand réseau de trafic de jeunes Japonaises envoyées en Europe.',
    type: 'Seinen',
    picture: '../assets/samuraiChamploo/005.jpeg',
    created: new Date('24 juin 2004'),
    link1: "//ok.ru/videoembed/315958954681",
    link2: '',
    link3: '',
  },
  {
    episode: 6,
    season: 1,
    title : 'L\'Étranger à la touffe rouge',
    summary: 'Affamés, Jin et Mugen mettent en gage leurs armes pour participer au tournoi du plus gros mangeur d’Edo. Alors que Fû est finaliste, elle fait le signe d’abandon par erreur en voulant tuer une mouche. Le vainqueur est un étranger aux cheveux roux qui propose de leur rendre leurs biens contre une visite touristique de la ville. Malheureusement, les Européens étant interdits d’accoster au Japon, ils se retrouvent vite pistés par la police locale.',
    type: 'Seinen',
    picture: '../assets/samuraiChamploo/006.jpeg',
    created: new Date('1er juillet 2004'),
    link1: '//ok.ru/videoembed/315959151289',
    link2: '',
    link3: '',
  },
  {
    episode: 7,
    season: 1,
    title : 'Le Port de la drogue',
    summary: 'Alors que le trio avait enfin réussi à gagner un peu d’argent, Fû se fait voler son portefeuille par un voleur à la tire. En se faisant passer pour sa petite amie, elle découvre que ce dernier ne peut payer les médicaments de sa mère malade et qu’il est malgré lui mêlé à une affaire de drogue.',
    type: 'Seinen',
    picture: '../assets/samuraiChamploo/007.jpeg',
    created: new Date('8 juillet 2004'),
    link1: '//ok.ru/videoembed/859874658866',
    link2: '',
    link3: '',
  },
  {
    episode: 8,
    season: 1,
    title : 'La Légende de l\'Est',
    summary: 'Nagamitsu, un vieux frimeur, s’est mis en tête qu’il devait battre Jin, et défie ainsi tous les samouraïs à lunettes qu’il peut rencontrer. En courtisant Fû dans un restaurant, il croise la route du vrai Jin, mais sans le remarquer, ce dernier ayant été obligé de mettre en gage ses lunettes contre un peu d’argent. Alors que Jin et Mugen se font séduire par une inconnue et disparaissent avec elle, Fû, par fierté, décide d’accepter la proposition de Nagamitsu.',
    type: 'Seinen',
    picture: '../assets/samuraiChamploo/008.jpeg',
    created: new Date('15 juillet 2004'),
    link1: '//ok.ru/videoembed/859874724402',
    link2: '',
    link3: '',
  },
  {
    episode: 9,
    season: 1,
    title : 'Le Pique-Nique du beatnik',
    summary: 'Mugen, Jin et Fû doivent passer par le péage de Hakone pour continuer leur voyage, mais malheureusement ils ne possèdent pas d’autorisation. Ils arrivent à se procurer des faux, mais sont bien évidemment arrêtés sur le champ. Les douaniers se rendent alors compte qu’ils ont tué un homme dont la tête avait été mise à prix. Mugen est chargé de la rapporter, mais s’il ne réussit pas avant le coucher du soleil, Jin et Fû seront exécutés.',
    type: 'Seinen',
    picture: '../assets/samuraiChamploo/009.jpeg',
    created: new Date('22 juillet 2004'),
    link1: '//ok.ru/videoembed/859874789938',
    link2: '',
    link3: '',
  },
  {
    episode: 10,
    season: 1,
    title : 'Folie meurtrière',
    summary: 'Jin, Mugen et Fû se mettent au service d’un moine contre le gîte et le couvert. Fû apprend alors dans le village que les autorités locales offrent une récompense contre la capture d’un tueur en série s’en prenant uniquement aux samouraïs de haut niveau. Mugen se met rapidement en tête de le retrouver.',
    type: 'Seinen',
    picture: '../assets/samuraiChamploo/010.jpeg',
    created: new Date('29 juillet 2004'),
    link1: '//ok.ru/videoembed/859874855474',
    link2: '',
    link3: '',
  },
  {
    episode: 11,
    season: 1,
    title : 'Souvenirs en vrac',
    summary: 'Alors que Mugen se met en tête que les combats de scarabées pourraient lui rapporter de l’argent, Jin fait la connaissance d’une jeune femme sur un pont qui décide de l’aider pour son nouveau travail. Elle lui avoue qu’à cause des dettes de son mari, elle va devoir aller travailler dans un bordel. Tombé amoureux d’elle, Jin décide de lui venir en aide.',
    type: 'Seinen',
    picture: '../assets/samuraiChamploo/011.jpeg',
    created: new Date('5 août 2004'),
    link1: '//ok.ru/videoembed/859874921010',
    link2: '',
    link3: '',
  },
  {
    episode: 12,
    season: 1,
    title : 'Souvenirs en vrac',
    summary: 'Jin et Mugen s’interrogent sur le samouraï qui sent le tournesol et sur la crédibilité de la promesse qu’ils ont faite à Fû. Ils volent alors le journal intime de la jeune femme pendant qu’elle prend son bain et revivent leur long voyage de son point de vue. Ils se rendent vite compte que Fû a une façon bien personnelle de décrire leurs aventures.',
    type: 'Seinen',
    picture: '../assets/samuraiChamploo/012.jpeg',
    created: new Date('12 août 2004'),
    link1: '//ok.ru/videoembed/859874986546',
    link2: '',
    link3: '',
  },
  {
    episode: 13,
    season: 1,
    title : 'Les Flibustiers de la nuit, première partie',
    summary: 'Sur la route pour Nagasaki, alors que le trio atteint les côtes, il a la désagréable surprise de tomber le terrible Mukuro et sa bande de pirates, anciens camarades de Mugen. Ce dernier avait réussi, à l’époque, à quitter le gang en feintant sa mort, échappant de peu aux les autorités locales. Mukuro, cependant, est loin d’avoir oublié le déserteur, et il lui demande de l’aider sur un dernier gros coup.',
    type: 'Seinen',
    picture: '../assets/samuraiChamploo/013.jpeg',
    created: new Date('26 août 2004'),
    link1: '//ok.ru/videoembed/859875052082',
    link2: '',
    link3: '',
  },
  {
    episode: 14,
    season: 1,
    title : 'Les Flibustiers de la nuit, seconde partie',
    summary: 'Le plan de Mukuro pour aborder le navire du shogun était un piège, et Mugen explose avec le bateau pirate. Jin et Fû, prévenus par Koza, arrivent trop tard. Alors qu’il est sur le point de mourir, Mugen a des visions de son passé à Satsuma. Pendant que Fû part à la recherche de son cadavre, Koza demande à Jin de le venger en tuant Mukuro.',
    type: 'Seinen',
    picture: '../assets/samuraiChamploo/014.jpeg',
    created: new Date('2 septembre 2004'),
    link1: '//ok.ru/videoembed/297031305869',
    link2: '',
    link3: '',
  },
  {
    episode: 15,
    season: 1,
    title : 'Fausse Monnaie et petite épée',
    summary: 'Alors qu’ils pêchent, le trio trouve une bourse remplie d’argent, qu’ils s’empressent de dépenser dans la première ville qui se présente à eux. Jin et Mugen ne se gênent pas pour abandonner Fû et fuir au quartier des plaisirs, interdit aux femmes, mais malheureusement pour eux, la maison de passe dans laquelle ils se rendent cache en réalité une forge de faux-monnayeurs, et la prostituée que Mugen choisit se trouve être en réalité un agent infiltré.',
    type: 'Seinen',
    picture: '../assets/samuraiChamploo/015.jpeg',
    created: new Date('9 septembre 2004'),
    link1: '//ok.ru/videoembed/859875183154',
    link2: '',
    link3: '',
  },
  {
    episode: 16,
    season: 1,
    title : 'La Montagne du désespoir',
    summary: 'Alors qu’ils traversent la forêt de l’Ouest, le trio est intrigué par une rumeur au sujet d’un monstre qui hante les montagnes. Ils n’ont cependant pas le temps d’en discuter longtemps car une grosse dispute éclate, et chacun décide de continuer son propre chemin. Alors que Fû fait une dangereuse chute du haut d’une falaise, Mugen est défié par un mystérieux archer, et Jin est attaqué par un samouraï masqué, portant deux katana tout comme lui.',
    type: 'Seinen',
    picture: '../assets/samuraiChamploo/016.jpeg',
    created: new Date('16 septembre 2004'),
    link1: '//ok.ru/videoembed/859875248690',
    link2: '',
    link3: '',
  },
  {
    episode: 17,
    season: 1,
    title : 'Berceuse pour un damné',
    summary: 'Fû est repêchée par Okuru, qui refuse de devenir son nouveau compagnon de route même si tous deux se rendent vers l’ouest. Après avoir été faussement pris pour cible par la police, Mugen se met à la recherche d’Okuru, que l’on dit atteint de folie. Jin, qui a ramassé une sandale de Fû dérivant au bord de la rivière, finit par retrouver la jeune femme, bien en vie, mais quelques secondes plus tard, ils se font attaquer par Yukimaru.',
    type: 'Seinen',
    picture: '../assets/samuraiChamploo/017.jpeg',
    created: new Date('23 septembre 2004'),
    link1: '//ok.ru/videoembed/859875314226',
    link2: '',
    link3: '',
  },
  {
    episode: 18,
    season: 1,
    title : 'La Guerre des mots',
    summary: 'Jin et Fû se rendent compte que Mugen ne sait pas lire. Alors que ce dernier se fait embarquer par un ivrogne qui s’est mis en tête de lui apprendre, les deux autres se retrouvent au milieu d’un différend entre deux jumeaux, héritiers du même dojo. Le duel au sabre étant dépassé, Jin et Fû leur proposent un marché : celui qui taguera le mur le plus dangereux de la ville sortira vainqueur du conflit.',
    type: 'Seinen',
    picture: '../assets/samuraiChamploo/018.jpeg',
    created: new Date('22 janvier 2005'),
    link1: '//ok.ru/videoembed/859875772978',
    link2: '',
    link3: '',
  },
  {
    episode: 19,
    season: 1,
    title : 'Mésentente cordiale',
    summary: 'Alors que ses deux compagnons de route sont partis chercher de quoi manger et croisent la route d’un héros chrétien, Fû vient en aide à une jeune femme, Yuri, poursuivie par des brigands. Celle-ci avoue connaître le samouraï qui sent le tournesol, mais elle n’a malheureusement pas le temps d’en dire plus car les brigands réapparaissent et la kidnappent. En partant à sa recherche, Mugen, Jin et Fû arrivent dans un mystérieux village abritant des chrétiens. Cependant, ils découvrent rapidement qu’il cache également un gros trafic d’armes.',
    type: 'Seinen',
    picture: '../assets/samuraiChamploo/019.jpeg',
    created: new Date('29 janvier 2005'),
    link1: '//ok.ru/videoembed/859876756018',
    link2: '',
    link3: '',
  },
  {
    episode: 20,
    season: 1,
    title : 'La Complainte du piège, premier couplet',
    summary: 'Mugen, Jin et Fû rencontrent une goze, Sara, dans une auberge. Ils font rapidement connaissance et décident de continuer leur route ensemble. Mais alors que tout se passe bien, Sara annonce qu’elle voudrait retrouver son fils perdu. Comme elle aussi a besoin de protection, elle pose Fû devant une alternative : elle lui demande de choisir entre Jin et Mugen.',
    type: 'Seinen',
    picture: '../assets/samuraiChamploo/020.jpeg',
    created: new Date('5 février 2005'),
    link1: '//ok.ru/videoembed/859877214770',
    link2: '',
    link3: '',
  },
  {
    episode: 21,
    season: 1,
    title : 'La Complainte du piège, second couplet',
    summary: 'Le combat contre Sara commence à tourner mal pour Jin, qui arrive in extremis à les faire tomber tous deux dans la rivière. Mugen et Fû apprennent que le pont qui était sur la route de leurs amis a été détruit et retrouvent Sara, inanimée, mais pas Jin. Mugen, qui n’accepte pas la mort de ce dernier, inspecte les lieux et comprend très vite que la goze est la responsable. Il comprend également qu’il est le prochain sur sa liste et se retrouve rapidement lui aussi en bien mauvaise posture.',
    type: 'Seinen',
    picture: '../assets/samuraiChamploo/021.jpeg',
    created: new Date('12 février 2005'),
    link1: '//ok.ru/videoembed/859877280306',
    link2: '',
    link3: '',
  },
  {
    episode: 22,
    season: 1,
    title : 'Quatrième Dimension',
    summary: 'Alors qu’ils se disputent pour des champignons, le sol se dérobe sous les pieds de Mugen, Jin et Fû, qui atterrissent dans une mystérieuse carrière. Un dénommé Shige, prétendant être l’héritier du clan Heike, leur propose dix pour cent d’un trésor caché sous les pierres s’ils l’aident à le déloger. Ils acceptent le marché, mais vont vite comprendre que la carrière est bien plus dangereuse qu’ils ne le pensaient.',
    type: 'Seinen',
    picture: '../assets/samuraiChamploo/022.jpeg',
    created: new Date('19 février 2005'),
    link1: '//ok.ru/videoembed/859877542450',
    link2: '',
    link3: '',
  },
  {
    episode: 23,
    season: 1,
    title : 'Le Blues du base-ball',
    summary: 'Incapable de payer la note d’un restaurant, Mugen prend la fuite, laissant Jin et Fû sur place. Il se fait rattraper par un ancien ninja Oniwaban qui propose de payer leur facture s’ils acceptent tous les trois de participer à un match de baseball qui décidera de leur destinée. En effet, un peu plus tôt, des Américains ont débarqué sur la côte malgré l’interdiction, menaçant la tranquillité des habitants.',
    type: 'Seinen',
    picture: '../assets/samuraiChamploo/023.jpeg',
    created: new Date('26 février 2005'),
    link1: '//ok.ru/videoembed/312603183744',
    link2: '',
    link3: '',
  },
  {
    episode: 24,
    season: 1,
    title : 'Drôle d\'endroit pour une rencontre',
    summary: 'Approchant enfin d’Ikitsuki, Mugen, Jin et Fû se font des dernières confidences autour d’un feu. Après les avoir pistés pour retrouver enfin la cachette du samouraï qui sent le tournesol, le shogunat, qui a pris conscience du talent de Mugen et Jin, leur envoie son meilleur assassin. Mais Kariya Kagetoki n’est pas la seule menace qui plane au-dessus de leur tête.',
    type: 'Seinen',
    picture: '../assets/samuraiChamploo/024.jpeg',
    created: new Date('5 mars 2005'),
    link1: '//ok.ru/videoembed/859878132274',
    link2: '',
    link3: '',
  },
  {
    episode: 25,
    season: 1,
    title : 'Rencontre du troisième type',
    summary: 'Fû se fait rattraper par de vieux ennemis de Mugen dans les champs de tournesols d’Ikitsuki. Mugen se voit alors obligé de laisser Jin seul face à Kariya pour aller lui sauver la vie. Jin comprend que son lourd passé est intimement relié à celui de Kariya, rendant leur affrontement plus que personnel.',
    type: 'Seinen',
    picture: '../assets/samuraiChamploo/025.jpeg',
    created: new Date('12 mars 2005'),
    link1: '//ok.ru/videoembed/859878263346',
    link2: '',
    link3: '',
  },
  {
    episode: 26,
    season: 1,
    title : 'Le Samurai qui ne sentait plus rien',
    summary: 'Fû rencontre enfin son père, mais elle ne peut venger sa mère tellement l’homme est malade et affaibli. Kariya surgit alors, mettant un terme à la vie du samouraï sous l’ordre du shogunat. Il prend ensuite Fû en chasse, qui se retrouve piégée au bord de la falaise. Jin, qui a survécu, arrive à temps et accepte de se sacrifier pour arrêter Kariya une bonne fois pour toutes. Au même moment, en bas de la falaise, Mugen, grièvement blessé, se fait piéger par une explosion de dynamite.',
    type: 'Seinen',
    picture: '../assets/samuraiChamploo/026.jpeg',
    created: new Date('19 mars 2005'),
    link1: '//ok.ru/videoembed/859878787634',
    link2: '',
    link3: '',
  },


]
