import { Anime } from "../modeles/anime";


export const VINLAND: Anime[] = [
  {
    episode: 1,
    season: 1,
    title: "Quelque part ailleurs",
    summary: "Dans une bataille navale viking à Hjörungavágr , le féroce guerrier Thors Snorresson est fatigué de tuer et après être tombé dans la mer, il abandonne ses hommes. Quinze ans plus tard, Thors mène une vie paisible en Islande avec sa femme Helga, leur jeune fils Thorfinn et leur fille Ylva. Cependant, Thorfinn aspire à l'aventure et a hâte d'en savoir plus sur le monde. Il rêve d'un paradis appelé Vinland dont il entend parler du grand aventurier Leif Erikson. Un jour, Thors recueille un esclave en fuite. Le lendemain, le maître de l'esclave, le brutal Halfdan, arrive au village exigeant que l'esclave soit rendu. Thors refuse et achète l'esclave pour le prix de huit moutons. Cependant, l'esclave meurt bientôt et les enfants de Thor sont en colère contre sa décision.",
    type: 'Seinen',
    picture: '../assets/vinland/001.jpeg',
    created: new Date('8 juillet 2019'),
    link1: "https://www.youtube.com/embed/RnPutJEd6II",
    link2: '',
    link3: '',
  },
  {
    episode: 2,
    season: 1,
    title: "Épée",
    summary: "En l'an 1002, la guerre entre l'Angleterre et le Danemark s'intensifie et les Anglais massacrent une bande de Vikings en Northumbrie . Une bande de Jomsvikings, dirigée par l'intimidant Floki, visite le village de Thorfinn pour enrôler Thors dans leur guerre contre les Anglais. Thors était leur ancien commandant, connu sous le nom de Troll de Jom. Il est obligé de rejoindre Floki, avec un navire et des hommes, afin de protéger les villageois d'être pris en otage. Thorfinn et les jeunes hommes du village sont excités à l'idée d'aller à la guerre, mais ils ont peu de compréhension de ce que c'est vraiment. Pendant ce temps, dans les îles Féroé, Floki conspire avec Askeladd pour massacrer Thors et son équipage une fois arrivés, en guise de punition pour avoir déserté quinze ans plus tôt.",
    type: 'Seinen',
    picture: '../assets/vinland/002.jpeg',
    created: new Date('15 juillet 2019'),
    link1: "https://www.youtube.com/embed/kwBkqc2Hr28",
    link2: '',
    link3: '',
  },
  {
    episode: 3,
    season: 1,
    title: "Troll",
    summary: "Askeladd, le chef d'une bande d'une centaine de Vikings, marchande avec Floki et exige le double du prix pour tuer Thors. De retour au village, les jeunes hommes bourdonnent d'excitation alors qu'ils se préparent pour leur première bataille. Avec cinq hommes du village et l'équipage de Leif Erikson, ils ont embarqué sur deux navires pour rencontrer Askeladd. Cependant, Leif Erikson révèle à une jeune femme que Thors n'a pas l'intention d'emmener les jeunes hommes sur le champ de bataille. Une fois en mer, les jeunes hommes trouvent les choses difficiles et Thors découvre avec colère que Thorfinn s'est caché sur le navire. Lorsqu'ils s'arrêtent pour se reposer et se ravitailler aux îles Féroé, ils sont pris dans un piège tendu par Floki. Un combattant, Bjorn, mange un champignon agaric et se prépare à combattre Thors seul pour tester ses compétences, mais Thors saute à bord de leur vaisseau et les attaque à la place.",
    type: 'Seinen',
    picture: '../assets/vinland/003.jpeg',
    created: new Date('22 juillet 2019'),
    link1: "https://www.youtube.com/embed/1MgJzmX4xAU",
    link2: '',
    link3: '',
  },
  {
    episode: 4,
    season: 1,
    title: "Un véritable guerrier",
    summary: "Thors avance à travers les hommes d'Askeladd, les battant mais ne les tuant pas, jusqu'à ce qu'il fasse face à Bjorn qui est dans une rage berserker après avoir mangé le champignon. Il bat Bjorn et défie Askeladd en duel. Après un combat acharné à l'épée, Thors bat Askeladd, mais se rend pour sauver Thorfinn et ses villageois. Il est ensuite tué par une volée de flèches. Ayant été témoin de la mort de son père, Thorfinn s'embarque sur le navire capturé et jure de se venger d'Askeladd.",
    type: 'Seinen',
    picture: '../assets/vinland/004.jpeg',
    created: new Date('29 juillet 2019'),
    link1: "https://www.youtube.com/embed/DlRkB2l9F2o",
    link2: '',
    link3: '',
  },
  {
    episode: 5,
    season: 1,
    title: "Le Fils du Troll",
    summary: "Askeladd et ses hommes débarquent en Angleterre près de la rivière Humber pour se ravitailler et pillent un village local. Thorfinn se précipite à terre et pendant la nuit se prépare à tuer Askeladd endormi mais ne peut pas le faire. Thorfinn s'entraîne seul dans les bois avant de sortir pour défier Askeladd en duel. Thorfinn est à nouveau facilement vaincu, mais Askeladd reconnaît sa force et promet à Thorfinn une chance de le combattre à nouveau s'il fait ses preuves au combat.",
    type: 'Seinen',
    picture: '../assets/vinland/005.jpeg',
    created: new Date('5 août 2019'),
    link1: "https://www.youtube.com/embed/XIxK8Cjxv4s",
    link2: '',
    link3: '',
  },
  {
    episode: 6,
    season: 1,
    title: "Le voyage commence",
    summary: "Askeladd et ses hommes rament en amont jusqu'à Gainsborough où ils trouvent une bande de Vikings morts. Thorfinn suit, écoeuré par la puanteur de la mort dans l'air. Askeladd conclut un accord avec les forces danoises pour se joindre à leur campagne de conquête de l'Angleterre pour de l'argent et du butin. Cette nuit-là, les Britanniques les attaquent, tirant des volées de flèches dans leur camp, tuant un certain nombre d'hommes avant qu'ils ne répliquent. Thorfinn essaie d'entrer dans la bataille et est piégé par un épéiste anglais, mais Thorfinn est sauvé par Askeladd. Néanmoins, Thorfinn finit par se défendre et tue pour la première fois - un soldat anglais. Thorfinn rejoint le groupe d'Askeladd et au cours des années suivantes, il perfectionne ses talents de combattant. Il devient un combattant impitoyable avec son épée courte, avide d'une revanche contre Askeladd. Thorfinn est grièvement blessé à East Anglia et est secouru par une fille anglaise et sa gentille mère. Cependant, il signale plus tard à Askeladd dont les navires sont ancrés au large et ses hommes débarquent et attaquent le village.",
    type: 'Seinen',
    picture: '../assets/vinland/006.jpeg',
    created: new Date('12 août 2019'),
    link1: "https://www.youtube.com/embed/HN6iWS-YeS0",
    link2: '',
    link3: '',
  },
  {
    episode: 7,
    season: 1,
    title: "Les Normands",
    summary: "Le roi danois, Sweyn Forkbeard , retire ses troupes d'Angleterre au cours de l'hiver. L'invasion de l'Angleterre étant en attente, la bande d'Askeladd a mis le cap sur des opportunités en France. Ils proposent leurs services aux Normands et Thorfinn, devenu un jeune homme, est envoyé pour négocier. Leur plan se passe bien et la bande d'Askeladd pille le trésor du fort et Thorfinn livre la tête de leur chef à Askeladd. Askeladd accepte finalement d'honorer son contrat de duel avec Thorfinn.",
    type: 'Seinen',
    picture: '../assets/vinland/007.jpeg',
    created: new Date('19 août 2019'),
    link1: "https://www.youtube.com/embed/5yAPsjiVPJc",
    link2: '',
    link3: '',
  },
  {
    episode: 8,
    season: 1,
    title: "Au-delà de la mer",
    summary: "Askeladd et ses hommes retournent dans le village du seigneur féodal Gorm, avide d'argent, dans la péninsule du Jutland, avec le butin de leurs aventures. Thorfinn a un match revanche avec Askeladd, seulement pour être vaincu quand Askeladd le pousse à faire une attaque en colère et imprudente. En 1013, le roi danois Sweyn mène une invasion du nord de l'Angleterre, avec des forces danoises et des mercenaires vikings tels qu'Askeladd débarquant près de Gainborough, mais ils s'arrêtent dans la ville marchande fortement défendue de Londres .",
    type: 'Seinen',
    picture: '../assets/vinland/008.jpeg',
    created: new Date('26 août 2019'),
    link1: "https://www.youtube.com/embed/HtaVupLYSi0",
    link2: '',
    link3: '',
  },
  {
    episode: 9,
    season: 1,
    title: "La Bataille du pont de Londres",
    summary: "Les forces danoises sont arrêtées au pont fortifié de Londres, gardé par Thorkell the Tall - un redoutable Danois qui soutient les Anglais. Askeladd offre à Thorfinn un autre duel s'il peut délivrer la tête de Thorkell. Thorfinn attaque Thorkell, mais le géant Viking est trop expérimenté et Thorfinn doit battre en retraite avec ses blessures. Arrivé dans une impasse, le roi Sweyn laisse son fils, le prince Canut, maintenir le siège avec Ragnar, tandis que le reste de l'armée se dirige vers le Wessex .",
    type: 'Seinen',
    picture: '../assets/vinland/009.jpeg',
    created: new Date('2 septembre 2019'),
    link1: 'https://www.youtube.com/embed/o-ki3w_HmSU',
    link2: '',
    link3: '',
  },
  {
    episode: 10,
    season: 1,
    title: "Ragnarok",
    summary: "Les hommes de Ragnar deviennent impatients avec le siège, stimulés par les railleries de Thorkell, mais il les garde sous contrôle. Les hommes d'Askeladd s'ennuient également à cause de l'inactivité, mais après avoir appris que Thorkell est parti à la poursuite de l'armée de Sweyn, il renouvelle l'assaut sur Londres.",
    type: 'Seinen',
    picture: '../assets/vinland/010.jpeg',
    created: new Date('16 septembre 2019'),
    link1: 'https://www.youtube.com/embed/4D5P9oR6wKM',
    link2: '',
    link3: '',
  },
  {
    episode: 11,
    season: 1,
    title: "Un pari",
    summary: "Thorkell continue son chemin pour attraper l'armée de Sweyn avec Ragnar et le prince Canute comme otages, mais un groupe de l'armée danoise les rattrape et menace de les anéantir. Thorkell libère astucieusement les otages, mais pousse ensuite les soldats danois dans une attaque insensée qu'ils ne peuvent pas gagner, combattant au corps à corps. Pendant ce temps, Askeladd déclenche un feu de forêt, provoquant de la fumée qui désoriente les combattants, et envoie Thorfinn pour capturer le prince. Thorkell décide de ne pas gaspiller ses hommes en combattant Thorfinn et lui permet de prendre le prince.",
    type: 'Seinen',
    picture: '../assets/vinland/011.jpeg',
    created: new Date('23 septembre 2019'),
    link1: 'https://www.youtube.com/embed/zWpRCts9PVs',
    link2: '',
    link3: '',
  },
  {
    episode: 12,
    season: 1,
    title: "Le pays sur la rive lointaine",
    summary: "Askeladd a maintenant le prince Canute, mais il est vivement poursuivi par Thorkell et ses hommes et envoie des renforts. Ils atteignent le canal de Bristol , et sont accueillis par le général gallois Gratianus avec des renforts du royaume de Morgannwg . Cependant, lorsqu'ils atteignent le royaume de Brycheiniog , ils sont entourés d'archers au sommet des collines.",
    type: 'Seinen',
    picture: '../assets/vinland/012.jpeg',
    created: new Date('30 septembre 2019'),
    link1: 'https://www.youtube.com/embed/0cAjdlCnXMw',
    link2: '',
    link3: '',
  },
  {
    episode: 13,
    season: 1,
    title: "Fils de héros",
    summary: "En novembre 1013 après JC, Floki rapporte au roi du Danemark que les forces danoises ont vaincu les Anglais dans le Wessex , mais il doit également signaler que Thorkell a peut-être pris Canute. Pendant ce temps au Pays de Galles, Asser de Brycheiniog bloque le passage d'Askeladd jusqu'à ce qu'Askeladd révèle qu'il a une ascendance galloise, prétendant être un descendant du roi Artorius et travaillera pour protéger le Pays de Galles lorsque l'Angleterre sera vaincue par les Danois. Le prince Canute ne peut pas se résoudre à affronter les Gallois, alors Askeladd et ses hommes rendent leurs armes pour passer en toute sécurité à travers Brycheiniog, apparaissant comme s'ils étaient des prisonniers. Au nord de la Mercie, ils changent de direction pour rejoindre la principale armée danoise à Gainborough.",
    type: 'Seinen',
    picture: '../assets/vinland/013.jpeg',
    created: new Date('7 octobre 2019'),
    link1: 'https://www.youtube.com/embed/EVkCwxLr3QA',
    link2: '',
    link3: '',
  },
  {
    episode: 14,
    season: 1,
    title: "La Lumière de l'aube",
    summary: "Alors qu'Askeladd et ses hommes traversent le nord de la Mercie, ils sont pris dans les neiges du début de l'hiver. Froids et affamés, ils tombent sur un village de chrétiens et le pillent, emportant toute leur nourriture. Ils tuent les villageois afin que personne ne puisse révéler leur emplacement. Le seul survivant est une jeune femme qui se trouvait dans les bois à l'extérieur du village en quête de pénitence à cause d'une bague bon marché qu'elle avait volée lors d'une foire.",
    type: 'Seinen',
    picture: '../assets/vinland/014.jpeg',
    created: new Date('14 octobre 2019'),
    link1: 'https://www.youtube.com/embed/mivCW2D5lpw',
    link2: '',
    link3: '',
  },
  {
    episode: 15,
    season: 1,
    title: "Après Yule",
    summary: "Thorkell atteint Gloucester , mais apprend que les nobles anglais sont fatigués de la guerre et sont prêts à accepter la domination danoise. Certaines troupes anglaises trouvent le groupe d'Askeladd, et ses hommes commencent à penser que sa chance est épuisée. Askeladd ordonne à Bjorn de tuer le tuteur du prince Canute, Ragnar, le blâmant sur une escarmouche avec les Anglais et espérant que le prince deviendra un chef qu'il pourra suivre.",
    type: 'Seinen',
    picture: '../assets/vinland/015.jpeg',
    created: new Date('21 octobre 2019'),
    link1: 'https://www.youtube.com/embed/JFgBMsPOdAs',
    link2: '',
    link3: '',
  },
  {
    episode: 16,
    season: 1,
    title: "Histoire de bêtes",
    summary: "Askeladd dit à Thorfinn de garder Canute et torture un capitaine anglais capturé, à la recherche d'informations. Il est interrompu pour être informé que Thorkell approche. Craignant la défaite, certains de ses hommes décident de déserter et tentent de rejoindre Thorkell, qui les tue à leur arrivée. Askeladd atteint la rivière Severn supérieure peu profonde et coupe un petit pont. Cependant, Thorkell les rattrape. De nombreux hommes d'Askeladd commencent à douter de ses capacités de leader et il est confronté à une mutinerie à grande échelle.",
    type: 'Seinen',
    picture: '../assets/vinland/016.jpeg',
    created: new Date('28 octobre 2019'),
    link1: 'https://www.youtube.com/embed/SuIC48aaxfA',
    link2: '',
    link3: '',
  },
  {
    episode: 17,
    season: 1,
    title: "Servant",
    summary: "Menacé par une mutinerie, Askeladd se souvient avoir nourri sa mère malade pendant qu'elle lui parlait de leur ancêtre, le roi Artorius, qui se remettait de ses blessures au combat à Avalon, un endroit paradisiaque d'où il reviendrait pour sauver leur peuple de ses souffrances. Askeladd informe ses hommes de sa haine secrète des Danois et se déchaîne immédiatement et tue deux d'entre eux. Bjorn décolle dans le traîneau avec Thorfinn, Canut et le prêtre ivre, avec dix hommes à sa poursuite, laissant Askeladd faire face au reste de ses anciens fidèles. Les hommes poursuivant le traîneau l'écrasent avec succès et capturent le prince, tandis que Thorfinn vole l'un de leurs chevaux et revient pour empêcher quiconque de tuer Askeladd avant qu'il ne puisse se venger. Pendant ce temps, Askeladd tue plusieurs de ses anciens camarades mais est paralysé par une volée de flèches. Thorkell arrive et donne aux hommes d'Askeladd l'occasion de mourir au combat. Soudain, Thorfinn fait irruption et défie Thorkell en duel contre Askeladd.",
    type: 'Seinen',
    picture: '../assets/vinland/017.jpeg',
    created: new Date('4 novembre 2019'),
    link1: 'https://www.youtube.com/embed/IlBU2NXsq8E',
    link2: '',
    link3: '',
  },{
    episode: 18,
    season: 1,
    title: "Hors du berceau",
    summary: "Thorfinn affronte Thorkell pour décider du sort d'Askeladd. Pendant ce temps, Canut est toujours allongé dans la neige et rêve de Ragnar, qui s'excuse de l'avoir élevé comme un fils au lieu d'un prince, et fait ses adieux. Après s'être réveillé de sa rêverie, Canut a une révélation en parlant au prêtre qui parle de la différence entre l'amour et la discrimination, et Canut décide d'affronter lui-même la situation actuelle. Il baisse les yeux et calme le berserker Bjorn, qui est poignardé par Atli, l'un des hommes d'Askeladd. Il ordonne au prêtre de guérir Bjorn pendant qu'il accepte le défi d'être roi. De retour au duel, Thorkell donne un coup de pied à Thorfinn, l'envoyant s'écraser contre les arbres à proximité.",
    type: 'Seinen',
    picture: '../assets/vinland/018.jpeg',
    created: new Date('18 novembre 2019'),
    link1: 'https://www.youtube.com/embed/QHw8s6M1b_k',
    link2: '',
    link3: '',
  },{
    episode: 19,
    season: 1,
    title: "Un front uni",
    summary: "Thorfinn a un bras et des côtes cassés à cause du coup de pied de Thorkell, et Thorkell lui permet d'être traité par Askeladd. Thorkell explique que lui et Thors étaient des commandants des Jomsvikings et que leur chef Sigvaldi, qui était le frère aîné de Thorkell, lui a donné l'une de ses filles, Helga. Cela signifie que Thorkell est le grand-oncle de Thorfinn. Thors est considéré comme mort après être tombé dans la mer lors de la bataille navale de Hjörungavágr, mais trois mois après des funérailles pour lui, Thorkell l'a trouvé en train de quitter les Jomsvikings avec Helga et leur fille. Thors a renoncé à une vie de combat et après avoir assommé Thorkell, il est parti. Le duel reprend, mais alors que Thorkell est sur le point de terminer Thorfinn, Askeladd réfléchit la lumière dans les yeux de Thorkell, l'aveuglant un instant, et Thorfinn jette Thorkell au sol en frappant son faible menton, et s'arrache un oeil. Les hommes de Thorkell se préparent à tuer Thorfinn, mais Thorkell les arrête, affirmant que Thorfinn a gagné le duel. Canute arrive sur les lieux et dit à Thorkell qu'il n'y a aucune valeur à le garder en otage parce que le roi Sweyn a déjà choisi son frère aîné Harold comme successeur et s'attend à ce que Canute soit tué au combat. Avec une nouvelle résolution, Canute déclare qu'il marchera contre le roi à Gainsborough, et Askeladd et Thorkell acceptent de le rejoindre.",
    type: 'Seinen',
    picture: '../assets/vinland/019.jpeg',
    created: new Date('25 novembre 2019'),
    link1: 'https://www.youtube.com/embed/imIgtHGVGws',
    link2: '',
    link3: '',
  },
  {
    episode: 20,
    season: 1,
    title: "Couronne",
    summary: "À Gainsborough, Canute et ses partisans affrontent Floki et l'armée danoise, et il demande le passage pour voir le roi Sweyn. Au château, Canute envoie Thorkell boire avec les autres commandants pendant qu'il va affronter le roi, flanqué d'Askeladd et Thorfinn. Ils sentent une embuscade dans la salle obscure et le roi Sweyn confirme qu'il veut la mort de Canut. Le roi Sweyn se prépare à les faire tuer, mais Askeladd intercède et rappelle au roi que Canute a remporté une victoire sur Londres via les forces de Thorkell. Le roi décide d'épargner Canut qui décide qu'il est prudent de s'associer au roi pour le moment. Le frère de Rangar, Gunnar, s'approche de Canut et jure de le servir, mais Askeladd se méfie de lui. Plus tard, Askeladd renvoie Alti et son frère chez eux, lui ordonnant de ne plus jamais lever l'épée.",
    type: 'Seinen',
    picture: '../assets/vinland/020.jpeg',
    created: new Date('2 décembre 2019'),
    link1: 'https://www.youtube.com/embed/ldBAhGT81Hc',
    link2: '',
    link3: '',
  },
  {
    episode: 21,
    season: 1,
    title: "Réunion",
    summary: "En 1014, sur instructions du roi Selwyn, Canute emmène ses partisans à York , une ville danoise occupée dans la région de Northumbria . Alors que leurs bateaux remontent la rivière Ouse, Canute est touché à la poitrine par une flèche d'arbalète tirée par un assassin qui est traqué et tué par Thorfinn. Thorfinn est reconnu par Leif de son village en Islande et ils sont joyeusement réunis. Cependant, Thorfinn n'est pas intéressé à rentrer chez lui, mais a seulement l'intention de se venger d'Askeladd. Pendant ce temps, il est révélé que Canut n'a pas été abattu, mais qu'il s'agissait d'une femme esclave habillée comme son double. Canute ordonne que tout soit fait pour la sauver. En passant Floki, Askeladd en déduit que Canute a des ennemis à York. Il est révélé plus tard qu'Askeladd lui-même a engagé l'assassin pour promouvoir les rumeurs selon lesquelles le roi veut la mort de Canut. Pour faire avancer ses plans, Askeladd fournit également des informations à Gunnar qui espionne pour le roi. Pendant ce temps, Thorfinn dont le bras cassé n'a pas encore guéri, est impatient de régler sa dette avec Askeladd. Thorfinn l'appelle à un duel devant être observé par Canut et Thorkell. Avant de commencer, Bjorn, mortellement blessé, défie Askeladd d'entrerValhalla . Bjorn est vaincu, mais reçoit également les assurances d'Askeladd qu'ils sont de vrais amis avant que ce dernier ne tue miséricordieusement son ami. Askeladd se prépare alors à affronter Thorfinn.",
    type: 'Seinen',
    picture: '../assets/vinland/021.jpeg',
    created: new Date('9 décembre 2019'),
    link1: 'https://www.youtube.com/embed/Mr7vwHmLsHM',
    link2: '',
    link3: '',
  },
  {
    episode: 22,
    season: 1,
    title: "Loup solitaire",
    summary: "Thorfinn et Askeladd se préparent au duel, mais Askeladd jette étonnamment son épée. Thorfinn l'attaque avec colère, mais il ne fait pas le poids face à Askeladd qui s'est battu avec lui plus d'une douzaine de fois et connaît ses mouvements et ses faiblesses. Askeladd bat Thorfinn dans l'inconscience, et Canute arrête le combat quand Askeladd a porté le coup gagnant. Askeladd raconte ensuite son éducation en tant que fils d'une femme esclave, qui a attiré l'attention de son père viking Olaf en raison de ses talents de combattant. Il s'est finalement vengé et a tué Olaf, mais a jeté des soupçons sur un autre fils qui a été exécuté pour le meurtre. Il détaille son mépris pour l'attitude des Vikings qui ne vivent que pour la bataille, la conquête et la vengeance. Il reproche à Thorfinn de n'avoir rien appris alors qu'Askeladd exploitait le garçon à ses propres fins.",
    type: 'Seinen',
    picture: '../assets/vinland/022.jpeg',
    created: new Date('16 décembre 2019'),
    link1: 'https://www.youtube.com/embed/tUO-1thwe7Q',
    link2: '',
    link3: '',
  },
  {
    episode: 23,
    season: 1,
    title: "Erreur de jugement",
    summary: "Pendant son séjour à York, le roi Sweyn convoque le Conseil impérial, mais la situation est tendue parmi les dirigeants danois suite à la tentative d'assassinat de Canut. Sweyn s'adresse aux anciens du Danemark, et après avoir annoncé la conquête viking réussie de l'Angleterre, il loue ouvertement Canute et Thorkell. Il remet le contrôle de Mercie , la partie la plus prospère de l'Angleterre, à Canut et annonce ensuite les préparatifs d'une attaque contre l'Irlande pour se venger de l'humiliation du roi Harald par Brian Boru. Askeladd pense que ses stratégies pour l'ascendant de Canute ont fonctionné, mais il est horrifié lorsque Sweyn annonce également son intention de soumettre le Pays de Galles au printemps prochain, car il pense qu'ils sèment les graines de la rébellion. Pendant ce temps, Thorfin, sévèrement battu, est jeté en prison après avoir semé le trouble dans la rue. Leif Erikson rend visite à Thorfinn en prison et lui promet de le renvoyer en Islande, puis dans le chaud et fertile Vinland. De retour au Conseil impérial, Floki raconte à Sweyn la réaction d'Askeladd à l'attaque annoncée contre le Pays de Galles qui, selon lui, montre une faiblesse pour les Gallois. Askeladd essaie en vain de penser à un plan pour contrecarrer le roi et avoue à Thorkell que sa mère était galloise, mais lui jure de garder le secret. Askeladd est alors convoqué devant le roi, et se demande pourquoi sa chance l'abandonne toujours à la onzième heure.",
    type: 'Seinen',
    picture: '../assets/vinland/023.jpeg',
    created: new Date('23 décembre 2019'),
    link1: 'https://www.youtube.com/embed/grhgD9LUhHM',
    link2: '',
    link3: '',
  },
  {
    episode: 24,
    season: 1,
    title: "FIN DU PROLOGUE",
    summary: "Alors qu'Askeladd reçoit sa récompense pour avoir sauvé le prince Canute, il remet audacieusement en question l'ordre du roi Sweyn de soumettre sa propre patrie du Pays de Galles. Askeladd justifie sa déclaration en disant que le pays montagneux pauvre du Pays de Galles ne vaut pas le coût à conquérir et propose à la place de négocier une paix.",
    type: 'Seinen',
    picture: '../assets/vinland/024.jpeg',
    created: new Date('30 décembre 2019'),
    link1: 'https://www.youtube.com/embed/gQm-gnnjM10',
    link2: '',
    link3: '',
  },
]
